# 미국 시장 데일리 수집 결과 (Collect)
# 기준일: 2026-07-24 (금) · 미국 정규장 종가 기준 · 실행모드: [실적시즌]
# 생성시각(KST): 2026-07-27 09:00

※ 오늘(2026-07-27, 월)은 주말(7/25~26)을 지나 맞이하는 첫 거래일이며, 직전 미국 정규장 마감일은 2026-07-24(금)이다. 이번 주(7/27~31)는 FOMC(7/28~29)와 MSFT·META·AAPL·AMZN 등 빅테크 실적 발표가 몰린 실적시즌 핵심 주간이다.

---

## [1] 미국 주요 지수 + 리스크 지표 〔Daily〕

| 항목 | 종가/수치 | 등락률 | (보도된) 원인 | 출처+태그 |
|---|---|---|---|---|
| S&P500 | 7,411.98 | +0.05% | 파키스탄이 중국 중재로 미-이란 평화협상 물꼬를 트려 한다는 로이터 보도(파키스탄 소식통 인용) 이후 국제유가가 하락하며 장중 낙폭 축소, 보합 마감 | Washington Post · "How major US stock indexes fared Friday 7/24/2026" · 2026-07-24 · washingtonpost.com [P2] |
| NASDAQ | 24,975.82 | -0.64% | 반도체 등 AI 관련 대형기술주 매도세 지속(밸류에이션·AI 설비투자 수익성 우려) | Washington Post · 상동 · 2026-07-24 [P2] |
| Dow | 51,947.25 (+235.60pt) | +0.46% | 전일 급락분 일부 만회, 유가 하락에 따른 인플레 우려 완화 | Washington Post · 상동 · 2026-07-24 [P2] |
| Russell2000 | 2,930 | -0.35%(주1) | 소형주 약세, 주간 기준 지수 전반 하락 마감 | TheStreet · "Stock Market Today (July 24, 2026)" · 2026-07-24 [P2] |
| SOX(필라델피아 반도체지수) | 11,818.89 (-524.95pt) | -4.25% | HBM 증설 둔화 보도·AI 설비투자 수익성 논란에 따른 반도체·메모리주 급락 | Yahoo Finance(^SOX Historical Data) · 2026-07-24 [P3] |
| ES(S&P500 선물, 월요일 아침 기준) | N/A(변동률만 확인) | +0.2% | 월요일 개장 전 소폭 상승 출발 | CNBC · "Stock market next week: Outlook for July 27-31, 2026" · 2026-07-24 [P2] |
| NQ(나스닥100 선물) | N/A(변동률만 확인) | +0.3%(다우선물 +87pt) | 월요일 개장 전 소폭 상승 출발 | CNBC · 상동 · 2026-07-24 [P2] |
| VIX | 18.58 (-0.12pt) | -0.64% | 지정학 리스크 완화 보도에 변동성 소폭 하락 | Yahoo Finance(^VIX Historical Data) · 2026-07-24 [P3] |
| DXY(달러인덱스) | 101.47 | +0.02% | 전일 한달래 고점(101.5) 근접 후 소폭 되돌림, 유가 하락이 금리인상 기대를 일부 완화 | TradingEconomics(ICE 데이터 기반) · 2026-07-24 [P3] |
| WTI | $89.31/배럴 (-$2.88) | -3.12% | 파키스탄발 미-이란 평화협상 가능성 보도로 리스크 프리미엄 축소 | Rigzone · "Brent Pulls Back From $100" 연계 데이터 · 2026-07-24 [P2] |
| Brent | $97.24/배럴 | 약 -4% (6월 말 이후 최대 하루 낙폭) | 상동, 미-이란 협상 기대감에 지정학 리스크 프리미엄 축소 | Rigzone · "Brent Pulls Back From $100" · 2026-07-24 [P2] |
| Gold | $4,052/온스 | +0.06% | 다음주(7/28~29) FOMC 결과 대기 속 보합권 등락 | TradingEconomics · 2026-07-24 [P3] |

(주1) Russell2000 등락률은 자료마다 -0.31%~-0.35%로 소폭 차이가 있어 확정치 아님 — 확인 필요.
(주2) WTI/Brent는 목요일(7/23) 브렌트 $100 돌파 이후 금요일(7/24) 되돌림 국면. 목요일 고점 수치는 이번 표에 포함하지 않음(기준일 종가만 기재).

---

## [2] 금리 / 연준 〔Daily〕

| 항목 | 사실 내용(발언·수치) | 출처+태그 |
|---|---|---|
| 미 국채 2년물 금리 | 4.33% (2026-07-24 기준) | Advisor Perspectives(dshort) · "Treasury Yields Snapshot: July 24, 2026" · 2026-07-24, FRED(DGS2) 데이터 기반 [P1] |
| 미 국채 10년물 금리 | 4.69% (2026-07-24 기준) | 상동, FRED(DGS10) 데이터 기반 [P1] |
| 10Y-2Y 스프레드 | +0.36%p(36bp) | 상동, FRED(T10Y2Y) 데이터 기반 [P1] |
| 연방기금금리 목표 범위 | 3.50~3.75% (2026-06-17 FOMC에서 동결 결정, 신임 의장 케빈 워시 취임 후 첫 회의) | Federal Reserve · FOMC Minutes/Press Conference, 2026-06-17 · federalreserve.gov [P1] |
| 다음 FOMC 회의 | 2026-07-28(화)~29(수) 개최 예정, 아직 미실시(기준일 7/24 시점) | Federal Reserve 공식 일정 [P1] |
| CME FedWatch (2026-07-23 기준) | 7월 회의 동결 확률 약 63.5~65%, 25bp 인상 확률 약 35~36.5% | CBS News · "Will the Federal Reserve raise interest rates?" · 2026-07-23; Forbes · "Markets Price In Rising Odds Of July Fed Rate Hike" · 2026-07-23 [P2] |
| CME FedWatch (9월 회의 전망) | 9월 회의 인상 확률 약 73~82%로 상승(유가발 인플레 우려 반영) | CNBC · "Odds of Federal Reserve rate hike surge as oil prices rip higher" · 2026-07-23; techtimes.com · 2026-07-16 [P2] |
| Fed 의장 케빈 워시 발언(하원 증언, 인용) | "The members of our [Federal Open Market Committee] have no tolerance for persistently elevated inflation. And we share a resolute commitment to restoring price stability." | Federal Reserve · Testimony by Chairman Warsh · 2026-07-14 · federalreserve.gov [P1] |
| 참고: 미국 신규 실업수당 청구건수(7/23 발표, 기준일과 다른 날짜) | 18.7만 건(7/18일 마감 주간), 1969년 이후 최저 수준, 예상치(21만 건) 하회 — 이 수치가 9월 인상 기대 상승에 영향을 준 것으로 보도됨 | Bloomberg · "US Initial Jobless Claims Fall to Lowest Level Since 1969" · 2026-07-23 [P2] |

(주) 워시 의장의 7/24 당일 별도 발언은 검색으로 확인되지 않음 — 상기 인용은 가장 최근 확인된 7/14 하원 증언 발언임.

---

## [3] 주요 경제지표 〔Conditional — 2026-07-24(금) 발표분〕

| 지표 | 발표시각(ET·KST) | 발표치 | 예상치 | 이전치 | 서프라이즈(발표치−예상치) | 출처 |
|---|---|---|---|---|---|---|
| S&P Global 플래시 제조업 PMI | 09:45 ET(발표시각 확인 필요) · 7/24 밤(KST) | 53.8 | 54.4 | 53.9 | -0.6 | CNBC · "S&P Flash U.S. Manufacturing PMI comes in at 53.8 for July" · 2026-07-24 [P2] |
| S&P Global 플래시 서비스업 PMI | 상동 | 51.2 | 51.5 | N/A | -0.3 | mni Markets · "Friday Data Calendar: S&P Global Flash PMIs, New Home Sales" · 2026-07-24 [P2] |
| S&P Global 플래시 종합 PMI | 상동 | 51.9 | 51.8 | N/A | +0.1 | mni Markets · 상동 · 2026-07-24 [P2] |
| 신규주택판매(New Home Sales) | 10:00 ET(발표시각 확인 필요) | 연율 58.0만 채 | 60.6만 채 | N/A | -2.6만 채(전월비 -7.30%, 예상 +4.7%) | mni Markets · 상동 · 2026-07-24 [P2] |

(주) 정확한 발표 시각(ET)은 검색으로 세부 확인되지 않아 통상 발표시각을 병기함 — 확인 필요.

---

## [4] 특징 종목 〔Daily, ±5%+ 등락 또는 거래량 급증, [5]/[5-A]/[6] 대상 제외〕

| 종목 | 티커 | 등락률 | 거래량 | (보도된) 핵심 사실 | 출처+태그 |
|---|---|---|---|---|---|
| 인텔 | INTC | 실적 발표 후 시간외 +12~13% 급등 후 다음날 절반 이상 반납 | N/A | 2분기 매출 YoY +25%(15년래 최고 증가율), non-GAAP EPS $0.42(컨센서스 $0.21~0.22 상회), 다만 GAAP 기준 110억달러 순손실 기록. 7분기 연속 가이던스 상회 | CNBC · "Intel (INTC) earnings report Q2 2026" · 2026-07-23; Investing.com · 어닝콜 트랜스크립트 · 2026-07-23 [P1/P2] |
| 샌디스크 | SNDK | -7.88%~-11%(자료별 상이) | N/A | 메모리주 밸류에이션 부담에 따른 차익실현, 낸드플래시 가격 조정 전망 및 실망스러운 분기 가이던스 | The Motley Fool · "Stock Market Today, July 24: ... Sandisk Tumbles 11%" · 2026-07-24; TradingKey · "SNDK Moved Down by 7.88% on Jul 24" · 2026-07-24 [P2/P3] |
| 마이크론 | MU | -6.99%($990.21→$920.95) | N/A | 최근 급등(머스크의 대규모 메모리 공급계약 공개 영향) 이후 차익실현, 중국 메모리업체와의 경쟁 심화 우려 부각 | TradingKey · "MU Moved Down by 5.50%~6.99% on Jul 24" · 2026-07-24; Yahoo Finance · "Why Micron Stock Is Tumbling Friday" · 2026-07-24 [P2] |

(주) 마이크론 등락률은 출처별로 -5.50%~-6.99%로 편차 있음 — 확정치 확인 필요. 아메리칸익스프레스(-4.41%) 등은 ±5% 기준 미달로 제외.

---

## [5] AI 인프라 — 공급 측 〔Daily〕
(대상: NVDA, AVGO, AMD, TSM, ANET, CRDO, CLS, VRT, SMCI, APLD)

| 기업 | 뉴스 제목 | 사실 내용(무슨 일이) | 출처일자 | 출처+태그 |
|---|---|---|---|---|
| NVDA | SK그룹과 5000억달러+ AI 인프라 파트너십 | SK그룹과 NVIDIA가 글로벌 컴퓨트 수요 대응을 위한 5000억달러 이상 규모의 포괄적 파트너십 계획을 발표 | 2026-07-24 | NVIDIA Newsroom [P1] |
| NVDA | 한국 AI 팩토리 확장(NAVER·Brookfield) | NAVER·NVIDIA·Brookfield가 한국 소버린 AI 팩토리 인프라 확장을 제안, 초기 DSX AI 팩토리 배치 규모를 200MW로 3배 이상 확대 | 2026-07-24 | NVIDIA Newsroom [P1] |
| NVDA | Amkor와 칩 패키징 계약 | Amkor와 15억달러 규모의 칩 패키징 계약 체결 | 2026-07-24(보도 기준) | Bloomberg 보도 인용 [P2] |
| AMD | Advancing AI 2026 – Helios 랙스케일 시스템 양산 시작 | AMD Helios 랙스케일 솔루션 양산 시작, 기가와트급 배치 목표로 주요 AI 기업에 공급 예정. HBM4 탑재 Instinct MI400 시리즈(MI455X) 공개 | 2026-07-22~23 | AMD Newsroom · "AAI 2026: AMD Delivers Full-Stack Compute for the Agentic AI Era" · 2026-07-23 [P1] |
| AMD | EPYC Venice(TSMC 2nm) 양산 램프업 | TSMC 2nm 공정 기반 EPYC Venice 프로세서 양산 램프업 시작, MI450 GPU 연내 대량 출하 예정 | 2026-07-23 | AMD Newsroom [P1] |
| AMD | Anthropic과 MI450 공급 파트너십 | Anthropic에 최대 2GW 규모 MI450 GPU 공급(2027년 초 시작) 파트너십 체결, AMD는 배치 마일스톤 연계 최대 50억달러 투자 약정 | 2026-07-23(보도 기준) | CNBC 등 보도 인용 [P2] |
| TSM | 2026년 capex 가이던스 상향 | 2026년 자본지출 가이던스를 기존 520~560억달러에서 600~640억달러로 상향, 애리조나 추가 1000억달러 투자 발표 | 2026-07-17(실적발표) | Investing.com · "Earnings call transcript: TSMC lifts 2026 outlook" · 2026-07-17 [P1] |
| TSM | 2분기 실적 | 2분기 매출 NT$1.27조(YoY +36%), 매출총이익률 67.7%, 2026년 매출 성장률 가이던스를 기존 '30%대 초반'에서 '40%대 초반'으로 상향 | 2026-07-17 | TSMC 실적발표/어닝콜 [P1] |
| ANET | 2026년 매출 가이던스 상향 | 2026 회계연도 매출 전망을 115억달러로 상향, 2분기(6월 마감) 매출 가이던스 약 28억달러 제시. 실적 발표는 2026-08-04(화) 예정 | 2026-07-06(가이던스 발표) | Arista · 보도자료 · 2026-07-06 [P1] |
| CRDO | 2026 회계연도 매출 3배 성장 | 회계연도 매출이 전년 대비 3배인 13억달러로 성장, 내년 80%대 성장 가이던스 유지 발표(정확한 발표일 특정 어려움) | 확인 필요 | 다수 매체 종합 보도 [N/A] |
| CLS(Celestica) | 실적 발표 예정 | 신규 변동 없음 — 직전 가이던스 유지. 2분기 실적은 2026-07-27(월) 장 마감 후 발표 예정(컨센서스: 매출 43.9억달러, EPS $2.31) | 2026-07-24 시점 기준 예정 | Yahoo Finance · "Celestica to Release Q2 Earnings" · 2026-07-24 [P2] |
| VRT | 2분기 실적 발표 예정 | 신규 변동 없음 — 직전 가이던스 유지. 2분기 실적은 2026-07-29(수) 장 개장 전 발표 예정(사전 가이던스: 매출 32.5~34.5억달러, 유기적 매출성장 20~24%, 조정EPS $1.37~1.43) | 가이던스 발표일 확인 필요 | Yahoo Finance · "Vertiv Announces Date of Second Quarter 2026 Earnings Release" [P2] |
| SMCI | FY26 4분기 예비실적 – 마진 서프라이즈 | 2026-06 마감 4분기 GAAP·비GAAP 매출총이익률 가이던스를 8.2~8.4%에서 15~17%로 상향, 신규수주 600억달러 초과로 역대 최대 백로그 달성, 시간외 +17% | 2026-07-22 | Yahoo Finance · "SMCI Stock Soars as Super Micro Computer's Backlog Surpasses $60 Billion" · 2026-07-22 [P2] |
| SMCI | H15 서버 라인업 공개(주말 뉴스) | 6세대 AMD EPYC 9006 CPU 탑재 H15 서버 포트폴리오 공개, 최대 72 GPU 지원 'Helios 플랫폼' 포함 — 기준일(7/24) 이후 주말(7/26)에 발표된 뉴스로 월요일 장 반영 가능성 있음 | 2026-07-26(일, 주말) | Foreign Policy Journal · "Super Micro Computer... Unveils H15 Server Line" · 2026-07-26 [P3] |
| APLD | Polaris Forge 1 2동 가동 | 노스다코타 Polaris Forge 1 캠퍼스 2번째 건물 1단계(75MW) 가동 개시, 캠퍼스 누적 가동용량 175MW 달성. 완공 시 400MW 계약 규모 | 2026-07-01 | Applied Digital IR · 보도자료 [P1] |
| APLD | 올리버 카운티 3번째 데이터센터 부지 검토 | 노스다코타 올리버 카운티에서 신규 데이터센터 부지 확장 검토, 도로 사용·건설 접근 협약 체결 | 2026-07-10 | Valley News Live · 2026-07-13 [P3] |
| APLD | 계약 임대매출 누적 360억달러 | 5개 AI Factory 캠퍼스 기준 총 계약 임대매출 360억달러, 1.4GW 규모 IT 부하 계약 확보(신규 5번째 리스 체결 시점 기준 수치) | 2026-06-26 | Foreign Policy Journal · "Applied Digital Locks In Fifth Major Lease" · 2026-06-26 [P3] |
| HBM/DRAM | SK하이닉스 HBM4 램프업 지연 | SK하이닉스가 HBM4 생산능력 증설 계획을 2분기에서 3분기로 연기, HBM3E 생산라인 일부를 DDR5로 전환 검토 — NVIDIA 'Rubin' 양산 지연이 배경으로 거론됨 | 2026년 6월 말~7월 보도(정확한 날짜 확인 필요) | TechPowerUp · "SK Hynix Slows Down HBM4 Ramp" [P3] |
| DRAM/NAND 가격 | 2분기 계약가 급등 | 2분기 DRAM 계약가 전분기 대비 +58~63%, 낸드플래시 계약가 +70~75% 전망. 재고 3~5주, 리드타임 30~40주 이상 | 출처일자 확인 필요 | TrendForce/업계 리포트 종합 [N/A] |

---

## [5-A] AI 인프라 — 수요 측 / 하이퍼스케일러 CAPEX 〔Earnings season — 전체 수행〕
(대상: Microsoft, Amazon, Alphabet, Meta)

| 항목 | 사실 내용(발표 수치·문구) | 전분기 대비(산술) | 출처일자 | 출처+태그 |
|---|---|---|---|---|
| Alphabet(GOOGL) 2026년 capex 가이던스 상향 | 2026년 capex 전망을 1800~1900억달러에서 1950~2050억달러로 상향. 2분기 매출 YoY +24%($1,198억), 클라우드 매출 YoY +82%($248억), 백로그 5,140억달러. capex 가이던스 상향에 시간외 주가 하락 | 가이던스 상단 기준 +$150억(약 +8%p 상향 폭) | 2026-07-22(2분기 실적 발표) | CNBC · "Alphabet earnings takeaways: Q2 revenue beats, GOOGL stock sinks on 2026 capex hike" · 2026-07-22 [P1/P2] |
| Microsoft(MSFT) 2026 회계연도 capex 가이던스 | FY26 3분기(1~3월) capex+금융리스 319억달러(YoY +49%). FY26 전체 capex 가이던스 1900억달러(전년비 +61%). 4분기(4~6월) capex는 400억달러 초과 전망 발표됨. FY26 4분기(및 연간) 실적은 2026-07-29(수) 발표 예정 — 아직 미발표 | 3분기 대비 4분기 가이던스는 증가 전망(구체적 QoQ 수치는 실적 발표 후 확인 필요) | 2026-04-29(3분기 실적 발표 시 가이던스 제시) | CNBC · "Microsoft (MSFT) Q3 earnings report 2026" · 2026-04-29 [P1] |
| Meta(META) 2026년 capex 가이던스 | 2026년 capex 가이던스를 1150~1350억달러에서 1250~1450억달러로 상향(1분기 실적 발표 시). 컴포넌트 가격 상승 및 데이터센터 비용 증가가 배경. 2분기 실적은 2026-07-29(수) 발표 예정 — 아직 미발표 | 상단 기준 +100억달러 상향 | 2026-04-29(1분기 실적 발표 시 가이던스 제시) | Yahoo Finance/Fortune · "Meta just bumped its 2026 capex forecast up to as much as $145 billion" · 2026-04-29 [P1/P2] |
| Amazon(AMZN) | 신규 capex 수치 발표 없음(2분기 실적은 2026-07-30 목 발표 예정). 다만 자체 AGI(생성형AI연구)팀 대상 인력 정리(모델 커스터마이징·포스트트레이닝 역할 축소) 진행, AI 인프라(칩·데이터센터) 투자는 지속 중이라고 보도됨 | N/A(실적 미발표) | 2026-07-22(레이오프 보도) | Tech Times · "Amazon Cuts AGI Jobs While Pouring $200 Billion Into AI Infrastructure" · 2026-07-23 [P2] |

(주) MSFT·META·AMZN은 이번 주(7/29, 7/29, 7/30) 실적 발표 예정으로 최신 capex 확정치는 아직 없음 — "실적 발표 예정"으로 표기. AAPL은 하이퍼스케일러 capex 대상이 아니므로 [5-A]에서 제외(일반 이슈는 [6] 참조).

---

## [6] 시총 상위 10 — AI 무관 일반 이슈 〔Earnings season / issue-driven〕
(대상: MSFT, NVDA, AAPL, AMZN, GOOGL, META, AVGO, BRK, TSLA, TSM)

| 기업 | 사실 내용 | 출처일자 | 출처+태그 |
|---|---|---|---|
| TSLA | 2분기 실적 발표: EPS $0.33(컨센서스 $0.50 하회), 연초 이후 미판매 재고 차량 22,000대, 운전자보조 기술 관련 사고 200건 이상 언급. 실적 발표 후 주가 -14.5%(종가 $320, 작년 8월 이후 최저). CEO 일론 머스크는 로보택시 관련 "매우 야심찬 목표지만 사고·피해를 일으키지 않도록 신중해야 한다"고 발언 | 2026-07-23(실적 발표) | Zacks/Yahoo Finance 등 종합 · 2026-07-23~24 [P2] |
| TSLA | 로보택시 관련 논란: 탬파에서 무인 로보택시 서비스 출시 하루 만에 로보택시가 일방통행로를 역주행하는 모습이 목격됨 | 2026-07-24 전후(정확 일자 확인 필요) | 다수 매체 보도 종합 [P3] |
| AAPL | 법무부(DOJ)와 아이폰 반독점 소송 관련 조기 합의 협상 진행 중. 애플은 올해 여러 차례 DOJ에 합의안 제시, 합의 성사 여부는 불확실 | 2026-07-17 | Bloomberg · "Apple, DOJ Hold Early Settlement Talks in Antitrust Lawsuit Over iPhone" · 2026-07-17 [P2] |
| GOOGL(Alphabet) | EU 최고재판소가 안드로이드 반독점 관련 41억유로(약 47억달러) 과징금에 대한 구글의 최종 항소를 기각, 전액 확정. EU 집행위는 별도로 안드로이드 11개 기능을 AI 경쟁사에 개방하고 검색 데이터를 익명화 공유하도록 명령(안드로이드 변경 2027년 7월, 데이터 공유 2027년 1월 시행) | 2026-07-02(과징금 확정), 2026-07-중순(개방명령) | CNBC · "Google loses fight over record $4.7 billion EU antitrust fine" · 2026-07-02 [P2] |
| META | FTC가 2025년 11월 지방법원의 '메타 무혐의(인스타그램·왓츠앱 인수 관련 독점 불인정)' 판결에 불복해 2026년 1월 항소장 제출, 항소심 계속 진행 중 | 2026-01(항소 제기, 이후 진행 상황은 7월 기준 신규 변동 확인 안 됨) | FTC 관련 보도 종합 [P3] |
| AMZN | 워싱턴주 등에서 소프트웨어 엔지니어·시니어 매니저 등 정리해고 지속(WARN 법 신고 기준), 2025년 말 이후 누적 약 3만 명 규모 감원. 반독점·마켓플레이스 규제 우려로 주가 약 -4% 하락 | 2026-07-22~23 | PeopleMatters/Invezz 등 종합 · 2026-07-22~23 [P2/P3] |
| MSFT | FY2026 회계연도 시작(7/1)에 맞춰 매년 반복되는 7월 구조조정 단행, 영업·컨설팅·Xbox 부문 등에서 인력 감축(전체 인력의 최대 2.5% 수준으로 보도). Xbox 사업부는 5년간 200억달러 이상 투입에도 매출 감소 지속 중이라고 사내 공유 | 2026-07-01 전후 | Windows Central/GuruFocus 종합 · 2026-07 [P2/P3] |
| BRK(Berkshire Hathaway) | 워런 버핏이 향후 8년(2034년까지)에 걸쳐 약 1,400억달러 규모 버크셔 지분 전량을 자녀 등에게 증여·처분하는 계획 발표, 게이츠재단 대상 기부는 일시 중단. CEO 그렉 아벨은 미국 시민권 취득(귀화) | 2026-07-14 | Bloomberg · "Warren Buffett to Offload Berkshire Stake in 8 Years" · 2026-07-14 [P1/P2] |
| BRK | 버크셔가 알파벳(Alphabet) 주식 100억달러어치를 직접 매입하기로 합의(거래 완결 여부는 미공식 확인) | 2026-06-01(합의 발표) | Motley Fool 보도 종합 · 2026-06 [P3] |
| AVGO | 신규 변동 없음 — 직전 가이던스 유지(2026-07 초 실적 발표 시 AI 반도체 매출 3분기 YoY +200%(160억달러) 가이던스 제시분에서 추가 변동 없음). ※ AI 관련 수요·공급 뉴스는 [5]로 분류하지 않음(AVGO는 [5] 목록에 미포함, 필요시 참고용으로만 기재) | 확인 필요 | N/A [N/A] |
| TSM | 대만 정부가 대중국 첨단 AI 반도체 수출에 대한 규제 강화 검토 중(위반 시 형사처벌 포함 가능성), 화웨이 등 일부 대상에서 전체 중국 고객으로 확대 검토 — TSMC의 중국 매출 노출도에 영향 가능성 | 2026-06월 보도(진행 중, 7월 기준 확정 여부 확인 필요) | Yahoo Finance/Taipei Times 종합 · 2026-06 [P3] |

---

## [7] 기관·대형 자금 수급 〔Daily〕

| 항목 | 종목 | 사실 내용 | 규모(수치) | 출처+태그 |
|---|---|---|---|---|
| 반도체 ETF 자금 흐름(주간, 참고용) | SOXX | 7/8일 단일 세션 기준 순유입 54.3억달러(AUM 약 463억달러로 급증), 이후 한 주간(7월 초) 반도체 ETF에 총 약 400억달러 유입 보도 — 기준일(7/24) 당일 수치는 확인되지 않음 | $5.43B(7/8 단일세션 기준) | ETF.com · "Semiconductor ETFs Roar Back: SOXX Pulls In $5.4 Billion in a Single Day" · 2026-07-08 [P2] |
| 반도체 ETF 자금 흐름(주간, 참고용) | SMH | 7/8일 기준 +5.52억달러 유입 보도된 반면, 같은 주 -12.4억달러 유출 보도도 존재(자료 간 상이) — 기준일(7/24) 당일 수치 확인 안 됨 | $0.55B 유입 vs $1.24B 유출(자료 상이) | Yahoo Finance · "Daily ETF Flows: SMH Pulls In $1.8B" 등 종합 · 2026-07-08 [P2/P3] |
| QQQ 자금 흐름(참고용) | QQQ | 7월 중 한 주간 80억달러 순유출 보도된 반면, 별도 세션에서 13.7억달러 순유입 보도도 존재 — 기준일 당일 수치 확인 안 됨 | 상이(자료 참조) | Benzinga 등 종합 · 2026-07 [P3] |
| 미결정옵션(콜) 쏠림 | NVDA | $210 콜 스트라이크에 만기 근접 대량 콜 매수 포착 | N/A | StockOptionsChannel · "Unusual Options Volume in TSLA, META, and NVDA Draws Focus to Key July 24, 2026 Strikes" · 2026-07-24 [P3] |
| 미결정옵션(콜) 쏠림 | META | $612.50 스트라이크 부근 콜 매수 집중 | N/A | StockOptionsChannel · 상동 · 2026-07-24 [P3] |
| 이례적 옵션거래량 | TSLA | 상대거래량 기준 가장 두드러진 옵션 활동 포착(실적 발표 다음날) | N/A | StockOptionsChannel · 상동 · 2026-07-24 [P3] |
| 이례적 옵션거래량 | MU, INTC, SMCI, AMD | 옵션 거래량 급증 종목으로 포착됨(메모리·반도체 실적/변동성 이벤트와 맞물림) | N/A | 옵션 스크리너 종합 보도 · 2026-07-24 [P3] |

(주) 블록트레이드·대량매매 관련 기준일 당일(7/24) 구체 수치는 검색으로 확인되지 않아 — N/A(확인 필요). 13F는 분기·45일 지연 공시로 본 절에서 제외.

---

## [7-A] Insider Trading (SEC Form 4) 〔Conditional — 신규 공시 확인분〕

| 기업 | 내부자 | 직책 | 매수/매도 | 거래유형(10b5-1 / 재량 / 옵션행사) | 규모 | 거래일 | 출처 |
|---|---|---|---|---|---|---|---|
| CRDO(Credo Technology) | Daniel W. Fleming | CFO | 매도 | 10b5-1 | 7,580주, $240.50~$249.99/주 | 2026-07-08 | StockTitan · "Credo Technology CFO sells shares under 10b5-1 plan" [P1] |
| CRDO(Credo Technology) | Lam Yat Tung | COO | 매도 | 10b5-1 | 55,998주, 총 $12.6M | 2026-07-15 | The Motley Fool · "Credo Technology COO sells 55,998 shares for $12.6 million" · 2026-07-16 [P2] |

(주) CRDO CTO(Cheng Chi Fung, 7/7·7/14 매도)는 스펙상 우선순위 직책(CEO/CFO/COO/Director)에 해당하지 않아 본 표에서 제외. AVGO 최고법무책임자(Mark Brazeal, 7/10, 25,000주, $401.33 평균가, 10b5-1 여부 불명확 — 재량 매도로 보도됨)도 우선순위 직책 밖이라 제외. NVDA·APLD·VRT·SMCI는 기준일 전후 CEO/CFO/COO/Director 급 신규 Form 4 공시가 검색으로 확인되지 않음 — 해당 4개 기업은 `N/A — Form 4 신규 공시 없음`.

---

## [8] 향후 14일 주요 일정 〔2026-07-27 ~ 2026-08-09〕

### 경제 일정

| 날짜 | 시각(ET·KST) | 이벤트 | 컨센서스 | 이전치 | 출처 |
|---|---|---|---|---|---|
| 2026-07-27(월) | N/A | 6월 내구재수주(Durable Goods Orders) | N/A(확인 필요) | N/A | CNBC · "Stock market next week: Outlook for July 27-31, 2026" · 2026-07-24 [P2] |
| 2026-07-28(화)~29(수) | N/A | FOMC 회의 및 금리 결정(29일 발표) | 동결(63.5~65%) vs 25bp 인상(35~36.5%) — CME FedWatch 7/23 기준 | 3.50~3.75%(유지) | CBS News/CME FedWatch 종합 · 2026-07-23 [P2] |
| 2026-07-30(목) | 08:30 ET · 21:30 KST | 2분기 GDP 속보치(Advance Estimate) | N/A(확인 필요) | N/A | BEA 공식 발표 일정 [P1] |
| 2026-07-30(목) | 08:30 ET · 21:30 KST | 6월 개인소비지출(PCE) 물가지수 | N/A(확인 필요) | N/A | BEA 공식 발표 일정(잠정) [P1] |
| 2026-08-07(금) | 08:30 ET · 21:30 KST | 7월 고용보고서(비농업부문 고용, 실업률) | N/A(확인 필요) | N/A | BLS 공식 발표 일정 [P1] |

(주) 8/1(토) 전후 ISM 제조업 PMI, 8/12 CPI 등은 14일 범위(8/9까지) 밖이거나 정확 일자 확인이 어려워 일부 생략함 — 확인 필요.

### 기업 일정

| 날짜 | 기업 | 이벤트 | 컨센서스 EPS | 컨센서스 매출 | 출처 |
|---|---|---|---|---|---|
| 2026-07-27(월) | Applied Digital(APLD) | FY26 4분기 및 연간 실적 발표(장 마감 후, 컨퍼런스콜 17:00 ET) | N/A(확인 필요) | N/A | Foreign Policy Journal · 2026-07-16 [P2] |
| 2026-07-27(월) | Celestica(CLS) | 2분기 실적 발표(장 마감 후) | $2.31 | $4.39B | Yahoo Finance · "Celestica to Release Q2 Earnings" · 2026-07-24 [P2] |
| 2026-07-29(수) | Microsoft(MSFT) | FY26 4분기 실적 발표(장 마감 후, 컨퍼런스콜 14:30 PT) | N/A(확인 필요) | N/A | Microsoft IR · 2026-07-08 [P1] |
| 2026-07-29(수) | Meta(META) | 2분기 실적 발표(장 마감 후) | N/A(확인 필요) | N/A | CNBC/뉴스 종합 · 2026-07 [P2] |
| 2026-07-29(수) | Vertiv(VRT) | 2분기 실적 발표(장 개장 전, 컨퍼런스콜 11:00 ET) | $1.37~$1.43(가이던스) | $3.25B~$3.45B(가이던스) | Yahoo Finance · "Vertiv Announces Date of Second Quarter 2026 Earnings" [P1] |
| 2026-07-30(목) | Apple(AAPL) | 3분기(회계) 실적 발표(장 마감 후, 컨퍼런스콜 14:00 PT) | $1.89(컨센서스) | $108.89B(컨센서스, YoY +15.8%) | Kiplinger/Seeking Alpha 종합 · 2026-07 [P2] |
| 2026-07-30(목) | Amazon(AMZN) | 2분기 실적 발표(장 마감 후, 컨퍼런스콜 14:00 PT) | $1.85(컨센서스, 확인 필요) | 클라우드(AWS) 매출 약 $40.5B 컨센서스 | Kiplinger/Seeking Alpha 종합 · 2026-07 [P2] |
| 2026-08-04(화) | AMD | 2분기 실적 발표(장 마감 후, 컨퍼런스콜 17:00 ET) | N/A(확인 필요) | N/A | StockTitan · "AMD sets Aug. 4 earnings call" [P1] |
| 2026-08-04(화) | Arista Networks(ANET) | 2분기 실적 발표(장 마감 후) | N/A(확인 필요) | 자체 가이던스 약 $2.8B | Arista IR · 보도자료 · 2026-07-06 [P1] |

---

## [9] 오늘의 사실 목록 (순위 없음)

- [1] S&P500 7,411.98(+0.05%), 나스닥 24,975.82(-0.64%), 다우 51,947.25(+0.46%) 마감(2026-07-24) · Washington Post [P2]
- [1] SOX지수 11,818.89(-4.25%)로 반도체주 급락 마감 · Yahoo Finance [P3]
- [1] WTI $89.31(-3.12%), 브렌트 $97.24(약 -4%)로 급락, 파키스탄 중재 미-이란 협상 가능성 보도가 배경 · Rigzone [P2]
- [1] VIX 18.58(-0.64%), DXY 101.47(+0.02%), 금 $4,052/온스(+0.06%) · Yahoo Finance/TradingEconomics [P3]
- [1] 월요일(7/27) 아침 선물: S&P500 +0.2%, 나스닥100 +0.3%, 다우선물 +87pt · CNBC [P2]
- [2] 미 국채 2년물 4.33%, 10년물 4.69%, 스프레드 +36bp(2026-07-24) · FRED 기반 [P1]
- [2] 연방기금금리 3.50~3.75% 유지 중(6/17 FOMC), 다음 회의 7/28~29 예정, CME FedWatch 동결 63.5~65% vs 인상 35~36.5%(7/23 기준) · CBS/Forbes [P2]
- [2] 9월 FOMC 인상 확률은 73~82%로 상승 · CNBC [P2]
- [2] Fed 의장 케빈 워시: "인플레이션 지속에 대해 무관용 원칙, 물가안정 회복에 확고히 전념"(7/14 하원 증언 인용) · Federal Reserve [P1]
- [2] 참고: 7/23 발표 신규 실업수당 청구 18.7만 건, 1969년 이후 최저(예상 21만 건 하회) · Bloomberg [P2]
- [3] S&P Global 7월 플래시 제조업 PMI 53.8(예상 54.4), 서비스업 51.2(예상 51.5), 종합 51.9(예상 51.8) · CNBC/mni [P2]
- [3] 6월 신규주택판매 연율 58.0만 채(예상 60.6만 채, 전월비 -7.30%) · mni Markets [P2]
- [4] 인텔 실적 발표 후 시간외 +12~13% 급등했으나 다음날 상당폭 반납(매출 YoY+25%, EPS 서프라이즈에도 GAAP 110억달러 순손실) · CNBC [P1/P2]
- [4] 샌디스크 -7.88%~-11%, 마이크론 -6.99% 급락(메모리주 밸류에이션 부담·차익실현) · Motley Fool/TradingKey [P2]
- [5] NVIDIA-SK그룹 5000억달러+ AI 인프라 파트너십, NAVER·Brookfield와 한국 AI 팩토리 200MW 확장 발표(7/24) · NVIDIA Newsroom [P1]
- [5] AMD Advancing AI 2026서 Helios 랙스케일 양산 시작, MI400 시리즈(HBM4 탑재) 공개, Anthropic과 최대 2GW MI450 공급 계약 · AMD Newsroom [P1]
- [5] TSMC 2026년 capex 가이던스 520~560억→600~640억달러 상향, 애리조나 추가 1000억달러 투자, 2분기 매출 YoY+36%(7/17) · TSMC IR [P1]
- [5] Super Micro FY26 4분기 예비실적에서 매출총이익률 가이던스 8.2~8.4%→15~17%로 상향, 신규수주 600억달러 초과(7/22) · Yahoo Finance [P2]
- [5] Applied Digital, Polaris Forge 1 캠퍼스 2동 가동(75MW, 누적 175MW, 7/1) · Applied Digital IR [P1]
- [5] SK하이닉스, HBM4 램프업을 2분기→3분기로 연기, DDR5 전환 검토(6월 말~7월 보도) · TechPowerUp [P3]
- [5-A] Alphabet 2026년 capex 가이던스 1800~1900억→1950~2050억달러로 상향, 클라우드 매출 YoY+82%(7/22) · CNBC [P1/P2]
- [5-A] Meta 2026년 capex 가이던스(1분기 발표분) 1150~1350억→1250~1450억달러로 상향(4/29), 2분기 실적은 7/29 예정 · Yahoo/Fortune [P1]
- [5-A] Microsoft FY26 3분기 capex $319억(YoY+49%), 연간 가이던스 1900억달러, FY26 4분기 실적은 7/29 예정 · CNBC [P1]
- [5-A] Amazon AGI팀 정리해고 진행(7/22), AI 인프라 투자는 지속, 2분기 실적은 7/30 예정 · Tech Times [P2]
- [6] 테슬라 2분기 EPS $0.33(컨센서스 $0.50 하회), 실적 발표 후 -14.5%(7/23) · Zacks/Yahoo 종합 [P2]
- [6] 애플, DOJ와 아이폰 반독점 소송 조기 합의 협상 진행 중(7/17) · Bloomberg [P2]
- [6] 구글, EU 안드로이드 반독점 41억유로 과징금 최종 확정(7/2), 안드로이드 기능 개방 명령(7월 중순) · CNBC [P2]
- [6] 워런 버핏, 8년에 걸쳐 버크셔 지분 약 1,400억달러 전량 증여·처분 계획 발표(7/14) · Bloomberg [P1/P2]
- [6] 대만 정부, 대중국 AI 반도체 수출 규제 강화 검토(형사처벌 포함 가능성, 확정 여부 확인 필요) · Yahoo/Taipei Times [P3]
- [7] SOXX 7/8일 단일세션 54.3억달러 순유입(기준일 당일 수치는 미확인) · ETF.com [P2]
- [7] 7/24 옵션시장에서 NVDA $210콜, META $612.50콜 부근 매수 집중, TSLA·MU·INTC·SMCI·AMD 옵션거래량 급증 · StockOptionsChannel [P3]
- [7-A] Credo Technology CFO(7/8, 7,580주)·COO(7/15, 55,998주) 10b5-1 매도 공시 확인 · StockTitan/Motley Fool [P1/P2]
- [8] FOMC 7/28~29, MSFT·META 7/29, AAPL·AMZN 7/30, AMD·ANET 8/4, 고용보고서 8/7 예정 · 각 사 IR/BLS 종합 [P1/P2]

---

### 자체 점검(Self-check) 메모
- 파이어월 위반(투자의견·전망·별점·AI영향도·수혜주 추론·TOP10 재랭킹) 여부 검토 후 발견 시 삭제 완료.
- 모든 수치·뉴스에 출처+태그 부기, 불확실 항목은 N/A 또는 "확인 필요"로 표기.
- 동일 사안 중복 보도는 대표 출처 1건으로 정리(추가 출처는 병기).
- [5](공급)·[5-A](수요/하이퍼스케일러)·[6](일반 이슈) 분류 기준에 따라 AI 관련 뉴스와 일반 규제·인사 뉴스를 구분.
- capex/가이던스/실적 항목에는 발표일자를 표기.
- Form 4는 거래유형(10b5-1/재량/옵션행사)을 사실 기준으로만 분류, 해석 없음.
- [9]는 순위가 아닌 섹션 순서의 사실 나열임.
