# 미국 시장 데일리 수집 결과 (Collect)
# 기준일: 2026-08-05 (수) · 미국 정규장 종가 기준 · 실행모드: 실적시즌 (하이퍼스케일러 4사 및 반도체 AI인프라 다수 기업 최근 1~2주 내 실적 발표, SMCI 8/11 실적 예정)
# 생성시각(KST): 2026-08-06 08:20

> 참고: 웹검색으로 확정한 현재 날짜는 2026-08-06(목, KST) 오전이다. 미국 정규장은 미개장 상태이므로, 아래 시장 데이터는 직전 정규장인 2026-08-05(수, ET) 종가 기준이다.

---

## [1] 미국 주요 지수 + 리스크 지표

| 항목 | 종가/수치 | 등락률 | (보도된) 원인 | 출처+태그 |
|---|---|---|---|---|
| S&P500 | 7,723.55 | -0.17%(-12.97pt) | 전일 사상 최고 종가(7,736.52) 이후 나흘 연속 상승세 소진, 기술주 차익실현 | CNBC/Coinpaper · "Stock Market Today: DJI Holds Strong Gain as S&P 500 Fades From Record High" 2026-08-05 [P2] |
| NASDAQ 종합 | 26,363.44 | -0.83% | 4거래일 연속 랠리 종료, AMD 실적 실망(시간외/프리마켓 -8.5%)이 기술주 전반에 부담 | Yahoo Finance/CNBC · "S&P 500 is flat as 4-day rally loses momentum" 2026-08-05 [P2] |
| Dow | 54,349.12 | +263.24pt / +0.49%(사상 최고 종가, 5거래일 연속 상승) | 엔비디아 3%대 상승(스페이스X 전용 공급 발언)이 지수 견인 | CNBC/FXLeaders · "Dow Jones Crosses 54,500 as Nvidia $220 Breakout Fires Up AI Rally" 2026-08-05 [P2] |
| Russell2000 | 2,961.51 | +22.31pt / +0.76% | 개별 보도 원인 특정 없음(소형주 전반 강세로 보도) | ibtimes.com.au · "Russell 2000 Climbs 0.76%..." 2026-08-05 [P3] |
| SOX(필라델피아 반도체지수) | N/A(지수 자체 종가 미확인) | N/A | 검증 가능한 종가 수치 검색 실패 | [N/A] |
| ES(S&P500 선물) | N/A | N/A | 한국 아침 시점 프리마켓 수치, 검색 결과 상충(타 연도 기사 혼입 의심)으로 신뢰도 부족 | [N/A] |
| NQ(나스닥100 선물) | N/A | N/A | 상동 | [N/A] |
| VIX | 약 16.28~16.50(자료별 상이) | 소폭 등락(보합권) | 개별 보도 없음 | Yahoo Finance/historicaloptiondata.com [P3] — ※ 자료 간 수치 상이하여 범위로 병기 |
| DXY(달러인덱스) | 99.85 | 소폭 하락 | 개별 보도 없음 | TradingEconomics 집계 [P3] |
| WTI | $75.69/bbl | -0.10% | 개별 보도 없음(전일 급락 이후 보합) | TradingEconomics [P3] |
| Brent | $79.26/bbl | -0.13% | 상동 | TradingEconomics [P3] |
| Gold | $4,130~4,304 구간(자료별 상이) | 상승(구체 등락률 미확정) | 유가 하락·달러 약세·미 국채금리 하방 압력이 금 매수세 뒷받침(ADP 고용 둔화 보도와 병기) | Investing.com/Convextrade [P3] — ※ 자료 간 수치 격차 커 범위로만 병기, 단일 수치 확정 불가 |

---

## [2] 금리 / 연준

| 항목 | 사실 내용(발언·수치) | 출처+태그 |
|---|---|---|
| 미 10년물 국채금리 | 약 4.62%(2026-08-05 기준, 보합) | TradingEconomics/검색 집계(FRED DGS10 계열) [P1] |
| 미 2년물 국채금리 | 약 4.21%(2026-08-04 기준 확인, 08-05 개별 수치 미확인) | StreetStats/검색 집계 [P1] |
| 10Y-2Y 스프레드 | 약 +0.41%p(산술, 상기 두 수치 기반) | 산출값 |
| 최근 FOMC(7월 29일 회의) | 정책금리 3.50~3.75% 동결, 9-3 표결로 이견 존재 | Fed 회의 결과 보도 [P1][P2] |
| 워시 Fed 의장 발언(7월 하원 금융서비스위원회 증언) | "지속적으로 높은 인플레이션을 용인하지 않겠다"(no tolerance for persistently elevated inflation) | CBS News · "Warsh vows to tackle inflation in first congressional testimony" [P3] |
| 워시 Fed 의장 발언(7월 29일 기자회견) | 금리 미조정 결정에도 필요시 조치하겠다고 언급(구체 인용문 재검증 필요) | CNBC · "Fed meeting recap: Warsh says Fed won't hesitate to stop inflation, but bond market has doubts" 2026-07-29 [P2] |
| 차기 FOMC 일정 | 2026-09-16 | 검색 집계 [P3] |
| CME FedWatch (2026-08-04 기준) | 9월 회의에서 0.25%p 인상 확률 61.9%로 표시 | centralbank.watch 등 집계 [P3] |
| CME FedWatch (별도 보도, 시점 불명확) | 9월 16일 회의까지 누적 인상 확률 82.4%로 보도 | Yahoo Finance · "There's Now an 82% Chance of a Fed Rate Hike by mid-September" [P3] — ※ 위 61.9%와 측정 시점·방법론 상이, 해석 없이 병기 |
| ADP 민간고용보고서(7월, 2026-08-05 발표) | 민간부문 고용 +44,000명(예상 +75,000명 하회, 전월 6월 +95,000명 대비 둔화, 1월 이후 최소 증가폭). 서비스업 +47,000명, 재화생산업 -3,000명 | ADP/CNBC · "Private companies added just 44,000 workers in July, below expectations, ADP reports" 2026-08-05 [P1][P2] |

---

## [3] 주요 경제지표

| 지표 | 발표시각(ET·KST) | 발표치 | 예상치 | 이전치 | 서프라이즈(산술) | 출처 |
|---|---|---|---|---|---|---|
| ISM 서비스업 PMI(7월, 2026-08-05 발표) | 2026-08-05 10:00 ET / 23:00 KST | 54.1% | 54.5% | 54.0%(6월) | -0.4%p | ISM/PRNewswire · "Services PMI at 54.1%" [P1] |
| 신규 실업수당 청구건수(주간, 금주분) | 2026-08-06 8:30 ET / 21:30 KST(금일, 미발표) | N/A(미발표) | 203,000건 | 197,000건 | N/A | Econoday/투자닷컴 집계 [P3] |

※ 7월 고용보고서(비농업고용)는 2026-08-07(금) 발표 예정 — [8] 참조.
※ CPI(7/13), PPI(8/13), 소매판매(8/15)는 금일 발표 대상 아님 — [8] 참조.

---

## [4] 특징 종목 (±5% 이상 / 거래량 급증, [5]/[5-A]/[6] 대상 제외)

| 종목 | 티커 | 등락률 | 거래량 | (보도된) 핵심 사실 | 출처+태그 |
|---|---|---|---|---|---|
| 디지털 터빈 | APPS | +28.2% | N/A | 분기 매출·이익 큰 폭 상회, 연간 가이던스 상향 | 검색 집계(2026-08-05 실적 반응) [P3] |
| 일라이 릴리 | LLY | +6.5% 이상 | N/A | 2분기 실적·매출 컨센서스 상회, 2026 연간 매출 가이던스 상향(Zepbound·Mounjaro 수요 강세) | 검색 집계 · 2026-08-05 [P2] |
| 윈 리조트 | WYNN | +5% | N/A | 2분기 조정 EPS $1.24(컨센서스 $1.11 상회), 매출 $18.6억(컨센서스 $18.4억 상회) | 검색 집계 · 2026-08-05 [P3] |
| 핀터레스트 | PINS | -9% | N/A | 3분기 매출 가이던스가 시장 예상보다 둔화된 성장률 시사(2분기 실적 자체는 예상 상회) | 검색 집계 · 2026-08-05 [P3] |
| 매치그룹 | MTCH | -10.2% | N/A | 매출 예상 하회, 유료 이용자 추가 감소 전망 제시 | 검색 집계 · 2026-08-05 [P3] |

---

## [5] AI 인프라 — 공급 측

| 기업 | 뉴스 제목 | 사실 내용(무슨 일이) | 출처일자 | 출처+태그 |
|---|---|---|---|---|
| 엔비디아(NVDA) | 스페이스X, 향후 AI 인프라 엔비디아 전용 사용 발표 | 스페이스X CEO 일론 머스크가 첫 실적 콘퍼런스콜에서 향후 스페이스X의 AI 시스템을 엔비디아 기반으로만 구축하겠다고 발언. 스페이스X는 연말까지 2GW 이상, 내년 말까지 약 10GW 컴퓨팅 용량 확보 목표 언급. 궤도상 AI 데이터센터 "Starmind" 위성 프로젝트에 우주용 Vera Rubin 모듈(Rubin GPU·Vera CPU) 탑재 계획 공개 | 2026-08-05 | Yahoo Finance/Tom's Hardware · 머스크 발언 인용 [P2] |
| 엔비디아(NVDA) | 주가 반응 | 위 소식에 주가 3%대 상승, $220 돌파 | 2026-08-05 | FXLeaders [P2] |
| AMD | 실적 발표 후 프리마켓 반응(후속) | 전일(8/4) 실적 발표 후 시간외 하락에 이어, 8/5 프리마켓에서 추가로 8.5% 하락(2분기 실적이 투자자 기대에 미치지 못했다는 평가) | 2026-08-05 | CNBC · "Stocks making the biggest moves premarket" [P2] |
| 브로드컴(AVGO) | AI 반도체 매출 가이던스(기존 발표 재인용) | 당사 가이던스상 AI 반도체 매출이 이번 분기 전년비 200% 이상 성장한 $160억에 달할 것으로 제시(발표 시점 재검증 필요) | 발표일 N/A(최근 실적발표 기준으로 추정) | 검색 집계 [P3] — ※ 발표일자 재확인 필요 |
| TSMC(TSM) | AI 반도체 수요 지속 시사(기존 보도 재확인) | AI 인프라 구축 확대가 향후 수년간 지속될 것이라는 취지의 기존 발언이 재차 보도됨(신규 발표 아님) | 2026-07-23 원보도 | Motley Fool [P2] — 신규성 낮음, 참고용 |
| 마이크론(MU) | 분기 매출 가이던스(기존 발표 재인용) | 분기 매출 $500억 가이던스 관련 보도(발표 시점 재검증 필요) | 발표일 N/A | 검색 집계 [P3] — ※ 발표일자 재확인 필요 |
| Applied Digital(APLD) | FY2026 4분기 실적(기존) | 4분기 매출 $2.587억(전년비 +407%), FY2026 연간 매출 $6.113억(전년비 +167%), 하이퍼스케일러向 서명된 리스 계약 $160억 규모 | 2026-07-27 | Yahoo Finance [P2] |
| 셀레스티카(CLS) | 신규 뉴스 | 금일 기준 신규 확인된 뉴스 없음 | — | N/A |
| Super Micro Computer(SMCI) | 신규 뉴스 | 금일 기준 신규 확인된 뉴스 없음(8/11 실적 발표 예정 — [8] 참조) | — | N/A |
| 크레도 테크놀로지(CRDO) | 신규 뉴스 | 금일 기준 신규 확인된 뉴스 없음 | — | N/A |
| 아리스타 네트웍스(ANET) | 신규 뉴스 | 금일 기준 신규 확인된 뉴스 없음(전일 실적 발표 내용은 전회차 기재 완료) | — | N/A |
| 버티브(VRT) | 신규 뉴스 | 금일 기준 신규 확인된 뉴스 없음 | — | N/A |

---

## [5-A] AI 인프라 — 수요 측 / 하이퍼스케일러 CAPEX 〔실적시즌〕

신규 변동 없음 — 직전 가이던스 유지: 알파벳 2026 CAPEX $1,950억~2,050억(2026-07-22 발표), 메타 $1,300억~1,450억(2026-07-29), 아마존 약 $2,000억(2026-07-30), 마이크로소프트 Azure 4분기 CAPEX $410억(2026-07-29). 금일 기준 4사 신규 CAPEX 관련 공시·발언 확인되지 않음.

---

## [6] 시총 상위 10 — AI 무관 일반 이슈 〔실적시즌/이슈시〕

| 기업 | 사실 내용 | 출처일자 | 출처+태그 |
|---|---|---|---|
| 아마존(AMZN) | 창업자 제프 베이조스가 약 1,500만주(약 $40.7억 상당, 2026-08-03 종가 $284.02 기준) 매도 계획을 SEC에 공시. 공시상 해당 매도는 2025-11-14 채택된 Rule 10b5-1 사전예정계획에 따른 것이며, Morgan Stanley Smith Barney LLC를 통해 집행. 공시 이후 아마존 주가 장 초반 2% 이상 하락 | 2026-08-04(공시일) | CNBC · "Jeff Bezos just filed to sell $4 billion in Amazon" [P2]; SEC 공시 [P1] |
| 애플(AAPL) | 애플 vs 오픈AI 영업비밀 소송(2026-07-10 제소) 관련, 애플이 오픈AI 및 전직 애플 직원 2명(창리우, 탕탄)을 상대로 예비적 금지명령(preliminary injunction) 신청서 제출. 오픈AI는 같은 날 공개 반박문(내부 메시지·법률서한 포함)으로 "애플의 금지명령 신청은 잘못된 정보에 근거했으며 불필요하다"고 대응 | 2026-08-03~04 | JURIST/9to5Mac/MacRumors · 법원 제출서류 기반 보도 [P2] |
| 마이크로소프트(MSFT) / 구글(GOOGL) / 메타(META) / 테슬라(TSLA) / 버크셔해서웨이(BRK) / TSM | 금일 기준 신규 확인된 AI 무관 이슈 없음 | — | N/A |

---

## [7] 기관·대형 자금 수급

| 항목 | 종목 | 사실 내용 | 규모(수치) | 출처+태그 |
|---|---|---|---|---|
| 반도체 ETF 주간 자금유입 | SMH·SOXX·SOXL | 2026년 8월 초 기준, 해당 3개 ETF가 전체 ETF 중 주간 자금유입 1위 기록(반도체 섹터 최초 사례로 보도) | N/A(비율/절대액 세부 미확인) | Stocktwits · "Semiconductor ETFs SMH, SOXX, SOXL Top Weekly Fund Flows For First Time" [P3] |
| SOXX 단일일 자금유입(기존 사례, 참고) | SOXX | 2026-07-08 단일 거래일 $54.3억 순유입, AUM 약 $463억으로 하루새 11.73% 증가 | $54.3억(1일, 7/8 기준) | ETF.com · "Semiconductor ETFs Roar Back" [P3] — ※ 최신 데이터 아님, 참고용으로 병기 |
| SMH 자금유입(기존 사례, 참고) | SMH | 2026-07-08 동일 세션 $5.52억 순유입, AUM 약 $698억 | $5.52억(1일, 7/8 기준) | ETF.com 상동 [P3] |

---

## [7-A] Insider Trading (SEC Form 4) 〔조건부〕

N/A — 금일(2026-08-06) 기준 대상 기업(NVDA·AVGO·CRDO·CLS·APLD·VRT·SMCI)의 CEO·CFO·COO·Director 관련 신규 Form 4 공시 확인되지 않음.
참고(신규 아님, 타 기업): 아마존 창업자(이사회 의장) 제프 베이조스의 약 $40.7억 규모 매도 계획 공시(2026-08-04) — 거래유형은 Rule 10b5-1 사전예정계획으로 공시서류에 명시됨. 다만 아마존은 [7-A] 우선 대상 AI 인프라 기업 목록에 포함되지 않아 [6]에 기재.

---

## [8] 향후 14일 주요 일정 (2026-08-06 ~ 2026-08-20)

### 경제 일정
| 날짜 | 시각(ET·KST) | 이벤트 | 컨센서스 | 이전치 | 출처 |
|---|---|---|---|---|---|
| 2026-08-06(목) | 8:30 ET / 21:30 KST | 신규 실업수당 청구건수(주간) | 203,000건 | 197,000건 | Econoday 집계 [P3] |
| 2026-08-07(금) | 8:30 ET / 21:30 KST | 7월 고용보고서(비농업고용·실업률) | N/A(신뢰 가능한 컨센서스 미확인) | N/A | 검색 집계 [P3] |
| 2026-08-12(수) | 8:30 ET / 21:30 KST | CPI(7월) | N/A | N/A | 검색 집계 [P3] |
| 2026-08-13(목) | 8:30 ET / 21:30 KST | PPI(7월) | N/A | N/A | 검색 집계 [P3] |
| 2026-08-15(토 표기, 요일 재확인 필요) | 8:30 ET / 21:30 KST | 소매판매(7월) | N/A | N/A | 검색 집계 [P3] — ※ 2026-08-15 요일이 보도상 "금요일"로 표기되었으나 자체 계산과 불일치 가능성 있어 재검증 필요 |

### 기업 일정
| 날짜 | 기업 | 이벤트 | 컨센서스 EPS | 컨센서스 매출 | 출처 |
|---|---|---|---|---|---|
| 2026-08-06(목) | McDonald's(MCD) | 실적 발표 | N/A | N/A | 검색 집계(EarningSpike/Kiplinger) [P3] |
| 2026-08-06(목) | Airbnb(ABNB) | 실적 발표 | N/A | N/A | 검색 집계 상동 [P3] |
| 2026-08-11(화) | Super Micro Computer(SMCI) | 장마감 후 실적 발표 | N/A | N/A | WallStreetHorizon/TipRanks(전회차 확인) [P3] |

※ 엔비디아(NVDA) 2분기(FY2027) 실적발표는 2026-08-26 예정으로 14일 창(~8/20) 밖이므로 이번 회차 미기재.

---

## [9] 오늘의 사실 목록 (순위 없음, 섹션순 나열)

- [1] S&P500 7,723.55 마감, 전일比 -0.17%, 4일 연속 상승세 종료 · CNBC [P2]
- [1] Dow 54,349.12 마감, +263.24pt(+0.49%), 사상 최고 종가·5거래일 연속 상승 · CNBC [P2]
- [1] NASDAQ 종합 26,363.44 마감, -0.83%, 4일 연속 랠리 종료 · Yahoo Finance [P2]
- [1] Russell2000 2,961.51 마감, +0.76% · ibtimes.com.au [P3]
- [1] WTI 75.69달러(-0.10%), Brent 79.26달러(-0.13%) · TradingEconomics [P3]
- [1] DXY 99.85, 소폭 하락 · TradingEconomics [P3]
- [2] 미 10년물 국채금리 약 4.62%(보합), 2년물 약 4.21%(8/4 기준) · 검색 집계 [P1]
- [2] CME FedWatch, 9월 FOMC 금리 인상 확률 61.9%(8/4 기준) 및 별도 보도 82.4% 병존 · centralbank.watch/Yahoo Finance [P3]
- [2] ADP 7월 민간고용 +44,000명, 예상(+75,000명) 대비 큰 폭 하회, 6월(+95,000명) 대비 둔화 · ADP/CNBC [P1][P2]
- [3] ISM 서비스업 PMI(7월) 54.1%, 예상 54.5% 하회, 전월 54.0% 소폭 상회 · ISM [P1]
- [3] 신규 실업수당 청구건수 금일(8/6) 21:30 KST 발표 예정, 예상 203,000건(미발표) · Econoday [P3]
- [4] 디지털 터빈(APPS) +28.2%, 일라이 릴리(LLY) +6.5%대, 핀터레스트(PINS) -9%, 매치그룹(MTCH) -10.2% · 검색 집계 [P2][P3]
- [5] 엔비디아, 스페이스X 전용 공급 발표로 주가 3%대 상승·$220 돌파, 스페이스X는 연말 2GW·내년말 10GW 컴퓨팅 목표 · Yahoo Finance/FXLeaders [P2]
- [5] AMD, 8/4 실적 발표 후 시간외 하락에 이어 8/5 프리마켓 추가 8.5% 하락 · CNBC [P2]
- [5-A] 하이퍼스케일러 4사, 금일 기준 CAPEX 관련 신규 공시 없음 — 직전 가이던스(알파벳 $1,950억~2,050억 등) 유지
- [6] 아마존 창업자 베이조스, 10b5-1 계획에 따라 약 $40.7억 규모 지분 매도 공시, 주가 2%대 하락 · CNBC [P2]
- [6] 애플, 오픈AI 상대 영업비밀 소송에서 예비적 금지명령 신청, 오픈AI는 공개 반박 · JURIST/9to5Mac [P2]
- [7] SMH·SOXX·SOXL, 8월 초 기준 전체 ETF 중 주간 자금유입 1위(반도체 섹터 최초) · Stocktwits [P3]
- [7-A] 대상 기업(NVDA 등) 신규 Form 4 공시 없음 · N/A
- [8] 신규 실업수당 청구 8/6, 7월 고용보고서 8/7, CPI(7월) 8/12, PPI(7월) 8/13, 소매판매(7월) 8/15 발표 예정 · 각 출처 [P3]
- [8] McDonald's·Airbnb 8/6 실적 발표, Super Micro Computer 8/11 실적 발표 예정 · 검색 집계 [P3]
