# 미국 시장 데일리 수집 결과 (Collect)
# 기준일: 2026-10-01 (목) 미국 정규장 종가 기준 · 작성일 2026-10-02 (금) · 실행모드: 데일리
# 생성시각(KST): 2026-10-02 07:40

> 날짜 확인: 2026-10-01은 목요일, 2026-10-02는 금요일로 검색 확인됨.
> 2026-10-02(금) 미 9월 고용보고서(비농업고용지표)는 예정대로 발표 대상이었음 — 2026-10-01 기준 미국 정부 셧다운은 발생하지 않음 (2026-09-02 서명된 임시예산안으로 2026-12-11까지 재정 집행, 상원 90-6·하원 370-48 통과). 단, 실제 발표치(수치)는 검색으로 확인되지 않아 [3]에 "확인 필요"로 표기함.
> 참고: 2026-05-22 제롬 파월 연준 의장 임기 종료, 후임 케빈 워시(Kevin Warsh) 의장 취임 확인됨(CNBC·Fed·Brookings 등 복수 소스로 교차 확인). 2026-09-16 FOMC에서 정책금리 25bp 인상(3.75~4.00%) 확인됨.

---

## [1] 미국 주요 지수 (데일리)

| 항목 | 종가/수치 | 등락률 | (보도된) 원인 | 출처+태그 |
|------|-----------|--------|---------------|-----------|
| S&P500 | 7,666.45 | +0.19% | 국채금리가 다년 고점에서 반락하며 상승 전환 | CNBC · "S&P 500 closes higher to start October as Treasury yields retreat from multiyear highs" · 2026-09-30/10-01 · https://www.cnbc.com/2026/09/30/stock-market-today-live-updates.html [P2] |
| 나스닥종합지수 | 26,871.60 | +0.04% | 국채금리 하락 속 반도체주 강세 | Yahoo Finance · "Dow, S&P 500, Nasdaq stage comeback as Treasury yields fall, chip stocks gain" · 2026-10-01 · https://finance.yahoo.com/markets/live/stock-market-today-thursday-oct-1-dow-sp-500-nasdaq-080602402.html [P2] |
| 다우존스산업평균 | 50,926.56 | +0.04% (+20.51pt) | 국채금리 반락에 따른 강보합 마감 | Yahoo Finance · 상동 · 2026-10-01 [P2] |
| 러셀2000 | N/A — 상충되는 수치(한 출처는 +0.8%대 오후 상승, 다른 출처는 2,960.20·-0.52% 보도) | N/A | N/A | 확인 필요 [N/A] |
| 필라델피아반도체지수(SOX) | N/A — 2026-10-01 종가 미확인(2026-09-30 종가 12,616.00만 확인됨) | N/A | N/A | 확인 필요 [N/A] |
| 브렌트유 | N/A — WTI는 0_data.md(섹션 1-A) 참조. 브렌트 자체는 보도에서 "+4.4%" 언급 있으나 정확 종가(달러) 복수 출처 교차검증 실패 | +4.4%(보도 기준, 종가 수치 미교차검증) | 미 항공모함 타격단 3척째 중동 파견 보도에 유가 급등 | CNBC · "Oil prices today: WTI, Brent" · 2026-10-01 · https://www.cnbc.com/2026/10/01/oil-prices-today-wti-brent.html [P2] (종가 숫자는 확인 필요) |

비고: 8/1 지수 마감 수치는 CNBC·Yahoo Finance 보도 기준이며, 일부 2차 소스(TheStreet 등)에서 소폭 다른 수치가 발견되어 완전히 일치하지 않음. S&P500·나스닥·다우 수치는 2개 이상 매체에서 일치해 채택. 러셀2000·SOX·브렌트 정확 종가는 출처 간 불일치로 N/A 처리.

---

## [1-A] 선물·변동성 구조 (0_data.md 원문 인용 — 재검색 없음)

### 선물 (한국 아침 시점)

| 항목 | 심볼 | 현재가/종가 | 전일 대비 | 직전 종가 | 기준시각(ET) |
|------|------|-------------|-----------|-----------|--------------|
| S&P500 선물 (ES) | `ES=F` | 7,725 | +0.12% | 7,715.5 | 2026-10-01 16:59 |
| 나스닥100 선물 (NQ) | `NQ=F` | 30,771.25 | +0.24% | 30,698.75 | 2026-10-01 16:59 |
| 다우 선물 (YM) | `YM=F` | 51,234 | -0.09% | 51,278 | 2026-10-01 16:59 |
| 러셀2000 선물 (RTY) | `RTY=F` | 2,829.8 | +0.44% | 2,817.5 | 2026-10-01 16:59 |

### 변동성 구조

| 항목 | 심볼 | 현재가/종가 | 전일 대비 | 직전 종가 | 기준시각(ET) |
|------|------|-------------|-----------|-----------|--------------|
| VIX (30일) | `^VIX` | 16.39 | +0.31% | 16.34 | 2026-10-01 16:15 |
| VIX9D (9일) | `^VIX9D` | 14 | -1.41% | 14.2 | 2026-10-01 16:15 |
| VIX3M (3개월) | `^VIX3M` | 18.58 | +1.14% | 18.37 | 2026-10-01 16:15 |
| VVIX (VIX의 변동성) | `^VVIX` | 92.01 | +2.83% | 89.48 | 2026-10-01 16:15 |
| SKEW (테일리스크) | `^SKEW` | 142.77 | +0.60% | 141.92 | 2026-10-01 17:00 |

### 매크로

| 항목 | 심볼 | 현재가/종가 | 전일 대비 | 직전 종가 | 기준시각(ET) |
|------|------|-------------|-----------|-----------|--------------|
| 미 10년 국채선물 | `ZN=F` | 104.61 | +0.39% | 104.2 | 2026-10-01 16:59 |
| 금 | `GC=F` | 4,207.8 | +0.50% | 4,186.7 | 2026-10-01 16:59 |
| WTI | `CL=F` | 92.91 | +2.75% | 90.42 | 2026-10-01 16:59 |
| 달러지수 (DXY) | `DX-Y.NYB` | 102.01 | +0.55% | 101.45 | 2026-10-01 17:20 |

### VIX 기간구조 (비율)

| 비율 | 값 | 구조 |
|------|----|------|
| VIX3M / VIX | 1.134 | 콘탱고 |
| VIX / VIX9D | 1.171 | 콘탱고 |

### Put/Call 비율 (CBOE 옵션 체인 직접 집계)

| 대상 | P/C (거래량) | P/C (미결제약정) | 콜 거래량 | 풋 거래량 | 집계 계약수 |
|------|--------------|------------------|-----------|-----------|-------------|
| S&P500 지수옵션 (SPX) | 1.122 | 1.420 | 2,589,741 | 2,905,883 | 29,394 |
| 나스닥100 ETF 옵션 (QQQ) | 1.001 | 1.399 | 5,055,200 | 5,061,425 | 11,268 |

출처: 0_data.md (Yahoo Finance chart API · CBOE 지연시세 API, 기계 수집) [P1]

---

## [2] 금리/연준 (데일리)

| 항목 | 사실 내용(발언·수치) | 출처+태그 |
|------|------------------------|-----------|
| 연준 의장 | 케빈 워시(Kevin Warsh), 2026-05-22 제롬 파월 후임으로 취임. 파월은 이사(governor)로 2028-01-31까지 잔류 | Brookings · "Who has to leave the Federal Reserve next?" · https://www.brookings.edu/articles/who-has-to-leave-the-federal-reserve-next-2/ [P3]; CNBC 교차확인 [P2] |
| FOMC 정책금리 결정 (2026-09-16) | 연방기금금리 목표범위 25bp 인상, 3.75~4.00%로 상향. 12-0 만장일치 | CNBC · "Fed rate decision September 2026: Rates rise to 3.75%-4%" · 2026-09-16 · https://www.cnbc.com/2026/09/16/fed-rate-decision-september-2026.html [P2] |
| FOMC 성명 발언 (워시 의장, 2026-09-16 기자회견) | "Today, the FOMC decided that this standard [inflation moving to objective clearly and at sufficient speed] has not been satisfied." (인플레이션의 목표 수렴 기준이 충족되지 않았다는 취지의 발언) | Schwab · "Fed Hikes in 12-0 Vote, Commits to Inflation Fight" · 2026-09-16 · https://www.schwab.com/learn/story/fomc-meeting [P3] |
| 점도표 (2026-09-16 SEP) | 참가자 중위값, 2026년 말까지 추가 25bp 인상해 4.1% 전망. 2027년 동결, 2028~2029년 인하 전망 | Advisor Perspectives / JPMorgan AM FOMC Statement 요약 · 2026-09-16 · https://am.jpmorgan.com/us/en/asset-management/adv/insights/portfolio-insights/fixed-income/fixed-income-perspectives/fomc-statement-september-2026/ [P2] |
| 10년 국채 수익률 (2026-10-01) | 5.24%, 전일 대비 -0.05%p | 검색 집계(TradingEconomics/YCharts류 데이터 기반 보도) · 2026-10-01 [P3] — 동일 시점 타 소스(5.33%대)와 불일치 있어 참고용 |
| 2년 국채 수익률 (2026-10-01) | 4.80%, 전일 대비 -0.112%p | 검색 집계 · 2026-10-01 [P3] |
| 10Y-2Y 스프레드 | N/A — 상기 양 수익률 출처가 서로 다른 집계여서 신뢰도 있는 스프레드 계산 불가 | 확인 필요 [N/A] |
| 10년물 수익률 전고점 맥락 | 2026-09 중 "24년 만의 고점"(최고 약 5.34%) 도달 후 반락했다는 보도 다수 | CNBC · "10-year Treasury yield is at its highest in 19-24 years" 계열 보도 · 2026-09-26 [P2] |
| 다음 FOMC 회의 | 2026-10-27~28, 금리 결정 발표 2026-10-28 14:00 ET (비-SEP 회의) | fedratecalc.com / financecalendar.com 집계 · [P3] |
| CME FedWatch (2026-10-28 회의 전망) | 상충 보도 존재(62.1% 동결 ~ 72.5% 금리 변경 확률 등 출처마다 수치 상이). 모든 출처 공통점: 금리 "인하" 가능성은 사실상 0%로 보도됨 | 복수 소스 상충 — 단일 확정 수치는 확인 필요 [N/A] |

---

## [3] 주요 경제지표 (조건부)

| 지표 | 발표시각(ET·KST) | 발표치 | 예상치 | 이전치 | 서프라이즈(산술값) | 출처 |
|------|--------------------|--------|--------|--------|----------------------|------|
| 9월 비농업고용지표(미 고용보고서) | 2026-10-02 08:30 ET · 2026-10-02 21:30 KST (예정) | 확인 필요 — 실제 발표치 검색 미확인 | +90,000명 (FactSet 컨센서스, 27개 기관 예상범위 +60,000~+130,000) | +162,000명 (2026년 8월) | 확인 필요 | FactSet Insight · "Total Nonfarm Payrolls for September 2026 Are Projected to Rise By 90,000" · https://insight.factset.com/total-nonfarm-payrolls-for-september-2026-are-projected-to-rise-by-90000 [P3]; BLS 일정 · https://www.bls.gov/schedule/news_release/empsit.htm [P1] |
| ISM 제조업 PMI (9월) | 2026-10-01 10:00 ET | 54.5% | N/A — 컨센서스 수치 미확인 | 54.6% (8월) | -0.1%p (전월 대비) | PR Newswire · "Manufacturing PMI® at 54.5%; September 2026 ISM® Manufacturing PMI® Report" · 2026-10-01 · https://www.prnewswire.com/news-releases/manufacturing-pmi-at-54-5-september-2026-ism-manufacturing-pmi-report-302894520.html [P1] |
| ADP 민간고용보고서 (9월) | 2026-09-30 | +90,000명 | +68,000명 (다우존스 컨센서스) | +36,000명 (8월, 하향수정) | +22,000명 (서프라이즈) | CNBC · "Private sector jobs rose by 90,000 in September, better than expected, ADP reports" · 2026-09-30 · https://www.cnbc.com/2026/09/30/private-sector-jobs-rose-by-90000-in-september-better-than-expected-adp-reports.html [P2] |
| 8월 PCE 물가지수 | 2026-09-30 발표(배경 수치) | 헤드라인 +3.4% YoY · 코어 +3.0% YoY | N/A | N/A | N/A | 검색 집계 보도 · 2026-09-30 [P3] — 원 발표처(BEA) 직접 확인 필요 |
| CPI (9월) | N/A — 발표일 미확정 | N/A | N/A | N/A | N/A | 확인 필요 — 경제캘린더 집계 사이트에서 10/14 언급 있으나 BLS 공식 확인 안 됨 [N/A] |
| PPI/GDP | N/A | N/A | N/A | N/A | N/A | 확인 필요 — 해당 기간 발표 확인 안 됨 [N/A] |

---

## [4] 특징 종목 (데일리)

| 종목 | 티커 | 등락률 | 거래량 | (보도된) 핵심 사실 | 출처+태그 |
|------|------|--------|--------|---------------------|-----------|
| 액센츄어 | ACN | +16~21% (출처별 상이) | N/A | FY Q4 실적 호조, 사상 최대 수주, FY2027 가이던스 상향 발표 | 검색 집계 보도 · 2026-10-01 [P3] — 정확 등락률 단일 수치 확인 필요 |
| 시놉시스 | SNPS | +5~13% (출처별 상이) | N/A | 2026-09-30 인베스터데이에서 FY2027 매출 가이던스 상향, OpenAI 파트너십, AWS 10억달러 이상 계약, 자사주매입 10억달러 발표 | 검색 집계 보도 · 2026-09-30/10-01 [P3] |
| 코그니전트 | CTSH | +7.2% (일부 출처 +11.19%) | N/A | 액센츄어 실적에 따른 동종업계 동반 상승(시벤패시) | 검색 집계 보도 · 2026-10-01 [P3] |
| 바이코 | VICR | 약 +10~12% | N/A | AI 전력공급 라이선스 로열티 기반 Q3 매출 성장 가이던스 상향 | 검색 집계 보도 · 2026-10-01 [P3] |
| 코르테바 | CTVA | 약 -84% (거래 데이터상) | N/A | 실질적 주가 하락이 아니라 Vylor(VYLR) 스핀오프 완료에 따른 기계적 기준가 조정 | 검색 집계 보도 · 2026-10-01 [P3] |

비고: 등락률 정확 수치가 출처마다 다르게 보도되어 범위로 표기. 거래량 수치는 검색으로 확인되지 않아 전부 N/A.

---

## [4-A] 섹터별 뉴스 (0_data.md 기반, 필요시 보충 검색)

| 섹터 | 종목 | 사실 내용(무슨 일이) | 발행시각(ET) | 출처+태그 |
|------|------|------------------------|--------------|-----------|
| 반도체·AI | AVGO | Anthropic에 최대 420억달러 전환사채 형태로 대출 제공 보도 — Anthropic의 5년간 1,252억달러 규모 TPU/컴퓨팅 공급계약 중 약 1/3 해당 | 2026-10-01 | CNBC(로이터 인용) · "Broadcom lending Anthropic $42 billion chips" · https://www.cnbc.com/2026/10/01/broadcom-lending-anthropic-42-billion-chips-reuters.html [P2] |
| 반도체·AI | AVGO | Marvell 대비 AI 수요 둔화 우려, Applied Materials와의 비교 기사 | 2026-10-01 15:32 / 14:29 | Yahoo · 0_data.md 원문 인용 [P3] |
| 반도체·AI | AVGO | AMD 주가 상승 이유 분석 기사 | 2026-10-01 14:13 | Yahoo · 0_data.md 원문 인용 [P3] |
| 금융 | JPM | JPMorgan M&A 총괄 헤르난 크리스테르나(Hernan Cristerna), 30년 근무 후 은퇴 | 2026-10-01 14:05 | Yahoo · 0_data.md 원문 인용 [P3] |
| 금융 | JPM | JPMorgan 채권시장 조달 관련, 저평가 여부 분석 기사 | 2026-10-01 14:09 | Yahoo · 0_data.md 원문 인용 [P3] |
| 에너지 | XOM | Marathon Petroleum +5%, Valero +4% 등 정유주 강세, Exxon Mobil은 보합 — 정유사가 통합 메이저 대비 초과수익 | 2026-10-01 13:53 | Yahoo · 0_data.md 원문 인용 [P3] |
| 에너지 | XOM | Wells Fargo, BP에 긍정적·Exxon Mobil 밸류에이션 격차 이유로 하향 | 2026-10-01 11:35 | Yahoo · 0_data.md 원문 인용 [P3] |
| 헬스케어 | UNH | UnitedHealthcare 2027년 메디케어 플랜 발표 — 0달러 보험료, 처방약 공동부담 등 | 2026-10-01 05:24 / 07:00 | Benzinga/Yahoo · 0_data.md 원문 인용 [P3] |
| 소비재·유통 | AMZN | Amazon-Constellation, 메릴랜드 원자력발전소 확장 위한 20년 전력구매계약(PPA) 체결 | 2026-10-01 14:55 | Yahoo · 0_data.md 원문 인용 [P3] |
| 소비재·유통 | AMZN | 전국 소매체인, 2026년 80개 매장 폐쇄 후 챕터11 파산신청 | 2026-10-01 14:34 | Yahoo · 0_data.md 원문 인용 [P3] |

---

## [5] AI 인프라 — 공급 측 (데일리)

| 기업 | 뉴스 제목 | 사실 내용(무슨 일이) | 출처일자 | 출처+태그 |
|------|-----------|------------------------|----------|-----------|
| NVDA | Nvidia 1,500억달러 자사주매입 승인 확대 | 이사회가 기존 프로그램에 1,500억달러를 추가 승인, 잔여 승인 총액 235억→실제 2,350억달러 규모로 2028 회계연도까지 집행 예정. 미국 기업 사상 최대 규모 자사주매입 승인 확대로 보도됨. 젠슨 황 CEO 코멘트 포함 | 2026-09-28 | NVIDIA 뉴스룸 · https://nvidianews.nvidia.com/news/nvidia-announces-a-150-billion-share-repurchase-authorization-increase [P1]; CNBC · 2026-09-28 · https://www.cnbc.com/2026/09/28/nvidia-share-buyback-plan-gets-150-billion-boost.html [P2] |
| AVGO | Broadcom, Anthropic에 최대 420억달러 대출 | 전환사채 방식으로 Anthropic의 TPU/컴퓨팅 공급계약(5년 1,252억달러) 자금조달 일부 지원 | 2026-10-01 | CNBC(로이터 인용) · https://www.cnbc.com/2026/10/01/broadcom-lending-anthropic-42-billion-chips-reuters.html [P2] |
| AMD | AMD, World Labs 82억달러 전액 주식 인수 | Fei-Fei Li 창업 AI 스타트업 World Labs를 82억달러 전액 주식 거래로 인수 발표. 합병계약 체결일 2026-09-26 | 2026-09-28 | Bloomberg · https://www.bloomberg.com/news/articles/2026-09-28/amd-to-buy-fei-fei-li-s-world-labs-ai-startup-for-8-2-billion [P2]; CNBC 교차확인 [P2] |
| TSM | TSMC, 텍사스 신규 캠퍼스 검토 | 애리조나 기존 투자에 추가해 텍사스에 신규 대규모 캠퍼스 건설을 초기 단계에서 검토 중이라고 보도 | 2026-10-01 | Bloomberg/Reuters 계열 보도 · 2026-10-01 [P2] |
| TSM | 2026년 설비투자 가이던스 | 2026년 자본지출 가이던스 600억~640억달러 (2026-07-16 실적발표에서 제시, 직전 520억~560억달러에서 상향) | 2026-07-16 (최신 가이던스, 변동 없음) | TSMC 실적발표 · 2026-07-16 [P1] |
| ANET | Arista, FY2026 매출 가이던스 상향 | AI 네트워킹 수요를 근거로 FY2026 매출 가이던스를 기존 115억달러에서 126억달러로 상향 | 2026-10-01 (Bernstein 커버리지 개시 보도 기준) | 검색 집계 보도 · 2026-10-01 [P3] |
| CRDO | Credo 분기 실적 발표 | FY2027 1분기 매출 4억7,900만달러 발표, 발표 당일 주가 약 -18~20% | 2026-09-01 | 검색 집계 보도 [P3] |
| VRT | Vertiv, UtilityInnovation Group 인수 | 14.5억달러 선지급 + 최대 11.5억달러 언아웃(earnout) 조건으로 인수 발표 | 2026-09-02 | 검색 집계 보도 [P3] |
| APLD | Applied Digital, CoreWeave 임대 확장 | CoreWeave 대상 150MW 임대 확장 발표, 누적 CoreWeave 계약 용량 400MW · 3건 합산 임대수익 약 110억달러 | 2026-08-29 | 검색 집계 보도 [P3] |

비고: HBM/DRAM/NAND 현물가 및 AI 서버 출하량 관련 TrendForce 등 수치는 1차 출처(TrendForce 원문) 직접 확인이 안 되어 본 표에서 제외함(신뢰도 낮은 2차 집계 블로그 출처만 확인됨).

---

## [5-A] AI 인프라 — 수요측/하이퍼스케일러 CAPEX

신규 변동 없음 — 2026-10-01 기준 MSFT·AMZN·GOOGL·META 모두 Q3 2026 실적 발표 전으로, 직전 가이던스 유지 중:
- MSFT: 2026년 캘린더연도 설비투자 가이던스 약 1,750억달러 (2026-07 Q2 실적발표 기준)
- AMZN: FY2026 설비투자 가이던스 약 2,200억달러로 상향 (2026-07 Q2 실적발표 기준)
- GOOGL: FY2026 설비투자 가이던스 1,950억~2,050억달러 (2026-07 Q2 실적발표 기준)
- META: FY2026 설비투자 가이던스 1,250억~1,450억달러 (2026-07 Q2 실적발표 기준)

출처: 각사 2026년 2분기(Q2) 실적발표 자료 [P1] — 검색 집계로 교차확인 [P3]

---

## [6] 시총상위 10 — AI 무관 일반 이슈

| 기업 | 사실 내용 | 출처일자 | 출처+태그 |
|------|-----------|----------|-----------|
| MSFT | LinkedIn CEO 라이언 롤란스키(Ryan Roslansky) 연내 퇴임 발표, COO 댄 샤피로(Dan Shapero)가 후임 | 2026-10-01 | CNBC/Microsoft 블로그 · 2026-10-01 [P2] |
| AAPL | 영국 Apple·Amazon 소비자 집단소송, 영국 경쟁항소재판소(CAT)가 일부 재개 결정 — 최대 2억8,900만~3억600만파운드 배상 가능성 보도 | 2026-09-28 | 검색 집계 보도 · 2026-09-28 [P3] |
| BRK (버크셔 해서웨이) | 워런 버핏, 아들 하워드 버핏(Howard Buffett)에게 이사회 의장직 이양 — 버핏은 명예회장(Chairman Emeritus)으로, CEO는 그렉 에이블(Greg Abel) 유지 | 2026-09-18 | 검색 집계 보도 · 2026-09-18 [P3] |
| TSLA | 로드스터 공개 행사, 기상 사유로 2026-10-01에서 2026-10-15로 연기 | 2026-10-01 (연기 발표) | 검색 집계 보도 [P3] |

비고: AMZN(FTC 반독점 재판 10/13 예정), GOOGL(검색 반독점 항소 진행 중, 신규 진전 없음), META(다주 청소년안전 관련 약 171억달러 합의 등은 2026-08월 사안으로 금일 신규 아님) — 금일(10/1) 기준 신규 변동 없음.

---

## [7] 기관·대형 자금 수급 (데일리)

| 항목 | 종목 | 사실 내용 | 규모(수치) | 출처+태그 |
|------|------|-----------|------------|-----------|
| ETF 자금흐름 | QQQ | 일일 순유입 | 31억2,969만달러 (2026-09-30 기준), 운용자산(AUM) 4,975억8,413만달러 | Yahoo Finance/etf.com · "Daily ETF Flows: QQQ SMH Top The List" · https://finance.yahoo.com/markets/options/articles/daily-etf-flows-qqq-smh-210007200.html [P3] |
| ETF 순자산 | SMH | 2026-09-30 기준 총 순자산 748억8,000만달러, 연초 이후 수익률 +68.93% | 748.8억달러 | VanEck 펀드 페이지 · 2026-09-30 기준 [P1] |
| ETF 자금흐름 | SOXX | 최근 1주 순유입 38.1억달러(AUM의 8.3%), 최근 1개월(9월) 순유입 94.3억달러(AUM의 20.5%), 2026-09-30 기준 순자산 약 484.3억달러 | 38.1억달러(1주)/94.3억달러(1개월) | iShares/BlackRock 펀드 데이터 집계 [P3] |
| 비정상 옵션 활동 | NVDA | 2026-09-29 콜옵션 매수: 230달러 행사가 125계약, 232.5달러 행사가 280계약(만기 2026-10-02); 별도로 230달러 행사가 약세 콜 스프레드(만기 2026-09-30, 거래대금 5만300달러) 포착 | N/A | Benzinga · "10 Information Technology Stocks With Whale Alerts" · 2026-09-29 [P3] |

비고: SMH/SOXX/QQQ 관련 블록트레이드(대량 단일 체결) 자체는 검색으로 확인되지 않아 N/A. AVGO 관련 10/1 특정 비정상 옵션활동도 확인되지 않아 N/A.

---

## [7-A] Form 4 내부자거래

N/A — 2026년 10월 신규 Form 4 공시 없음. (NVDA·AVGO·CRDO·CLS·APLD·VRT·SMCI 전 종목에서 2026년 9월 1일~25일 사이 거래만 확인되며, 대부분 기존 Rule 10b5-1 사전설정 매매계획에 따른 처분. 10월 신규 공시는 검색으로 확인되지 않음.)

주요 9월 거래 참고(10월 공시 아님, 배경 정보):
- NVDA: 티모시 테터(법률고문) 2026-09-21 지분 매각
- AVGO: 헨리 사무엘리(이사) 2026-09-23 70만2,190주 매각 (10b5-1 계획)
- CRDO: COO 얏 퉁 람(Yat Tung Lam) 2026-09-25 10만주 매각 (10b5-1 계획)
- CLS: CEO 로버트 미오니스 2026-09-23 2만3,396주 매각 (10b5-1 계획)
- APLD: 공동창업자 제이슨 장 2026-09-12 RSU 베스팅 관련 비자발적 처분 4만9,188주
- VRT: CEO 조르다노 알베르타치 2026-09-08 11만8,523주 증여 처분
- SMCI: CEO 찰스 리앙 2026-09-03~04 배우자 명의 20만주 매각 (10b5-1 계획)

출처: SEC EDGAR Form 4 / StockTitan 집계 [P1][P3]

---

## [8] 향후 14일 주요 일정 (2026-10-02 ~ 2026-10-16)

| 날짜 | 구분 | 내용 | 출처 |
|------|------|------|------|
| 2026-10-02 | 경제지표 | 9월 비농업고용지표(미 고용보고서) 발표 예정, 08:30 ET | BLS 일정 · https://www.bls.gov/schedule/news_release/empsit.htm [P1] |
| 2026-10-05~10-14 | 기업일정 | TSMC 실적발표 전 조용한기간(quiet period) | TSMC IR [P1] |
| 2026-10-08(추정) | 기업일정 | TSMC 9월 매출 발표 예정(월간 매출 공시 관행 기준) | 검색 집계, 확인 필요 [N/A] |
| 2026-10-12~10-15 | 컨퍼런스 | OCP(Open Compute Project) 글로벌 서밋, 산호세 — AI/데이터센터 인프라 관련(VRT·CLS·APLD·SMCI 연관) | 검색 집계 보도 [P3] |
| 2026-10-13 | 기업일정 | JPMorgan Chase 3분기 실적발표 (약 07:00 ET 자료 발표, 08:30 ET 콘퍼런스콜) | Yahoo Finance/Business Wire · https://finance.yahoo.com/markets/stocks/articles/jpmorganchase-host-third-quarter-2026-202200151.html [P1] |
| 2026-10-13(동일 보도) | 기업일정 | Goldman Sachs 3분기 실적발표 (일부 소스 보도, 교차확인 권장) | 검색 집계 보도 [P3] |
| 2026-10-14 | 경제지표 | CPI 발표 (경제캘린더 집계 사이트 기준, BLS 공식 직접 확인 필요) | 확인 필요 [N/A] |
| 2026-10-14 | 기업일정 | Bank of America·Morgan Stanley 3분기 실적발표 (집계 사이트 기준) | 검색 집계 보도 [P3] |
| 2026-10-14 | 기업일정 | ASML 3분기 실적발표 (콘퍼런스콜 약 01:00 ET) | MarketBeat · https://www.marketbeat.com/earnings/reports/2026-10-14-asml-holding-stock/ [P3] |
| 2026-10-15 | 경제지표 | 9월 소매판매(Advance Retail Sales), PPI 발표 예정(집계 사이트 기준, BLS 공식 확인 필요) | 확인 필요 [N/A] |
| 2026-10-15 | 기업일정 | TSMC 3분기 실적발표 (02:00~03:30 ET / 대만시간 14:00~15:30) | TSMC IR · https://investor.tsmc.com/english/quarterly-results/2026/q3 [P1] |
| 2026-10-17~10-29 | 연준 | FOMC 블랙아웃 기간(공식 연설 없음) | 검색 집계 보도 [P3] |
| 2026-10-27~10-28 | 연준 | FOMC 정례회의, 2026-10-28 14:00 ET 금리 결정 발표(비-SEP 회의) | fedratecalc.com/financecalendar.com 집계 [P3] |

비고: MSFT·NVDA·AAPL·AMZN·GOOGL·META 등 메가캡 실적발표는 통상 10월 하순 이후로, 10/2~10/16 구간 내 확정 일정은 검색으로 확인되지 않음(확인 필요).

---

## [9] 오늘의 사실 목록 (순위 없음)

- [1] S&P500 2026-10-01 종가 7,666.45, +0.19% · CNBC [P2]
- [1] 나스닥종합 2026-10-01 종가 26,871.60, +0.04% · Yahoo Finance [P2]
- [1] 다우존스 2026-10-01 종가 50,926.56, +0.04%(+20.51pt) · Yahoo Finance [P2]
- [1] 러셀2000·SOX 2026-10-01 정확 종가는 출처 상충으로 확인 필요 · [N/A]
- [1-A] S&P500 선물(ES=F) 7,725, +0.12% (2026-10-01 16:59 ET 기준) · 0_data.md [P1]
- [1-A] VIX 16.39, +0.31%; VIX3M/VIX=1.134(콘탱고), VIX/VIX9D=1.171(콘탱고) · 0_data.md [P1]
- [1-A] SPX 옵션 P/C(거래량) 1.122, QQQ 옵션 P/C(거래량) 1.001 · 0_data.md(CBOE) [P1]
- [2] 연준 의장 케빈 워시, 2026-05-22 파월 후임 취임 · Brookings/CNBC [P2][P3]
- [2] FOMC 2026-09-16 정책금리 25bp 인상, 3.75~4.00% · CNBC [P2]
- [2] 10년 국채수익률 2026-10-01 5.24%(-0.05%p), 2년물 4.80%(-0.112%p) · 검색 집계 [P3]
- [2] 다음 FOMC 2026-10-27~28, CME FedWatch 수치는 출처 상충으로 단일 확정치 확인 필요 · [N/A]
- [3] ISM 제조업 PMI 9월 54.5%, 전월 54.6% · PR Newswire(ISM) [P1]
- [3] ADP 민간고용 9월 +90,000명, 예상 +68,000명, 전월 +36,000명(수정치) · CNBC [P2]
- [3] 9월 비농업고용지표는 2026-10-02 08:30 ET 발표 예정(셧다운 없음), 실제 발표치는 확인 필요 · BLS [P1]
- [4] 액센츄어(ACN) FY Q4 실적 호조로 급등(+16~21%, 출처별 상이) · 검색 집계 [P3]
- [4] 시놉시스(SNPS) 인베스터데이에서 FY2027 가이던스 상향, OpenAI 파트너십 발표 · 검색 집계 [P3]
- [4-A] Broadcom, Anthropic에 최대 420억달러 전환사채 대출 제공 보도 · CNBC(로이터 인용) [P2]
- [4-A] UnitedHealthcare 2027년 메디케어 플랜 발표(0달러 보험료 등) · Yahoo/Benzinga [P3]
- [4-A] Amazon-Constellation, 메릴랜드 원자력발전 20년 PPA 체결 · Yahoo [P3]
- [5] NVDA 이사회, 1,500억달러 자사주매입 추가 승인(잔여 총 2,350억달러, 2028회계연도까지) · NVIDIA 뉴스룸 [P1]
- [5] AMD, World Labs를 82억달러 전액주식으로 인수 발표 · Bloomberg [P2]
- [5] TSMC, 텍사스 신규 캠퍼스 건설 초기 검토 보도 · Bloomberg/Reuters [P2]
- [5-A] MSFT/AMZN/GOOGL/META 신규 가이던스 변동 없음, 2026-07 Q2 실적발표 가이던스 유지 중 · 각사 IR [P1]
- [6] MSFT, LinkedIn CEO 라이언 롤란스키 연내 퇴임, COO 댄 샤피로 승계 · CNBC [P2]
- [6] 버크셔 해서웨이, 워런 버핏이 아들 하워드 버핏에게 이사회 의장직 이양(2026-09-18) · 검색 집계 [P3]
- [7] QQQ 2026-09-30 일일 순유입 31.3억달러, SOXX 9월 한달 순유입 94.3억달러 · Yahoo/etf.com, iShares [P3]
- [7-A] NVDA·AVGO·CRDO·CLS·APLD·VRT·SMCI 전종목 2026년 10월 신규 Form 4 공시 없음 · SEC EDGAR [P1]
- [8] 9월 비농업고용지표 2026-10-02 발표 예정 · BLS [P1]
- [8] JPMorgan Chase 3분기 실적발표 2026-10-13 예정 · Yahoo Finance/Business Wire [P1]
- [8] TSMC 3분기 실적발표 2026-10-15 예정 · TSMC IR [P1]
- [8] 다음 FOMC 회의 2026-10-27~28 예정 · 검색 집계 [P3]
