# 미국 시장 데일리 수집 결과 (Collect)
# 기준일: 2026-07-14 (화) · 미국 정규장 종가 기준(2026-07-13 월요일 종가) · 실행모드: 데일리 코어([1][2][4][5][7][9]) + 조건부([3] 지표발표일 임박·[8] 일정 갱신·[6] 신규이슈 있음·[7-A] 신규공시 확인)

# 생성시각(KST): 2026-07-14 09:40

> 본 문서는 순수 사실 수집(Collect) 결과입니다. 점수·순위·전망·해석은 포함하지 않았습니다(→Analysis 단계 소관).
> 검증 태그: [P1] 1차(Fed·Treasury·BLS·BEA·SEC·기업IR) · [P2] Reuters·Bloomberg·CNBC·WSJ · [P3] 기타 신뢰매체 · [N/A] 확인불가

---

## [1] 미국 주요 지수 + 리스크 지표 〔데일리〕

### 지수 (2026-07-13 월 정규장 종가)

| 항목 | 종가/수치 | 등락률 | (보도된) 원인 | 출처+태그 |
|------|-----------|--------|----------------|-----------|
| S&P 500 | 7,515.34 | -0.79% | 美-이란 무력 충돌 격화, 트럼프 대통령의 이란 해상 봉쇄 재시행 발표로 유가 급등하며 반도체주 동반 하락 | Yahoo Finance · "Stock market today: Dow, S&P 500, Nasdaq fall as chip stocks tumble, oil surges on US-Iran tensions" · https://finance.yahoo.com/markets/live/stock-market-today-monday-july-13-dow-sp-nasdaq-113249278.html [P2] |
| NASDAQ Composite | 25,873.18 | -1.55% | 상동(반도체·메모리주 낙폭 확대) | Yahoo Finance(상동) [P2] |
| Dow Jones | 52,498.64 (-138.37pt) | -0.26% | 에너지주 강세가 낙폭 일부 상쇄, 반도체·기술주 약세가 지수 하락 주도 | Yahoo Finance(상동); Fool.com · "Stock Market Today, July 13: Energy Stocks Cushion Dow as Tech Slides on Geopolitical Tensions" [P2] |
| Russell 2000 | 2,953.17 (-24.64pt) | -0.83% | N/A — 당일 개별 원인 보도 미확인 | Yahoo Finance 데이터 [P3, 원인 N/A] |
| SOX(필라델피아 반도체지수) | N/A — 2026-07-13 종가 확인 실패 | N/A | 검색 결과가 2026-07-10 종가(12,967.16, +0.06%)를 반복 제시하여 07-13 갱신치로 채택하지 않음(교차검증 실패, 창작 방지 원칙에 따라 N/A 처리) | Yahoo Finance/TradingEconomics 스니펫 [P3, 확인불가] |

### 선물 (2026-07-14 화 오전 KST, 미국 정규장 개장 전 — 2026-07-13 월 야간 미국시간 기준)

| 항목 | 동향 | 출처+태그 |
|------|------|-----------|
| ES(S&P500 선물) | 거의 보합권(플랫 부근) | CNBC · "Stock futures are little changed as Middle East tensions escalate; traders await earnings and inflation data" [P2] |
| NQ(나스닥100 선물) | 거의 보합권(플랫 부근, 소폭 마이너스) | CNBC(상동) [P2] |
| Dow 선물 | -40pt(-0.1%) | CNBC(상동) [P2] |

### 리스크 지표 (2026-07-13 월 기준)

| 항목 | 종가/수치 | 등락률 | 출처+태그 |
|------|-----------|--------|-----------|
| VIX | 17.16 | +14.17%(+2.13pt) | Yahoo Finance 데이터 종합 [P3] |
| DXY(달러인덱스) | 100.9305 | -0.02% | TradingEconomics [P3] |
| WTI 원유 | 약 $73.78~74/bbl | 장중 +3.3%~+4% | CNBC(상동); Yahoo Finance [P2] |
| Brent 원유 | 약 $78.48~79/bbl(장중), 이후 야간 선물 $83 상회 | 장중 +3.3%~+4%, 야간 9월물 +9.6%(2020년 이후 최대 일일 상승폭) | CNBC · "Brent oil jumps more than 9%, biggest daily gain since 2020, after Trump reinstates Iran blockade" [P2] |
| Gold(금) | $3,993.29/oz | -3.10% | TradingEconomics [P3] |

**보도된 배경 사실(지정학 리스크 관련):**
- 트럼프 대통령이 이란 해상 봉�хе(블록케이드) 재시행을 선언, 미국-이란이 호르무즈 해협 통제권을 두고 재차 무력 충돌
- 해당 충돌은 지난 6월 17일 양국이 체결한 잠정 평화협정상 호르무즈 해협 재개방 방식을 둘러싼 해석 차이에서 비롯됐다고 보도
- 출처: CNBC · "Brent oil jumps more than 9%, biggest daily gain since 2020, after Trump reinstates Iran blockade"(2026-07-12) [P2]

---

## [2] 금리 / 연준 〔데일리〕

| 항목 | 사실 내용(발언·수치) | 출처+태그 |
|------|----------------------|-----------|
| 미 국채 2년물(07-13) | 4.23% | TradingEconomics [P3] |
| 미 국채 10년물(07-13) | 4.58% | TradingEconomics [P3] |
| 10Y-2Y 스프레드 | N/A — 07-13 기준 정확한 산출치 확인 실패(직전 확인 가능 수치는 07-10 기준 +36bp) | FRED T10Y2Y 관련 스니펫 [P3, 07-13 수치 N/A] |
| Fed 거버너 Waller 발언(07-13, 뉴욕경제인협회 연설) | "지난 전쟁과 싸우지 말아야 한다(shouldn't fight the last war)"면서도 금리 인상 가능성은 여전히 열려있다고 언급. 인플레이션이 관세·에너지가격 급등 외에 인공지능(AI)발 수요 파급효과로도 확대됐다고 발언. "2021년에 고물가에 더 일찍 대응하지 못한 실수를 반복하지 않기로 결심했다"고 언급 | CNBC · "Waller says Fed shouldn't 'fight the last war' on inflation but warns hikes still possible"(2026-07-13) [P2]; Federal Reserve Board 연설 원문 · https://www.federalreserve.gov/newsevents/speech/waller20260713a.htm [P1] |
| Fed 거버너 Bowman(07-13) | 같은 날 연설 예정으로 보도되었으나, 발언 내용 구체 인용문은 검색으로 확인하지 못함 | Yahoo Finance · "watch week Warsh testifies bank" 관련 스니펫 [P3, 발언 내용 N/A] |
| Fed 워시(Warsh) 의장, 하원 금융서비스위원회 반기 통화정책 증언 | 2026-07-14(화) 10:00 ET 예정(취임 후 첫 반기 증언). CPI 발표(07-14 08:30 ET) 90분 뒤 증언 시작 | Yahoo Finance/Congress.net 종합 [P2] |
| Fed 워시 의장, 상원 은행위원회 증언 | 2026-07-15(수) 예정(정확 시각 확인 필요) | cryptobriefing.com [P3, 시각 확인 필요] |
| CME FedWatch — 차기 FOMC(2026-07-29) 확률 | 금리 인상 약 39%(CME Group 집계, 시점: 07-13 보도 기준) | CNBC · "Waller says..." 기사 내 인용(2026-07-13) [P2] |
| CME FedWatch — 참고치(07-08 기준) | 동결 70.1% / 인상 약 30% | growbeansprout.com/CME 관련 집계(07-08) [P3, 07-13 수치와 시점 상이] |
| 직전 FOMC(2026-06-17) | 3.50~3.75% 만장일치 동결(재확인) | Federal Reserve [P1] |
| 차기 FOMC 회의 | 2026-07-28~29 (07-29 14:00 ET/07-30 03:00 KST 결정 발표 예정) | 연준 캘린더 [P1] |

---

## [3] 주요 경제지표 〔조건부 — 발표 임박〕

**N/A — 본 문서 작성 시점(2026-07-14 09:40 KST) 기준 6월 CPI 아직 미발표.** CPI(6월)는 2026-07-14 08:30 ET(=21:30 KST, 오늘 저녁) 발표 예정이며, 컨센서스는 헤드라인 YoY 3.8%(5월 4.2%에서 둔화 전망)로 보도됨. 발표치는 다음 수집 주기에 반영.

| 지표 | 발표시각(ET·KST) | 발표치 | 예상치 | 이전치 | (서프라이즈) | 출처 |
|------|------------------|--------|--------|--------|----------------------------------------|------|
| CPI 헤드라인(6월) | 07-14 08:30 ET / 07-14 21:30 KST | N/A — 미발표 | YoY 약 3.8% | YoY 4.2%(5월) | N/A | Yahoo Finance/Congress.net [P2] |

### 향후 발표 예정(이번 주)
| 지표 | 예정일(ET) | 컨센서스 | 출처 |
|------|-----------|----------|------|
| CPI(6월) | 07-14(화) 08:30 | 헤드라인 YoY 약 3.8% | Yahoo Finance/Congress.net [P2] |
| PPI(6월) | 07-15(수) 08:30 | N/A | BLS [P1] |
| 소매판매(6월) | 07-16(목) 08:30 | N/A | Census [P1] |

---

## [4] 특징 종목 〔데일리, 2026-07-13 세션〕

| 종목 | 티커 | 등락률 | 거래량/특이사항 | (보도된) 핵심 사실 | 출처+태그 |
|------|------|--------|--------|---------------------|-----------|
| SK Hynix(한국 상장분) | 코스피 | -15% | 사상 최대 낙폭(단일일) | 나스닥 데뷔 이후 급등 랠리에 따른 차익실현 매물, 한국 증권사 KIS의 2분기 영업이익 컨센서스 하회 전망 보고서(HBM4 출하 지연 지적)가 촉발 | Motley Fool · "Stock Market Today, July 13: SK Hynix Tumbles 15% in South Korea" [P2] |
| AppLovin | APP | -11%~-12% | S&P500 내 최악 수익률 종목 | 특정 기업 뉴스 없이 하락, AI 트레이드 조정 국면에서 고베타 종목이 낙폭 확대됐다는 관측 보도 | 24/7 Wall St. · "AppLovin Stock Tumbles 12% Amid Broader Selloff"; TradingKey [P3] |
| SpaceX | SPCX | 장중 -4% | 상장 후 최저가 경신 근접(공모가 $135 근접) | 주간 누적 -13% 이상 하락 | Investing.com · "SpaceX shares continue lower, hit lowest level since IPO" [P3] |
| Micron / SanDisk / Western Digital | MU / SNDK / WDC | 3사 모두 약 -6% | 메모리 섹터 동반 하락 | SK Hynix의 약한 가이던스(KIS 보고서)가 메모리 3사에 전이 | 24/7 Wall St. · "Micron, SanDisk, Western Digital Fall 6% as SK Hynix's Weak Outlook Rattles Memory Stocks"(2026-07-13) [P3] |
| Intel | INTC | -5% 초과 | 반도체 대형주 동반 매도 | 리스크오프 국면에서 반도체 전반 약세에 동반 | Yahoo Finance 종합 [P2] |
| AMD | AMD | -3% | 반도체 대형주 동반 매도(단, 개별 보도는 +2.13% 상승치도 혼재 확인, 종가 기준 불일치) | N/A — 정확한 종가 등락률 출처 간 불일치로 확정 못함 | Yahoo Finance 종합 [P2, 수치 불일치] |
| 에너지주(Valero, ConocoPhillips, ExxonMobil, Chevron 등) | VLO/COP/XOM/CVX | +2%~+4% | 유가 급등 수혜 | 이란 관련 유가 급등에 따른 에너지 섹터 강세 | CNBC 종합 [P2] |
| IBM | IBM | N/A(가격 변동 특이사항 없음) | 옵션 거래량 급증(51,693계약, 약 520만주 상당) | 옵션시장에서 이례적 거래량 포착 | Benzinga 관련 종합 [P3] |

---

## [5] AI 인프라 — 공급 측 〔데일리〕

| 기업 | 뉴스 제목 | 사실 내용(무슨 일이) | 출처일자 | 출처+태그 |
|------|-----------|----------------------|----------|-----------|
| SK Hynix(SKHY, 美 ADR) | 한국 상장분 급락, 美 ADR 동반 압박 | 코스피 상장분이 사상 최대 낙폭(-15%) 기록, KIS 증권 보고서가 2분기 영업이익 컨센서스 하회 및 HBM4 출하 지연 가능성 지적. 이 여파로 글로벌 메모리·반도체주 전반 약세 | 2026-07-13 | Motley Fool [P2] |
| NVDA | 개별 뉴스 없음(섹터 동반 약세) | 반도체 섹터 전반 리스크오프 흐름 속 하락 동반(개별 사유 보도 확인 안됨) | 2026-07-13 | Yahoo Finance 종합 [P3] |
| AVGO | 주가 -3.22% | 고성장 반도체주 대상 로테이션(차익실현) 흐름 속 하락으로 보도 | 2026-07-13 | TradingKey · "Broadcom Inc Stock (AVGO) Moved Down by 3.22% on Jul 13" [P3] |
| AMD | Zen 6 EPYC(코드네임 Venice) 서버 CPU 출시 예고(재확인) | 2026-07-22 Advancing AI 2026 컨퍼런스에서 공개 예정이라고 재확인 보도. Citi는 "업계를 뒤흔들 발표(industry-shaking announcements)"가 있을 것으로 예상한다고 언급 | 2026-07-13 보도 시점 | 종합 보도 [P3] |
| Celestica(CLS) | 2026 전망 상향(재확인) | 클라우드 고객 대상 AI 데이터센터向 수요 강세로 2026년 가이던스 상향 — 2분기 실적·리더십 변경 발표(07-06)에서 이미 반영된 사실 | 2026-07-06(원보도) | Celestica 보도자료 [P1] |
| Vertiv(VRT) | 말레이시아 신규 생산시설(재확인) | AI·디지털 인프라 수요 대응 위해 말레이시아에 제조 능력 확대 발표(07-01) — 신규 변동 없음 | 2026-07-01(원보도) | Vertiv 뉴스룸 [P1] |
| Arista Networks(ANET) | 차기 실적일 확정 | 2026-08-04(화) 2분기 실적 발표 예정으로 확인. 06-09 발표된 차세대 1.6테라비트 AI 패브릭 포트폴리오는 변동 없음 | 2026-07-13 확인 | StockTitan 관련 종합 [P3] |

### 추가 시그널 (HBM/DRAM/NAND, AI서버·광통신)

| 항목 | 사실 내용 | 출처+태그 |
|------|-----------|-----------|
| HBM 공급 현황 | 2026년 HBM 생산능력이 전량 매진(sold out) 상태이며 제조사들이 신규 주문을 받지 않고 있다고 보도. HBM3 약 $200/스택, HBM3E 약 $300/스택, HBM4 약 $500/스택 수준(업계 추정치, 비공개 계약 기반이라 공식 현물가는 아님) | Silicon Analysts 관련 종합 [P3] |
| DRAM 계약가 전망(3분기) | 범용 D RAM 계약가 전분기 대비 +13~18% 상승 전망 | TrendForce 관련 보도 [P3] |
| NAND 계약가 전망(3분기) | NAND Flash 계약가 전분기 대비 +10~15% 상승 전망(소비자 수요 약화로 상승폭은 둔화) | TrendForce 관련 보도 [P3] |
| SK Hynix 실적 우려 | 한국 증권사 KIS가 SK Hynix의 2분기 영업이익이 컨센서스를 약 8% 하회할 수 있다는 전망 보고서 발표, HBM4 출하 지연·HBM 계약 의존도를 근거로 제시 | 2026-07-13 | Motley Fool/24/7 Wall St. 종합 [P2/P3] |

---

## [5-A] AI 인프라 — 수요 측 / 하이퍼스케일러 CAPEX 〔실적시즌 아님 — 직전 가이던스 유지〕

> MSFT·META 07-29, AAPL·AMZN 07-30 차기 실적 예정(2분기). CAPEX 수치는 신규 변동 없음.

- MSFT: 신규 변동 없음 — 직전 가이던스 유지(2026년 AI 관련 지출 약 $190B 추산, 출처일자 2026-07-13 · 24/7 Wall St. 기사 내 인용 [P3])
- AMZN: 신규 변동 없음 — 직전 가이던스 유지(2026년 capex 약 $200B 전망, 출처일자 2026-07-13 · 24/7 Wall St. [P3])
- GOOGL: 신규 변동 없음 — 직전 가이던스 유지(2026년 capex $175B~$185B, 출처일자 2026-07-13 · 24/7 Wall St. [P3])
- META: 신규 변동 없음 — 직전 가이던스 유지(2026년 capex $125B~$145B, 출처일자 2026-07-13 · 24/7 Wall St. [P3])

> 참고 사실(주가, capex 아님): 7사(매그니피센트7) 중 2026년 최고 수익률 기록 종목은 Apple(+16%)로 보도되며, 나머지 6개사는 모두 연중 고점 대비 하락한 상태(MSFT $392 vs 고점 $551, GOOGL $355 vs $408, AMZN $249 vs $279, NVDA $204 vs $236, META $660 vs $794, TSLA $393 vs $499)라고 보도됨 · 24/7 Wall St. · "Apple Sat Out the AI Arms Race..."(2026-07-13) [P3]

---

## [6] 시총 상위 10 — AI 무관 일반 이슈 〔신규 이슈 있음〕

| 기업 | 사실 내용 | 출처일자 | 출처+태그 |
|------|-----------|----------|-----------|
| AAPL | John Ternus(현 하드웨어엔지니어링 수석부사장)가 2026-09-01부로 Apple CEO에 취임 예정(2026-04-20 발표, 이사회 만장일치 승인). Tim Cook은 이사회 executive chairman으로 이동, 정책 담당자 대응 등 일부 역할 지속 수행 예정. Apple은 2026년 연초 대비 +16% 상승하며 매그니피센트7 중 최고 수익률 기록, 다음 실적발표는 07-30 예정 | 2026-04-20(원발표), 2026-07-13(재확인 보도) | Apple Newsroom · "Tim Cook to become Apple Executive Chairman, John Ternus to become Apple CEO"; CNBC(2026-04-20) [P1/P2] |
| SK Hynix(SKHYV/SKHY) | 2026-07-10 나스닥 데뷔($265억 규모, 외국기업 美 상장 사상 최대 규모, ADR 공모가 $149, 데뷔일 +13%) — 이후 07-13 급락(-15%, 한국 상장분 기준)으로 반전. 티커는 07-15부터 SKHYV에서 SKHY로 변경 예정 | 2026-07-10(상장), 2026-07-13(급락) | CNBC/TechCrunch(07-10) [P2]; Motley Fool(07-13) [P2] |

---

## [7] 기관·대형 자금 수급 〔데일리〕

| 항목 | 종목/ETF | 사실 내용 | 규모(수치) | 출처+태그 |
|------|------|-----------|------------|-----------|
| 옵션시장 이상거래 | INTC(인텔) | 풋옵션 거래량이 미결제약정(22계약) 대비 급증(V/OI 비율 243.23), 행사가 $85, 만기 07-22 | 프리미엄 약 $278,250 | Futunn News · "Unusual Options Activity: INTC, FIG and Others Attract Market Bets"(2026-07-13) [P3] |
| 옵션시장 이상거래 | 반도체 섹터 전반 | 2거래일 내 5개 이상 반도체 종목에서 콜옵션 대량 매수 포착(매크로 베팅 성격으로 해석 가능하다는 보도, 단 해석 부분은 본 문서에서 채택하지 않음) | N/A | Benzinga 관련 종합 [P3] |
| ETF 자금흐름(직전 확인분, 07-08) | SOXX(iShares Semiconductor) | 단일 세션 순유입(직전 파일과 동일 사실, 07-09~13 신규 수치 확인 안됨) | $54.3억(1일, 07-08) | ETF.com [P3] |
| ETF 자금흐름(직전 확인분, 07-08) | SMH(VanEck Semiconductor) | 동일 세션 순유입(직전 파일과 동일 사실) | $5.52억(1일, 07-08) | ETF.com [P3] |
| ETF 자금흐름 | QQQ(Invesco QQQ) | 최근 한 세션 순유출로 보도(정확한 날짜 특정 어려움) | 약 $8억(순유출) | ETF.com 관련 종합 [P3, 날짜 특정 불가] |
| 07-09~13 신규 ETF 자금흐름 개별 세션 수치 | SOXX·SMH·QQQ | N/A — 검색으로 확인하지 못함 | - | - |

---

## [7-A] Insider Trading (SEC Form 4) 〔조건부 — 신규공시 확인〕

| 기업 | 내부자 | 직책 | 매수/매도 | 거래유형 | 규모 | 거래일 | 출처 |
|------|--------|------|-----------|-----------|------|--------|------|
| AVGO | Mark David Brazeal | Chief Legal and Corporate Affairs Officer | 매도 | 확인 필요(재량/10b5-1 여부 미기재) | 25,000주, $9,479,700 | 2026-07-08 | MarketScreener [P3] |
| CRDO | Clyde Hosein | Director | 매도 | 확인 필요 | 3,451주 @ $262.3250 | 2026-07-01 | StockTitan [P3] |
| SMCI | David E. Weigand | SVP·CFO | RSU 행사·세금원천징수(시장 매도 아님) | RSU 행사 | 19,725주 행사, 10,038주 세금원천징수(@$27.65) | 2026-07-01 | StockTitan [P3] |

> NVDA·APLD·VRT 대상 2026-07-08 이후 신규 Form 4 매수/매도 공시는 검색으로 확인하지 못함(N/A). 위 AVGO·CRDO·SMCI 건은 07-01~08 거래로, 07-13 기준으로는 신규 공시가 아니라 직전 확인 사항의 재확인임.

---

## [8] 향후 14일 주요 일정 〔갱신 — 2026-07-14 ~ 07-27〕

### 경제 일정

| 날짜 | 시각(ET·KST) | 이벤트 | 컨센서스 | 이전치 | 출처+태그 |
|------|--------------|--------|----------|--------|------|
| 07-14(화) | 08:30 ET/21:30 KST | CPI(6월) | 헤드라인 YoY 약 3.8% | 4.2% YoY(5월) | Yahoo Finance/Congress.net [P2] |
| 07-14(화) | 10:00 ET/23:00 KST | Fed 워시 의장, 하원 금융서비스위 반기 통화정책 증언(취임 후 최초) | - | - | Congress.net/Yahoo Finance [P2] |
| 07-15(수) | 08:30 ET/21:30 KST | PPI(6월) | N/A | N/A | BLS [P1] |
| 07-15(수) | 시각 확인 필요 | Fed 워시 의장, 상원 은행위 반기 통화정책 증언 | - | - | cryptobriefing.com [P3, 시각 확인 필요] |
| 07-16(목) | 08:30 ET/21:30 KST | 소매판매(6월) | N/A | N/A | Census [P1] |
| 07-28~29 | 07-29 14:00 ET/07-30 03:00 KST | FOMC 금리결정 | - | - | 연준 [P1] |

### 기업 일정

| 날짜 | 기업 | 이벤트 | 컨센서스 EPS | 컨센서스 매출 | 출처+태그 |
|------|------|--------|--------------|---------------|------|
| 07-14(화) | JPMorgan Chase, Bank of America, Goldman Sachs, Citigroup, Wells Fargo | Q2 2026 실적(장전) | N/A | N/A | Benzinga/XTB 종합 [P2/P3] |
| 07-15(수) | Morgan Stanley, BlackRock, Bank of New York Mellon, PNC | Q2 2026 실적 | N/A | N/A | XTB [P3] |
| 07-22~23 | AMD | Advancing AI 2026 컨퍼런스, Zen 6 EPYC(Venice) 서버 CPU 공개 예정 | - | - | 종합 보도 [P3] |
| 08-04(화) | Arista Networks(ANET) | Q2 2026 실적 발표 | N/A | N/A | StockTitan 관련 종합 [P3] |

> 기간 이후 참고: MSFT·META 07-29(실적), AAPL·AMZN 07-30(실적) — 직전 파일과 동일, 재확인 완료.

---

## [9] 오늘의 사실 목록 (순위 없음) 〔데일리〕

```
[1] S&P500 7,515.34(-0.79%), NASDAQ 25,873.18(-1.55%), Dow 52,498.64(-0.26%)(07-13 종가) — 美-이란 충돌 격화·유가 급등·반도체주 약세 · Yahoo Finance[P2]
[1] Russell2000 2,953.17(-0.83%)(07-13 종가), SOX 07-13 종가 확인 실패(N/A) · Yahoo Finance[P3]
[1] VIX 17.16(+14.17%), DXY 100.93(-0.02%), Gold $3,993.29(-3.10%)(07-13) · TradingEconomics[P3]
[1] WTI 장중 +3.3~4%(~$74), Brent 야간선물 9월물 +9.6%(2020년來 최대 일일 상승)(07-12~13) · CNBC[P2]
[1] 트럼프 대통령, 이란 해상 봉쇄 재시행 선언·호르무즈 해협 통제권 두고 美-이란 무력 충돌 · CNBC[P2]
[2] Fed Waller, "지난 전쟁과 싸우지 말아야" 발언하면서도 금리인상 가능성 여전히 열려있다고 언급, AI발 인플레 파급효과 지목(07-13, 뉴욕) · CNBC[P2]
[2] CME FedWatch, 차기 FOMC(07-29) 금리인상 확률 약 39%(07-13 보도 기준) · CNBC[P2]
[2] 미 국채 2년물 4.23%, 10년물 4.58%(07-13) · TradingEconomics[P3]
[2] Fed 워시 의장, 취임 후 첫 하원 반기 통화정책 증언 07-14 10:00 ET 예정(CPI 발표 90분 후) · Congress.net[P2]
[3] CPI(6월) 07-14 08:30 ET 발표 예정(컨센서스 YoY 3.8%), 본 문서 작성 시점 미발표 · Yahoo Finance[P2]
[4] SK Hynix 한국 상장분 -15%(사상 최대 낙폭), KIS 증권 2분기 실적 컨센서스 하회 전망 보고서 촉발 · Motley Fool[P2]
[4] AppLovin -11~12%, 특정 뉴스 없이 S&P500 내 최악 수익률 종목 · 24/7 Wall St.[P3]
[4] Micron·SanDisk·Western Digital 3사 모두 약 -6%, SK Hynix 약세 가이던스 전이 · 24/7 Wall St.[P3]
[4] SpaceX 장중 -4%, 상장후 최저가 근접(공모가 $135 근접) · Investing.com[P3]
[4] 에너지주(Valero·ConocoPhillips·Exxon·Chevron) +2~4%, 유가 급등 수혜 · CNBC[P2]
[5] SK Hynix發 메모리·반도체 섹터 전반 약세, HBM4 출하 지연 우려 · Motley Fool[P2]
[5] HBM 2026년 생산능력 전량 매진 상태, 신규주문 미접수로 보도 · Silicon Analysts 관련[P3]
[5] AMD, 07-22 Advancing AI 2026에서 Zen 6 EPYC(Venice) 공개 예정 재확인 · 종합보도[P3]
[5-A] MSFT/AMZN/GOOGL/META capex 가이던스 신규 변동 없음(직전 가이던스 유지) · 각사 IR 관련[P3]
[6] Apple, John Ternus가 09-01부로 CEO 취임 예정(Tim Cook은 executive chairman 이동), 2026년 Mag7 중 최고 수익률(+16%) · Apple Newsroom[P1]
[6] SK Hynix, 07-10 나스닥 $265억 규모 사상 최대 외국기업 美 상장 이후 07-13 한국 상장분 급락 반전 · CNBC/Motley Fool[P2]
[7] INTC 풋옵션 이상거래 포착(V/OI 243.23배, 행사가 $85, 만기 07-22) · Futunn News[P3]
[7-A] AVGO Chief Legal Officer 07-08 25,000주 매도($947.97만) — 직전 확인분, 07-13 신규 공시 아님 · MarketScreener[P3]
[8] JPMorgan·BofA·Goldman·Citi·Wells Fargo 07-14 장전 Q2 실적 발표로 은행 실적시즌 개막 · Benzinga/XTB[P3]
[8] 차기 FOMC 금리결정 07-29(14:00 ET/07-30 03:00 KST) · 연준[P1]
```

---

## 자가 점검 결과
0. 방화벽 점검: 의견·전망·★·AI영향도·밸류체인·순위·다중추론 없음 — 확인 완료
1. 날짜: 웹 검색으로 2026-07-14(화) 확정, 미국 정규장 기준일은 직전 거래일인 2026-07-13(월) — 완료
2. 모든 수치·뉴스에 출처+검증 태그 부여 — 완료(일부 N/A 명시)
3. 확인 못한 칸 N/A 처리 — 완료(SOX 07-13 종가, 10Y-2Y 스프레드 07-13치, AMD 정확 등락률, ETF 07-09~13 개별 수치, Bowman 발언 내용 등)
4. 원인·영향은 보도된 사실만 기재 — 완료
5. 동일 사건 대표 출처 통합 — 완료
6. [5]공급/[5-A]수요/[6]일반 분류 — 확인 완료
7. CAPEX·가이던스 출처일자 표기 — 완료
8. Form 4 거래유형 구분 — 일부 항목 거래유형(10b5-1/재량 여부) 원문 미확인으로 "확인 필요" 표기
9. [9]는 랭킹이 아닌 사실 나열 — 완료

## 리서치 한계 (다음 단계 참고)
- SOX 지수의 2026-07-13 종가를 검색으로 확인하지 못함. 검색 결과가 계속 07-10 수치(12,967.16)를 반환해 교차검증 실패로 N/A 처리함. Analysis 단계에서 반도체 섹터 흐름 판단 시 SOX 수치 공백을 감안할 것.
- 10Y-2Y 스프레드의 07-13 당일치를 확인하지 못함(가장 최근 확인 가능한 수치는 07-10 기준 +36bp).
- AMD의 07-13 정확한 종가 등락률이 출처 간 불일치(-3% 보도와 +2.13% 보도가 혼재)하여 확정하지 못하고 두 수치를 병기함.
- CME FedWatch 차기 FOMC 확률이 출처 간 시점 불일치(07-08 기준 "동결 70.1%" vs 07-13 CNBC 인용 "인상 약 39%") — 07-13 인용치를 우선 채택했으나 원 계산 시점의 상세 브레이크다운은 확보하지 못함.
- ETF(SOXX/SMH/QQQ) 07-09~13 개별 세션 순유입/유출 수치를 검색으로 확인하지 못함(가장 최근 확인 가능한 수치는 07-08 기준).
- WebFetch(URL 원문 열람) 도구 사용 권한이 이번 세션에서 제한되어(사용자 승인 대기 중 미승인), 전 항목을 WebSearch 스니펫에 의존했음. 특히 CNBC "stocks making the biggest moves midday" 기사 원문 전체를 열람하지 못해 일부 종목(Nio, Braiin 등)의 세부 사실은 스니펫 수준에서만 반영함.
- Bowman 거버너의 07-13 발언 구체 인용문을 확인하지 못함(발언 예정 사실만 확인).
- Form 4 거래유형(10b5-1 계획/재량적 매도/옵션행사) 구분이 AVGO·CRDO 건에서 원문 미확인으로 "확인 필요" 처리됨(SMCI는 RSU 행사로 유형 확인됨).
