# 미국 시장 데일리 수집 결과 (Collect)
# 기준일: 2026-07-20 (월) · 미국 정규장 종가 기준 · 실행모드: [데일리]
# 생성시각(KST): 2026-07-21 05:30

---

## [1] 미국 주요 지수 + 리스크 지표 (데일리)

| 항목 | 종가/수치 | 등락률 | (보도된) 원인 | 출처+태그 |
|---|---|---|---|---|
| S&P500 | 7,443.28 | -0.19% | 미-이란 군사 충돌 재개로 유가 상승, 위험자산 회피 | CNBC · Stock market news for July 20, 2026 · [P2] |
| NASDAQ 종합 | 25,508.07 | -0.05% | 반도체株 반등이 일부 상쇄, 대형 빅테크 실적 대기 심리 | CNBC · 상동 · [P2] |
| Dow Jones | 51,839.26 | -307.16pt (-0.59%) | 애플 -2%대 급락이 지수 하방 견인 | CNBC · 상동 · [P2] |
| Russell 2000 | 확인 필요(N/A) | 확인 필요(N/A) | — | 7/20 정확 종가 검색 실패. 참고: IWM ETF 일중 $294.57~$296.50 레인지 · Yahoo Finance/Investing.com · [P3] |
| SOX (필라델피아 반도체지수) | 11,950.11 | +2.37%(약 +2.3~3% 보도 혼재) | 엔비디아·AMD·브로드컴 등 반도체주 반등, MS의 AMD Helios AI 추론 솔루션 도입 발표 | Investing.com/Yahoo Finance 데이터 · [P3]; Bloomberg "US Stocks Rebound From Selloff as Nvidia, Other Chipmakers Rise" · [P2] |
| ES (S&P500 선물, 한국시간 조간) | 확인 필요(N/A) | 확인 필요(N/A) | 검색으로 구체 수치 확인 실패 | N/A |
| NQ (나스닥 선물, 한국시간 조간) | 확인 필요(N/A) | 확인 필요(N/A) | 검색으로 구체 수치 확인 실패 | N/A |
| VIX | 자료 상충: 시가 17.21, 일중 16.15~17.56 레인지 보도 vs 별도 보도 "18.77, +12.19%" | 확인 필요(N/A) | 미-이란 지정학 리스크에 따른 변동성 확대 | Yahoo Finance/Investing.com(레인지) · [P3]; 별도 검색 스니펫(18.77) 출처 불명확 · [N/A] — 상충으로 단정 수치 기재 보류 |
| DXY (달러인덱스) | 100.72 | 확인 필요(N/A) | — | Investing.com/Yahoo Finance · [P3] |
| WTI 원유 | 종가 $83.23(장중 +0.9%) 보도와 $82.35(-0.17%) 보도 상충 | 확인 필요(N/A) | 미국의 대이란 추가 공습, 호르무즈 해협 관련 긴장, 쿠웨이트 석유시설 피격 | CNBC · "Oil prices rise after Trump says Iran will pay for killing U.S. service members" · [P2] |
| Brent 원유 | $88.19→$89.22 마감 보도(약 +1.3%) 또는 장중 $88~91 구간, 별도 보도는 +0.50% $88.54 | 확인 필요(N/A, 보도 간 수치 상충) | 상동(미-이란 군사 충돌, 호르무즈 리스크) | CNBC · 상동 · [P2] |
| Gold | 현물 기준 장중 $4,009~4,010/oz(오전 9시 ET), 선물(8월물) 시가 $4,005.60(전일 대비 -0.3%); 별도 데이터는 $4,001.06(-0.40%) | 확인 필요(N/A, 장중 vs 종가 혼재) | 중동 폭력사태 지속에도 $4,000 상회 유지 | Yahoo Finance · "Gold prices today, Monday, July 20, 2026" · [P2]; Fortune · [P3] |

비고: 반도체지수는 지난주(7/17 이전) 약세장(bear market) 진입 후 이날 반등한 것으로 보도됨(SOXX 최근 1개월 -18.6%~-20% 보도, 2008년 11월 이후 최악의 월간 성과라는 보도 존재) — Benzinga · [P3]

---

## [2] 금리 / 연준 (데일리)

| 항목 | 사실 내용(발언·수치) | 출처+태그 |
|---|---|---|
| 2Y 국채금리 | 가장 최근 확인된 수치: 7/17 기준 4.18% (7/20 당일 수치 검색 미확인) | Advisorperspectives.com dshort "Treasury Yields Snapshot: July 17, 2026" · [P3] |
| 10Y 국채금리 | 가장 최근 확인된 수치: 7/17 기준 4.55% (7/20 당일 수치 검색 미확인) | 상동 · [P3] |
| 10Y-2Y 스프레드 | 7/17 기준 약 +0.37%p (4.55%-4.18%, 산술 계산) | FRED T10Y2Y 시리즈 페이지 · [P1]; 계산은 자체 산술 |
| 연준 의장 발언 | 신임 연준의장 케빈 워시(Kevin Warsh), 6월 FOMC 이후 첫 공개 발언(7/1, 신트라 ECB 포럼)에서 "물가가 너무 높다(prices are too high)"고 언급, 2% 목표 달성 의지 재확인 | Chase.com · "Kevin Warsh: 'Prices Are Too High.'" · [P3] |
| 6월 FOMC 결정문 | 연방기금금리 목표 범위를 3.50~3.75%로 유지 결정(6/16-17 회의) | Federal Reserve · FOMC statement 2026-06-17 · [P1] |
| 6월 FOMC 의사록 관련 보도 | 정책위원 18명 중 절반은 금리 동결·인하 지지, 나머지 절반은 연내 인상 옹호로 의견 분산되었다는 보도 | 검색 스니펫(1차 출처 미확인) · [P3] |
| 다음 FOMC 회의 | 2026-07-28~29(현지시간), 금리 결정 발표 7/29 14:00 ET | Federal Reserve 공식 캘린더 · [P1] |
| CME FedWatch (7/29 회의) | 금리 동결(hold) 확률 86.7%로 보도(7/20 기준) | growbeansprout.com FedWatch 데이터 인용 · [P3] — CME 공식 페이지 직접 확인은 못함 |

---

## [3] 주요 경제지표 (조건부)

N/A — 금일(2026-07-20) CPI/Core CPI/PPI/GDP/Payrolls/실업률/신규실업수당청구/소매판매/ISM 제조업·서비스업 지표 중 해당 발표 없음.

참고(표 대상 지표 아님): Conference Board 경기선행지수(Leading Economic Index)가 7/20 10:00 ET에 발표 예정이었다는 보도가 있었으나(전월치 +0.1%), 본 표의 지정 지표 목록에 포함되지 않아 별도 집계하지 않음 — Investing.com · "Light economic calendar ahead on Monday with leading index data" · [P3]

---

## [4] 특징 종목 (데일리)

| 종목 | 티커 | 등락률 | 거래량 | (보도된) 핵심 사실 | 출처+태그 |
|---|---|---|---|---|---|
| Apple | AAPL | 약 -2%대 하락 | 확인 필요(N/A) | 실적 발표(7/30 예정) 전 차익실현, 애널리스트의 3Q 총마진 190bp 하락 경고(평균 36.8% 전망), iPhone 가격 인상 우려 등이 복합 거론됨 | Motley Fool/Yahoo Finance · "Why Apple Stock Dropped Today" · [P2]; Benzinga · [P3] |
| Oracle | ORCL | -4.4% | 확인 필요(N/A) | 검색 스니펫에 등락률만 확인, 구체 원인 기사 미확인 | Benzinga · "Leading And Lagging Sectors For July 20, 2026" · [P3] |
| ServiceNow | NOW | -4.2% | 확인 필요(N/A) | 상동, 구체 원인 미확인 | 상동 · [P3] |
| Adobe | ADBE | -4.0% | 확인 필요(N/A) | 상동, 구체 원인 미확인 | 상동 · [P3] |
| Lumentum | LITE | +7.5% | 확인 필요(N/A) | 검색 스니펫에 등락률만 확인, 구체 촉발 뉴스 미확인 | 검색 결과(1차 기사 URL 미특정) · [N/A] |
| Teradyne | TER | +4.6% | 확인 필요(N/A) | 상동 | 상동 · [N/A] |
| SpaceX(SPCX) | SPCX | 상장 후 고점 대비 약 -39%, 최근 1개월 약 -30% | 확인 필요(N/A) | 상장 직후 $135→$225.64 급등 후 급락. $250억 규모 채권 발행 및 8월 초 예정된 내부자 락업 해제를 앞둔 기관 매도가 하락 원인으로 거론 | 검색 결과(1차 기사 URL 미특정) · [P3] |

---

## [5] AI 인프라 — 공급 측 (데일리)

| 기업 | 뉴스 제목 | 사실 내용(무슨 일이) | 출처일자 | 출처+태그 |
|---|---|---|---|---|
| NVDA | 엔비디아, $200 지지선 테스트 | 중국 Kimi K3 모델 등 AI 경쟁 심화 및 AI 밸류에이션 우려 속 주가 $200선 공방. 일본에서의 물리적 AI(physical AI) 딜은 진행 중으로 언급 | 2026-07-20 | FX Leaders · "Nvidia Stock NVDA Tests $200 Support" · [P3] |
| NVDA | 반등 국면 | 이날 장중 +2%대 상승 후 상승폭 축소(trim) | 2026-07-20 | Bloomberg · "US Stocks Rebound From Selloff as Nvidia, Other Chipmakers Rise" · [P2] |
| AMD | Microsoft Helios 채택 | 마이크로소프트가 AMD의 Helios 솔루션을 AI 추론(inference)용으로 도입한다고 발표, 이 소식에 AMD 주가 +3%대 상승 | 2026-07-20 | Bloomberg · 상동 · [P2] |
| AVGO(Broadcom) | 주가 반등 | 이날 +3.10% 상승 마감 | 2026-07-20 | TradingKey · "Broadcom Inc Stock (AVGO) Moved Up by 3.10% on Jul 20" · [P3] |
| AVGO(Broadcom) | Apple 공급계약 갱신 | 애플과 2031년까지의 칩 공급계약 갱신 발표, 총 $300억 이상 규모, 무선용 FBAR 필터 및 커스텀(AI 추정) 칩 포함 | 확인 필요(정확 발표일 N/A, 7월 중 보도) | Yahoo Finance/24-7 Wall St 등 요약 보도 · [P3] |
| AVGO(Broadcom) | Q2 FY2026 실적(직전 발표분, 참고) | 매출 $221.9억(YoY +47.9%), AI 반도체 매출 $108.0억(YoY +143%) | 발표일 확인 필요(N/A, 6~7월 초 실적시즌으로 추정) | FX Leaders 요약 인용 · [P3] |
| AVGO(Broadcom) | DriveNets Tomahawk 6 채택 | DriveNets가 브로드컴의 Tomahawk 6 ASIC을 활용한 오픈 이더넷 AI 데이터센터 팹릭 포트폴리오 확장, 3Q 2026 배포 목표 | 확인 필요(N/A, 7월 보도) | Yahoo Finance · "Broadcom (AVGO) Backs DriveNets Tomahawk 6 Push" · [P3] |
| TSM | Q2 2026 실적(직전 발표, 참고) | 매출 NT$1조2,703.8억(연결), 분기 매출 $402억(가이던스 상회), 매출총이익률 67.7%(예상 상회), YoY 매출 +36.0%, 순이익·EPS YoY +77.4% | 2026-07-16 | SEC Form 6-K(TSMC) · [P1] |
| TSM | 2026 가이던스 상향 | 2026년 연간 매출 성장률 전망을 "40% 소폭 상회"로 상향, 2026 CAPEX 가이던스 $187.5억~$200억으로 상향. 3Q 매출 가이던스 $446억~$458억, 매출총이익률 65~67%(2나노 램프업 비용으로 일시적 압박 언급) | 2026-07-16 | SEC Form 6-K(TSMC) · [P1] |
| CRDO(Credo) | 애널리스트 커버리지 확대(참고, 7/6 보도) | Evercore ISI가 Outperform($325 목표가)로 커버리지 개시, Stifel 목표가 $350으로 상향(Buy 유지), BofA 목표가 $340으로 상향 | 2026-07-06 | StocksToTrade · [P3] |
| CLS(Celestica)/ANET(Arista) | UBS, 데이터센터 수요 프리뷰에서 주목 | UBS가 실적시즌을 앞두고 데이터센터 수요를 프리뷰하며 Celestica·Arista·Extreme·Lumentum 등을 주목. Celestica는 1.6T 네트워킹 생산 램프에 힘입어 컨센서스 매출 성장률이 55.55%→57.24%(YoY, FY26)로 상향되었고 EPS 상향 16건·매출 상향 13건, 하향 0건으로 집계 | 2026-07-14 | Seeking Alpha · "Arista, Celestica, Extreme, Lumentum in focus as UBS previews data center demand" · [P3] |
| CLS(Celestica) | 실적 발표 예정일 | 2026-07-28 실적 발표 예정(컨센서스 상향 흐름 속) | 2026-07-14 보도 기준 | Seeking Alpha · 상동 · [P3] |
| ANET(Arista) | 목표주가 상향 | Wells Fargo $185→$200, TD Cowen $200→$210 (7월 중순) | 확인 필요(정확 일자 N/A, 7월 중순) | Seeking Alpha 요약 인용 · [P3] |
| VRT(Vertiv) | 직전 분기 실적(참고) | 2026년 1분기 매출 YoY +30%(유기성장 +23%), 조정영업이익률 430bp 확대, 조정 잉여현금흐름 전년比 2배 이상 | 발표일 확인 필요(N/A, 1분기 실적으로 4~5월 추정) | Yahoo Finance/TradingView 요약 인용 · [P3] |
| VRT(Vertiv) | M&A | ThermoKey S.p.A.(열교환 기술 업체) 인수 완료 발표 | 확인 필요(N/A, 정확일자 미확인) | Yahoo Finance/TradingView 요약 인용 · [P3] |
| APLD(Applied Digital) | 데이터센터 인프라 확장 | 모듈형 전력 설계 및 액체냉각 인프라를 포함한 전력·냉각 스택으로 사업 확장 중이라는 보도(구체 일자 미확인) | 확인 필요(N/A) | TradingView/Yahoo Finance 요약 인용 · [P3] |
| SMCI(Super Micro) | 주가 흐름(참고) | 연초 대비 주가 +4% | 확인 필요(N/A, 기준일 불명) | TradingView 요약 인용 · [P3] |
| HBM/DRAM/NAND 스팟가, AI서버 출하량, GPU 공급, 광네트워킹 수요 | — | 금일자 구체 수치 검색으로 확인하지 못함 | N/A | N/A |

---

## [5-A] AI 인프라 — 수요 측 / 하이퍼스케일러 CAPEX (실적시즌 조건부)

Microsoft/Amazon/Alphabet/Meta의 2026년 2분기 실적은 아직 발표되지 않음(발표 예정: Alphabet 7/22, Microsoft·Meta 7/29, Amazon 7/30 — 모두 2026-07-20 이후). 따라서 아래는 "신규 변동 없음" 처리하며, 직전에 확인된 2026 연간 CAPEX 가이던스를 참고로 병기함.

| 항목 | 사실 내용(발표 수치·문구) | 전분기 대비(산술) | 출처일자 | 출처+태그 |
|---|---|---|---|---|
| Microsoft | 신규 변동 없음 — 직전 가이던스(2026 회계연도 CAPEX $1,900억, 애널리스트 평균 예상 $1,520억 상회) 유지 | 산출 불가(N/A, 분기별 수치 미확인) | 발표일 확인 필요(N/A, 직전 실적발표 시점) | IG UK · "Big Tech Q2 2026 earnings and the AI capex question" · [P3] |
| Amazon | 신규 변동 없음 — 직전 가이던스(2026년 AI 인프라 투자 약 $2,000억 수준으로 보도) 유지 | 산출 불가(N/A) | 발표일 확인 필요(N/A) | Yahoo Finance/IG UK 요약 인용 · [P3] |
| Alphabet | 신규 변동 없음 — 직전 가이던스(2026 CAPEX $50억 상향되어 최대 $1,900억까지) 유지 | 산출 불가(N/A) | 발표일 확인 필요(N/A) | IG UK · 상동 · [P3] |
| Meta | 신규 변동 없음 — 직전 가이던스(CAPEX $1,250억~$1,450억) 유지 | 산출 불가(N/A) | 발표일 확인 필요(N/A) | IG UK · 상동 · [P3] |
| 4개사 합산 | 2026년 4개사 합산 AI CAPEX 약 $7,250억(전년 약 $4,100억 대비 +77% 보도) | +77%(YoY, 보도치 그대로 인용, 자체 계산 아님) | 발표일 확인 필요(N/A) | Yahoo Finance · "Google, Microsoft, Meta, and Amazon capex spending to hit $725 billion in 2026" · [P2] |

비고: 개별 CAPEX 수치의 정확한 발표 시점(1Q26 실적발표 등)을 특정하지 못해 "출처일자"란은 N/A 처리함 — 스테이지 2에서 재확인 필요.

---

## [6] 시총 상위 10 — AI 무관 일반 이슈 (실적시즌 조건부)

| 기업 | 사실 내용 | 출처일자 | 출처+태그 |
|---|---|---|---|
| MSFT | 신규 변동 없음 — 실적 발표 예정 7/29 | — | Q2 2026 어닝 캘린더 보도 · [P3] |
| NVDA | 신규 변동 없음(AI 관련 이슈는 [5] 참고). 일반 이슈 신규 보도 미확인 | — | N/A |
| AAPL | 3Q(6월분기) 실적 발표 예정 7/30. 그 외 아이폰 가격 인상 우려([4] 참고, AI 무관 일반 이슈로 분류 가능) | 2026-07-20 | Motley Fool/Yahoo Finance · "Why Apple Stock Dropped Today" · [P2] |
| AMZN | 신규 변동 없음 — 실적 발표 예정 7/30 | — | 어닝 캘린더 보도 · [P3] |
| GOOGL | 신규 변동 없음 — 실적 발표 예정 7/22 | — | 어닝 캘린더 보도 · [P3] |
| META | 신규 변동 없음 — 실적 발표 예정 7/29 | — | 어닝 캘린더 보도 · [P3] |
| AVGO | 신규 변동 없음(AI 관련 이슈는 [5] 참고). Q3(9월) 실적발표 예정, 매출 가이던스 $294억(YoY +84%) 보도 | 확인 필요(N/A) | 검색 요약 인용 · [P3] |
| BRK(Berkshire) | 신규 변동 없음 — 관련 뉴스 검색 결과 확인되지 않음 | — | N/A |
| TSLA | 2Q 2026 실적 발표 7/22(현지시간, 장 마감 후, 콘퍼런스콜 17:30 ET) | 2026-07-15 | Tesla Oracle/Basenor · "Tesla Q2 2026 Earnings Call Set for July 22" · [P3] |
| TSM | Q2 실적 이미 발표([5] 참고, AI 반도체 관련이므로 본 표에서는 일반 이슈 없음) | — | — |

---

## [7] 기관·대형 자금 수급 (데일리)

| 항목 | 종목 | 사실 내용 | 규모(수치) | 출처+태그 |
|---|---|---|---|---|
| ETF 순유입(월중 누적, 참고) | SOXX | 반도체 급락 이후 자금 유입, 월중 누적 순유입 | $61.3억(월중 누적), 단일일 $54.3억 유입 보도(7/8) | ETF.com · "Semiconductor ETFs Roar Back: SOXX Pulls In $5.4 Billion in a Single Day" · [P3] |
| ETF 순유입(월중 누적, 참고) | SMH | 반도체 급락(월중 -15.2%)에도 순유입 지속 | 월중 $20.6억 유입 | 검색 요약(ETF.com 계열) · [P3] |
| ETF 순유출(주간, 참고) | QQQ | 7/10 종료 주간 기준 최대 규모 환매 | $80억 순유출 | ETF.com · "Investors Buy the Semiconductor Dip in $40 Billion Flows Week" · [P3] |
| 옵션/블록트레이드 | NVDA/AVGO 등 | 7/20 당일 특정 이상거래(unusual options activity) 구체 내역 검색으로 확인하지 못함 | N/A | N/A |

비고: 위 ETF 자금 수급 수치는 7/20 당일 단독 수치가 아니라 월중·주간 누적치이며, 7/20 당일 단독 유출입 수치는 검색으로 확인하지 못함(N/A) — 참고용으로만 병기.

---

## [7-A] Insider Trading SEC Form 4

| 기업 | 내부자 | 직책 | 매수/매도 | 거래유형 | 규모 | 거래일 | 출처 |
|---|---|---|---|---|---|---|---|
| CRDO(Credo) | Lam Yat Tung | COO | 매도 | 10b5-1 플랜(Cheng Huang Family Trust, 2026-04-15 채택) | 55,998주, 총 $1,260만 | 2026-07-15 | Motley Fool · "Credo Technology COO Sells 55,998 Shares for $12.6 Million" · [P2] |
| CRDO(Credo) | Clyde Hosein | 이사(Director) | 매도 | 시장매도(공시상 유형 상세 미확인) | 3,451주, 주당 $262.3250 | 2026-07-01 | StockTitan · "Credo director sells 3,451 company shares" · [P3] |
| AVGO(Broadcom) | Mark David Brazeal | Chief Legal and Corporate Affairs Officer | 매도 | 공시상 거래유형 상세 미확인 | 25,000주, 총 $9,479,700 | 2026-07-08 | MarketScreener · "Broadcom Insider Sold Shares Worth $9,479,700" · [P3] |

비고: NVDA/VRT/APLD/CLS/SMCI에 대한 신규 Form 4 공시는 검색으로 확인되지 않음.

---

## [8] 향후 14일 주요 일정 (2026-07-21 ~ 2026-08-04)

### 경제 일정

| 날짜 | 시각(ET·KST) | 이벤트 | 컨센서스 | 이전치 | 출처 |
|---|---|---|---|---|---|
| 2026-07-23(목) | 확인 필요(N/A)·확인 필요(N/A) | 신규 실업수당청구건수(주간) | N/A | 직전(7/11 종료주) 20.8만 건 | dshort/Advisor Perspectives · [P3] |
| 2026-07-24(금) | 10:00 ET·23:00 KST | 신규주택판매(New Residential Sales) | N/A | N/A | Census Bureau 발표 일정 · [P1] |
| 2026-07-27(월) | 08:30 ET·21:30 KST | 내구재수주 선행발표(Advance durable goods, 6월분) | N/A | N/A | Census Bureau 발표 일정 · [P1] |
| 2026-07-28~29 | 14:00 ET(29일)·익일 03:00 KST | FOMC 회의 및 금리 결정 발표 | 동결 우세(FedWatch 86.7%, 7/20 기준) | 3.50~3.75% 유지(6월 회의) | Federal Reserve 공식 캘린더 · [P1] |
| 2026-07-30(목) | 08:30 ET·21:30 KST | 2분기 GDP 속보치(Advance Estimate) | N/A | N/A | BEA Release Schedule · [P1] |
| 2026-07-30(목) | 08:30 ET·21:30 KST | PCE 물가지수(발표 월분 확인 필요) | N/A | N/A | 검색 스니펫(정확 대상월 상충으로 확인 필요) · [N/A] |
| 2026-08-01(토, 미국 기준 실제로는 첫 영업일) | 10:00 ET | ISM 제조업 PMI(8월 첫 영업일 발표) | N/A | N/A | ISM 공식 발표 캘린더 · [P1] |

비고: 컨센서스·이전치 수치 다수가 검색으로 확인되지 않아 N/A 처리. 7/30 PCE의 정확한 대상월(5월분 vs 6월분)은 검색 결과 상충으로 확인 필요.

### 기업 일정

| 날짜 | 기업 | 이벤트 | 컨센서스 EPS | 컨센서스 매출 | 출처 |
|---|---|---|---|---|---|
| 2026-07-21(화) | Danaher, 3M, Northrop Grumman, GM, MSCI 등 | 실적 발표 | N/A | N/A | Earnings Whispers 캘린더 · [P3] |
| 2026-07-22(수) | Alphabet(GOOGL) | 2분기 실적 발표(장 마감 후) | N/A | N/A | IG UK · [P3] |
| 2026-07-22(수) | Tesla(TSLA) | 2분기 실적 발표(장 마감 후, 콘퍼런스콜 17:30 ET) | N/A | N/A | Tesla Oracle/Basenor · [P3] |
| 2026-07-24(금) | Verizon | 2분기 실적 발표(콘퍼런스콜 08:30 ET) | N/A | N/A | Verizon Investor Calendar · [P1] |
| 2026-07-28(화) | Coca-Cola | 2분기 실적 발표(장전, 콘퍼런스콜 08:30 ET) | N/A | N/A | Coca-Cola IR 보도자료 · [P1] |
| 2026-07-28(화) | Celestica(CLS) | 실적 발표 예정 | N/A | N/A | Seeking Alpha · [P3] |
| 2026-07-29(수) | Microsoft, Meta | 2분기 실적 발표 | N/A | N/A | IG UK · [P3] |
| 2026-07-30(목) | Apple, Amazon | 실적 발표(Apple 3Q/6월분기, Amazon 2Q) | N/A | N/A | IG UK · [P3] |

비고: 컨센서스 EPS·매출은 검색으로 확인하지 못해 전부 N/A 처리(스테이지 2 진행 전 별도 확인 필요).

---

## [9] 오늘의 사실 목록 (순위 없음)

- [1] S&P500 7,443.28 마감, -0.19% · CNBC [P2]
- [1] NASDAQ 종합 25,508.07 마감, -0.05% · CNBC [P2]
- [1] Dow Jones 51,839.26 마감, -307.16pt(-0.59%), 애플 급락이 견인 · CNBC [P2]
- [1] SOX 11,950.11 마감, +2.37%(반도체주 반등) · Investing.com/Yahoo Finance [P3]
- [1] Russell 2000·VIX·ES/NQ선물·DXY 세부 수치 다수 상충/미확인으로 N/A 처리 · [N/A]
- [1] WTI·Brent·Gold 가격 보도 간 수치 상충 존재, 미-이란 군사 충돌이 공통 배경으로 거론됨 · CNBC [P2]
- [2] 신임 연준의장 케빈 워시, 7/1 신트라 포럼에서 "물가가 너무 높다" 발언 · Chase.com [P3]
- [2] 6월 FOMC, 기준금리 3.50~3.75% 동결 · Federal Reserve [P1]
- [2] 다음 FOMC 회의 7/28~29, CME FedWatch 동결 확률 86.7%(7/20 기준) · growbeansprout.com [P3]
- [3] 금일(7/20) CPI/PPI/GDP/Payrolls/실업률/신규실업수당청구/소매판매/ISM 발표 없음 · N/A
- [4] Apple 약 -2%대 하락, 실적 전 차익실현·마진 우려·가격인상 우려 복합 거론 · Motley Fool/Yahoo Finance [P2]
- [4] Oracle -4.4%, ServiceNow -4.2%, Adobe -4.0% · Benzinga [P3]
- [4] Lumentum +7.5%, Teradyne +4.6% · 검색 결과 [N/A]
- [5] AMD +3%대, MS의 AMD Helios AI 추론 솔루션 도입 발표가 계기 · Bloomberg [P2]
- [5] Broadcom(AVGO) +3.10% 마감 · TradingKey [P3]
- [5] TSMC, 2026-07-16 발표 Q2 실적에서 매출 $402억(가이던스 상회), 2026 CAPEX 가이던스 $187.5억~$200억으로 상향 · SEC Form 6-K [P1]
- [5] Credo, Celestica, Arista 등 UBS의 데이터센터 수요 프리뷰에서 긍정적으로 거론(7/14) · Seeking Alpha [P3]
- [5-A] MSFT/AMZN/GOOGL/META 2분기 실적 전부 7/20 이후 발표 예정(7/22~7/30), 금일 신규 CAPEX 변동 없음 · IG UK [P3]
- [6] Tesla 2분기 실적 7/22 발표 예정 · Tesla Oracle [P3]
- [7] SOXX 월중 누적 순유입 약 $61.3억, QQQ 7/10 종료 주간 $80억 순유출 · ETF.com [P3]
- [7-A] Credo COO Lam Yat Tung, 7/15 10b5-1 플랜에 따라 55,998주(약 $1,260만) 매도 · Motley Fool [P2]
- [7-A] Broadcom Chief Legal Officer Mark David Brazeal, 7/8 25,000주(약 $948만) 매도 · MarketScreener [P3]
- [8] FOMC 회의 7/28~29, 금리 결정 발표 7/29 14:00 ET · Federal Reserve [P1]
- [8] Alphabet 실적 7/22, Microsoft·Meta 7/29, Apple·Amazon 7/30 발표 예정 · IG UK [P3]
- [8] 2분기 GDP 속보치 7/30 08:30 ET 발표 예정 · BEA [P1]
