# 미국 시장 데일리 수집 결과 (Collect)
# 기준일: 2026-07-15 (수) · 미국 정규장 종가 기준(2026-07-14 화요일 종가) · 실행모드: 데일리 코어([1][2][4][5][7][9]) + 조건부([3] 지표발표일(CPI 발표됨·PPI 예정)·[6] 신규이슈 있음·[8] 일정 갱신)

# 생성시각(KST): 2026-07-15 07:11

> 본 문서는 순수 사실 수집(Collect) 결과입니다. 점수·순위·전망·해석은 포함하지 않았습니다(→Analysis 단계 소관).
> 검증 태그: [P1] 1차(Fed·Treasury·BLS·BEA·SEC·기업IR) · [P2] Reuters·Bloomberg·CNBC·WSJ · [P3] 기타 신뢰매체 · [N/A] 확인불가

---

## [1] 미국 주요 지수 + 리스크 지표 〔데일리〕

### 지수 (2026-07-14 화 정규장 종가)

| 항목 | 종가/수치 | 등락률 | (보도된) 원인 | 출처+태그 |
|------|-----------|--------|----------------|-----------|
| S&P 500 | 7,543.59 | +0.38% | 6월 CPI가 예상보다 둔화(헤드라인 YoY 3.5%, 컨센서스 3.8%)되며 반도체주가 상승 견인 | Yahoo Finance Markets · "Stock market today: Dow, S&P 500, Nasdaq rise as Fed rate-hike bets ease, chip stocks rally" [P2] |
| NASDAQ Composite | 26,107.01 | +0.9% | 상동(반도체·기술주 강세) | Yahoo Finance(상동) [P2] |
| Dow Jones | 52,508.27 (+9.63pt) | +0.02% | IBM 실적 경고(-24%)가 지수 상단을 억누른 반면, Goldman Sachs(+8.46%)·JPMorgan(+2%) 등 은행 실적 호조가 상쇄 | Fool.com · "Goldman Sachs Saves the Dow From IBM's Worst Day in 39 Years" [P2] |
| Russell 2000 | 2,981.18 (-11.36pt) | -0.38% | N/A — 당일 개별 원인 보도 미확인 | GuruFocus/시장 데이터 종합 [P3, 원인 N/A] |
| SOX(필라델피아 반도체지수) | N/A — 07-14 정확한 종가 수치 확인 실패 | N/A(단, 대리지표로 SOXX ETF +3%대, SMH ETF +2.5% 상승 보도) | 전일(07-13) 반도체 급락(-4.8%대)에 대한 반등으로 보도되었으나 SOX 지수 자체의 07-14 종가는 검색으로 교차검증하지 못함 | Yahoo Finance/CNBC 종합 [P3, 확인불가] |

### 선물 (2026-07-15 수 오전 KST, 미국 정규장 개장 전)

| 항목 | 동향 | 출처+태그 |
|------|------|-----------|
| ES(S&P500 선물) | 7,546.00 (-0.22%) | 시장 데이터 종합 [P3] |
| NQ(나스닥100 선물) | 29,526.50 (+0.17%) | Benzinga · "Stock Market Today: Dow, S&P 500, Nasdaq 100 Futures Rise on Better-Than-Expected CPI Data" [P2] |
| Dow 선물 | 52,586.00 (-0.34%) | 시장 데이터 종합 [P3] |
| 비고 | 나스닥100 선물은 반도체·AI 관련주 강세로 상승한 반면 다우·S&P500 선물은 미·이란 지정학 리스크 재부각으로 약세 혼조 | Benzinga(상동) [P2] |

### 리스크 지표 (2026-07-14 화 기준)

| 항목 | 종가/수치 | 등락률 | 출처+태그 |
|------|-----------|--------|-----------|
| VIX | 17.16 (전일 종가 기준) | N/A — 07-14 당일 등락률 확인 실패 | Barchart.com [P3, 등락률 N/A] |
| DXY(달러인덱스) | 100.677 | -0.36%(-0.363pt) | Investing.com [P3] |
| WTI 원유 | $79.56/bbl | 장중 +2% | fxleaders.com [P3] |
| Brent 원유 | $84.85/bbl | +1.86%(+1.55pt) | 시장 데이터 종합 [P3] |
| Gold(금) | $4,066.92/oz(선물) | +1.53%(+61.22pt) | Barchart.com(GCQ26) [P3] |

**보도된 배경 사실(지정학 리스크 관련, 07-11~14 누적):**
- 미국과 이란이 호르무즈 해협을 둘러싸고 3일 연속 공습·미사일 공격을 주고받음. 이란은 쿠웨이트·바레인·요르단·오만·카타르 내 美 군사기지를 드론으로 공격했다고 자국 관영매체를 통해 보도. UAE는 자국 유조선 2척이 오만 해역에서 이란 순항미사일에 피격됐으며 인도 국적 선원 1명 사망·8명 부상이라고 발표
- 美 중부사령부(CENTCOM)는 07-13(월) 20:45 GMT부로 이란에 대한 3일차 공습을 개시했다고 발표
- 트럼프 대통령은 호르무즈 해협이 여전히 개방되어 있다고 주장하며 美 보호 대가로 해당 항로 화물에 20% 통행료를 부과하겠다고 발표. 이란 외무장관 아라그치는 이를 거부하며 "이란이 해협의 수호자"라고 반박
- Kpler(해운·원자재 데이터 분석업체)에 따르면 호르무즈 해협 통과 선박 수가 전주 대비 절반 이상 감소
| 출처: CNN(07-11) · "US strikes Iran after ship attack in Strait of Hormuz"; Al Jazeera(07-13~14) · "US, Iran exchange attacks around Strait of Hormuz"; CNBC(07-13) · "U.S. and Iran exchange strikes as Strait of Hormuz standoff escalates" [P2]

---

## [2] 금리 / 연준 〔데일리〕

| 항목 | 사실 내용(발언·수치) | 출처+태그 |
|------|----------------------|-----------|
| 미 국채 2년물(07-14) | 4.21% (+5bp) | 시장 데이터 종합 [P3] |
| 미 국채 10년물(07-14) | 4.56% (+2bp) | 시장 데이터 종합 [P3] |
| 미 국채 20년물(07-14) | 5.08% (+2bp) | 시장 데이터 종합 [P3] |
| 미 국채 30년물(07-14) | 5.06% (+1bp) | 시장 데이터 종합 [P3] |
| 10Y-2Y 스프레드(07-14) | +35bp | 산출값(10Y 4.56% - 2Y 4.21%) [P3] |
| Fed 의장 케빈 워시(Kevin Warsh), 하원 금융서비스위원회 반기 통화정책 증언(07-14, 취임(05-22) 후 첫 의회 증언) | "인플레이션을 과거의 것으로 만들겠다"고 밝히면서도 향후 정책 경로에 대한 구체적 신호는 제시하지 않음. "우리는 지속적으로 높은 인플레이션을 용인하지 않으며, 물가 안정 회복에 대한 확고한 의지를 공유한다"고 발언. 최근 발표된 6월 CPI 결과에 대해 "오늘 아침 수치를 보고 '임무 완수'라고 말하는 사람도 있을 수 있지만, 그것은 내 견해가 아니다"라고 언급. AI 투자에 대해서는 "현재 경제에서 가장 두드러진 특징"이라며 Fed가 인플레이션·고용에 미치는 영향을 "주시하고 있다"고 발언 | Axios · "Warsh stays mum on rate plans, pledges price stability"; CNN · "Latest improvement on inflation isn't 'mission accomplished,' Fed Chairman Warsh says"; U.S. News(07-14) [P2] |
| Fed 의장 워시, 상원 은행위원회 반기 통화정책 증언 | 07-15(수) 예정(정확 시각 확인 필요) | cryptobriefing.com [P3, 시각 확인 필요] |
| CME FedWatch — 차기 FOMC(2026-07-29) 확률(07-13 기준) | 동결 88% / 인상 약 12%(전일 58%에서 동결 확률 상승) | CNBC · "A July rate hike from the Fed? The odds are rising"(07-13) [P2] |
| CME FedWatch — 참고치(07-14 CPI 발표 직후 기준, 출처 간 상이) | 일부 보도는 인상 확률 약 46.5%로 인용(이란 관련 유가 급등에 따른 변동성 반영), 다른 보도는 CPI 완화로 7월 인상 확률이 35%에서 약 15%로 하락했다고 인용 | CNBC(46.5%); Motley Fool(35%→15%) [P2, 수치 간 불일치] |
| 직전 FOMC(2026-06-17) | 3.50~3.75% 동결(재확인) | Federal Reserve [P1] |
| 차기 FOMC 회의 | 2026-07-28~29 (07-29 결정 발표 예정) | 연준 캘린더 [P1] |

> ⚠️ CME FedWatch 수치는 07-13 CNBC 인용치(동결 88%)와 07-14 CPI 발표 이후 인용치(인상 46.5% 또는 15%) 간 출처·시점 불일치가 있어 병기함. 확정 수치는 CME Group 공식 페이지 교차검증 필요(→Analysis 참고).

---

## [3] 주요 경제지표 〔조건부 — 06월 CPI 발표됨, PPI 발표 예정〕

| 지표 | 발표시각(ET·KST) | 발표치 | 예상치 | 이전치 | (서프라이즈=발표치-예상치, 산술값만) | 출처 |
|------|------------------|--------|--------|--------|----------------------------------------|------|
| CPI 헤드라인 MoM(6월) | 07-14 08:30 ET/21:30 KST | -0.4% | -0.2% | +0.5%(5월) | -0.2%p | CNBC · "Consumer price index inflation report June 2026" [P2]; BLS [P1] |
| CPI 헤드라인 YoY(6월) | 상동 | 3.5% | 3.8% | 4.2%(5월) | -0.3%p | 상동 [P2/P1] |
| Core CPI MoM(6월) | 상동 | 0.0% | +0.2% | +0.2%(5월) | -0.2%p | 상동 [P2/P1] |
| Core CPI YoY(6월) | 상동 | 2.6% | 2.9% | 2.9%(5월) | -0.3%p | 상동 [P2/P1] |
| PPI(6월) | 07-15(수) 08:30 ET/21:30 KST | N/A — 본 문서 작성 시점 미발표 | N/A | N/A | N/A | BLS [P1] |
| 소매판매(6월) | 07-16(목) 08:30 ET/21:30 KST | N/A — 미발표(예정) | N/A | N/A | N/A | Census [P1] |

> CPI 하락 배경으로 에너지 가격 하락(6월 WTI 월간 -20.4%)이 보도됨. 다만 07-11 이후 이란 관련 유가 급등은 6월 CPI 산정 기간 이후 발생한 사건임(→7월 CPI에 반영될 사안, 해석 아님).

---

## [4] 특징 종목 〔데일리, 2026-07-14 세션〕

| 종목 | 티커 | 등락률 | 거래량/특이사항 | (보도된) 핵심 사실 | 출처+태그 |
|------|------|--------|--------|---------------------|-----------|
| IBM | IBM | -24%(장중, "1961년 이후 최악의 하루"로 보도) | N/A | 2분기 실적 사전경고 발표 — 매출 $172억(컨센서스 $178.5억 하회), 비GAAP EPS $2.93(컨센서스 $3.02 하회) 가이던스 제시. 소프트웨어·인프라 부문 약세가 원인으로 보도 | Fool.com · "Stock Market Today, July 14: IBM Slides After Profit Warning Weighs on Dow"; Yahoo Finance · "IBM Q2 2026 earnings warning sends stock down 17%"(수치 간 -17%~-24% 보도 혼재) [P2, 등락률 출처 간 불일치] |
| Goldman Sachs | GS | +8.46%(다른 보도는 +6.92%로 병기) | N/A | 2분기 실적 발표 — 시장 컨센서스 상회, 주식트레이딩 부문 매출 사상 최고치 기록 | Fool.com(상동) [P2, 등락률 출처 간 불일치] |
| JPMorgan Chase | JPM | +2.21%(다른 보도는 +2.06%로 병기) | N/A | 2분기 순이익 주당 $6.14(일회성 항목 제외, 컨센서스 $5.85 상회), 매출 $580.2억, 사상 최대 분기 순이익 기록 | Fool.com(상동) [P2, 등락률 출처 간 불일치] |
| Bank of America | BAC | +2% | N/A | 2분기 실적 컨센서스 상회 | 시장 데이터 종합 [P3] |
| CleanSpark | CLSK | +11% | N/A | 조지아주 소재 데이터센터 20년 임대 계약 체결, 총 계약수익 규모 $66억 | CNBC · "Stocks making the biggest moves midday: IBM, Goldman Sachs, CleanSpark, HCA Healthcare & more"(07-14) [P2] |
| HCA Healthcare | HCA | -7%대 | N/A | 2026년 연간 EPS 가이던스를 $29.10~$31.50에서 $28.70~$30.50로 하향, 매출 전망 상단도 하향 | CNBC(상동) [P2] |
| 반도체 섹터 전반(SMH/SOXX ETF 프록시) | SMH/SOXX | SMH +2.5%, SOXX +3%대 | N/A | 전일(07-13) 급락(SOXX -4.8%)에 대한 반등, CPI 완화가 반등 촉발 요인으로 보도 | Yahoo Finance Markets [P2] |

---

## [5] AI 인프라 — 공급 측 〔데일리〕

| 기업 | 뉴스 제목 | 사실 내용(무슨 일이) | 출처일자 | 출처+태그 |
|------|-----------|----------------------|----------|-----------|
| AVGO(Broadcom) | Anthropic向 커스텀 칩 수주(재확인) | Anthropic과 협업 관계에서 두 건의 커스텀 AI 칩 수주 확인($100억 규모 1건, $110억 규모 추가 1건). 단, 직전 실적발표에서 AI 가이던스가 시장 기대치($170억 추정)에 못 미쳐 발표 후 1주일간 -22% 하락한 바 있다고 보도(원발표 시점은 이전 분기) | 원발표 시점 N/A(재확인 보도 07-14 이전) | 시장 데이터 종합 [P3] |
| TSMC(TSM) | 2분기 매출 +36% YoY(재확인) | 데이터센터向 수요 강세로 매출 급증 발표. Nvidia·AMD·Apple·Broadcom 등 주요 고객사向 첨단 파운드리 물량 공급 중 | 2026-07-13(원보도) | 24/7 Wall St. · "TSMC Sales Jump 36% as Memory Stocks Plunge" [P3] |
| NVDA | 개별 신규 뉴스 없음(섹터 동반 반등) | 2026-05-20 발표 1분기(FY2027) 실적 — 비GAAP EPS $1.87(컨센서스 $1.77 상회), 매출 $816.1억(YoY +85.2%) — 신규 변동 없음, 직전 실적 재확인 | 2026-05-20(원발표) | 시장 데이터 종합 [P1 원자료 기준] |
| AMD | 데이터센터 매출 +57% YoY(재확인) | Lisa Su CEO가 AI 인프라 수요 가속을 매출 성장의 주요 동인으로 언급 — 신규 변동 없음 | 원발표 시점 N/A | 시장 데이터 종합 [P3] |
| Arista Networks(ANET) | 1.6Tbps AI 스위치 출시(재확인) | Meta·Microsoft·Oracle向 공급을 배경으로 7060XE7 스위치 출시, BofA·KeyBanc가 목표주가를 $200로 상향 — 07-08 발표 재확인, 07-14 신규 변동 없음 | 2026-07-08(원보도) | 시장 데이터 종합 [P3] |
| Vertiv(VRT) | 말레이시아 신규 생산시설(재확인) | AI·고밀도 컴퓨팅 수요 대응 위해 조호르(Johor)에 제조시설 신설 발표(07-01), ThermoKey 인수 완료(6월, 열관리 기술 포트폴리오 확대) — 신규 변동 없음 | 2026-07-01(원보도) | Vertiv 뉴스룸 관련 종합 [P1/P3] |
| Celestica(CLS), Applied Digital(APLD), Super Micro(SMCI), Credo(CRDO) | 신규 변동 없음 | 07-14 기준 신규 개별 뉴스 검색으로 확인되지 않음 | - | N/A |

### 추가 시그널 (HBM/DRAM/NAND, AI서버·광통신)

| 항목 | 사실 내용 | 출처+태그 |
|------|-----------|-----------|
| DRAM 계약가 전망(3분기, 재확인) | 범용 DRAM 계약가 전분기 대비 +13~18% 상승 전망 | 업계 리서치 종합(TrendForce 관련) [P3] |
| NAND 계약가 전망(3분기, 재확인) | NAND Flash 계약가 전분기 대비 +10~15% 상승 전망 | 업계 리서치 종합(TrendForce 관련) [P3] |
| HBM 공급 현황 | 데이터센터가 전 세계 메모리 생산량의 약 70%를 소비하는 것으로 추산되며, HBM 웨이퍼당 매출이 일반 DDR5 대비 3~5배 높아 메모리 제조사들이 생산 능력을 HBM·고용량 DDR5로 이전 중이라고 보도 | 업계 리서치 종합 [P3] |
| 메모리 공급 전망 | 삼성전자·SK하이닉스가 AI발 메모리 공급 부족이 2027년 이후까지 지속될 수 있다고 경고했다고 보도 | 업계 리서치 종합 [P3] |

---

## [5-A] AI 인프라 — 수요 측 / 하이퍼스케일러 CAPEX 〔실적시즌 아님 — 직전 가이던스 유지〕

> MSFT·META·GOOGL·AMZN 2분기(Q2 2026) 실적은 아직 발표되지 않음(2026-04말~05월 발표된 1분기 실적상 가이던스가 최신). 07-14 기준 신규 변동 없음.

- MSFT: 신규 변동 없음 — 직전 가이던스 유지(2026 회계연도 capex $1,900억, 분석가 평균 예상치 $1,520억 상회. 이 중 $250억은 메모리·부품 가격 상승분으로 설명, 출처일자 2026-04말~05월 원발표) [P1 원자료 기준]
- GOOGL(Alphabet): 신규 변동 없음 — 직전 가이던스 유지(2026년 capex 가이던스 $5억 상향되어 최대 $1,900억, 출처일자 2026-04말~05월 원발표) [P1 원자료 기준]
- META: 신규 변동 없음 — 직전 가이던스 유지(2026년 capex $1,150억~$1,350억에서 $1,250억~$1,450억로 상향, 메모리 가격 상승이 상향 요인 중 상당 부분으로 설명, 출처일자 2026-04말~05월 원발표) [P1 원자료 기준]
- AMZN: 신규 변동 없음 — 직전 가이던스 유지(원발표 시점 상세 수치 재확인 필요, 출처일자 2026-04말~05월) [P3]

> 참고 사실(4사 합산, capex 아님): Google·Microsoft·Meta·Amazon 4사 합산 2026년 capex가 $7,250억 규모로 전년($4,100억) 대비 +77% 증가 전망으로 보도됨 | Tom's Hardware/Yahoo Finance 종합 [P3]

---

## [6] 시총 상위 10 — AI 무관 일반 이슈 〔신규 이슈 있음〕

| 기업 | 사실 내용 | 출처일자 | 출처+태그 |
|------|-----------|----------|-----------|
| AAPL | Apple이 OpenAI와 전직 Apple 직원 2명(Tang Tan, Chang Liu) 및 OpenAI 계열사 io Products를 상대로 소송 제기 — OpenAI의 첫 소비자 하드웨어 제품 개발 가속을 위해 Apple의 하드웨어 영업비밀을 조직적으로 탈취했다는 주장. Tang Tan은 前 Apple 부사장으로 현재 OpenAI Chief Hardware Officer 재직 중이라고 보도 | 2026-07-13 | Washington Post · "Apple sues OpenAI, alleging the AI company stole trade secrets" [P2] |
| AAPL | Epic Games와의 App Store 수수료 관련 항소심(연방대법원이 법정모독 판결 심리 중) 및 사파리 개인정보 관련 집단소송(06-24 제기, 핑거프린팅 방지 실패 주장) 계속 진행 중 | 2026-06-24(집단소송 제기일) | 시장 데이터 종합 [P3] |
| GOOGL(Alphabet) | EU 최고재판소가 알파벳에 대한 수십억 유로 규모의 반독점 과징금을 확정 판결 | 시점 확인 필요 | 시장 데이터 종합 [P3, 날짜 확인 필요] |
| META | 페이스북·인스타그램의 "중독성 설계" 관련 소송에서 연방판사가 소송 상당 부분의 진행을 허용하는 결정 | 시점 확인 필요 | 시장 데이터 종합 [P3, 날짜 확인 필요] |

---

## [7] 기관·대형 자금 수급 〔데일리〕

| 항목 | 종목/ETF | 사실 내용 | 규모(수치) | 출처+태그 |
|------|------|-----------|------------|-----------|
| ETF 자금흐름(직전 확인분, 07-08) | SOXX(iShares Semiconductor) | 단일 세션 순유입(가장 최근 확인 가능한 수치, 07-09~14 신규 개별 수치 확인 안됨) | $54.3억(1일, 07-08) | ETF.com [P3, 날짜 07-08로 07-14 대비 stale] |
| ETF 자금흐름(직전 확인분, 07-08) | SMH(VanEck Semiconductor) | 동일 세션 순유입 | $5.52억(1일, 07-08) | ETF.com [P3, 날짜 07-08로 stale] |
| 반도체 섹터 옵션 | 개별 종목(구체 티커 N/A) | 07-13 세션에서 SOXX -2%, Intel -2.5%대, AMD -2%대 하락 후 07-14 반등 — 옵션시장 이상거래 관련 07-14 구체 수치는 검색으로 확인 못함 | N/A | 시장 데이터 종합 [P3] |
| QQQ(Invesco QQQ) 자금흐름 | QQQ | 07-14 개별 세션 수치 확인 못함(N/A) | N/A | - |
| 07-09~14 SOXX·SMH·QQQ 개별 세션 신규 수치 | - | N/A — 검색으로 확인하지 못함 | - | - |

---

## [7-A] Insider Trading (SEC Form 4) 〔조건부 — 신규공시 확인〕

**N/A — Form 4 신규 공시 없음.** NVDA·AVGO·CRDO·CLS·APLD·VRT·SMCI 대상으로 2026-07-08 이후 07-14까지 신규 Form 4 매수/매도 공시를 검색으로 확인하지 못함(직전 문서에서 확인된 AVGO(07-08)·CRDO(07-01)·SMCI(07-01) 건이 가장 최근 확인 가능한 공시).

---

## [8] 향후 14일 주요 일정 〔갱신 — 2026-07-15 ~ 07-29〕

### 경제 일정

| 날짜 | 시각(ET·KST) | 이벤트 | 컨센서스 | 이전치 | 출처+태그 |
|------|--------------|--------|----------|--------|------|
| 07-15(수) | 08:30 ET/21:30 KST | PPI(6월) | N/A | N/A | BLS [P1] |
| 07-15(수) | 시각 확인 필요 | Fed 워시 의장, 상원 은행위원회 반기 통화정책 증언 | - | - | cryptobriefing.com [P3, 시각 확인 필요] |
| 07-16(목) | 08:30 ET/21:30 KST | 소매판매(6월) | N/A | N/A | Census [P1] |
| 07-18(토) | 08:30 ET/21:30 KST | 신규 실업수당 청구건수(주간) | N/A | N/A | DOL [P1] |
| 07-28~29 | 07-29 결정 발표 예정 | FOMC 금리결정 | - | - | 연준 [P1] |

### 기업 일정

| 날짜 | 기업 | 이벤트 | 컨센서스 EPS | 컨센서스 매출 | 출처+태그 |
|------|------|--------|--------------|---------------|------|
| 07-15(수) | Morgan Stanley, BlackRock, Bank of New York Mellon, PNC | Q2 2026 실적 발표 | N/A | N/A | 시장 데이터 종합 [P3] |
| 07-16(목) | Netflix | Q2 2026 실적 발표(장마감 후) | N/A | N/A | 시장 데이터 종합 [P3] |
| 07-22(수) | Tesla | Q2 2026 실적 발표(장마감 후, 17:30 ET 웹캐스트) | N/A | N/A | Tesla IR 관련 종합 [P1 원자료 기준] |
| 07-22~23 | AMD | Advancing AI 2026 컨퍼런스, Zen 6 EPYC(코드네임 Venice) 서버 CPU 공개 예정(재확인) | - | - | 시장 데이터 종합 [P3] |
| 07-29(수, 잠정) | Microsoft, Meta | Q2 2026 실적 발표 예정(잠정, 재확인 필요) | N/A | N/A | 시장 데이터 종합 [P3, 날짜 확인 필요] |

---

## [9] 오늘의 사실 목록 (순위 없음) 〔데일리〕

```
[1] S&P500 7,543.59(+0.38%), NASDAQ 26,107.01(+0.9%), Dow 52,508.27(+0.02%)(07-14 종가) — CPI 둔화·반도체주 상승 견인 · Yahoo Finance[P2]
[1] Russell2000 2,981.18(-0.38%)(07-14 종가), SOX 07-14 종가 확인 실패(N/A, SOXX ETF 대리지표 +3%대) · GuruFocus/Yahoo Finance[P3]
[1] DXY 100.677(-0.36%), WTI $79.56(+2%), Brent $84.85(+1.86%), Gold $4,066.92(+1.53%)(07-14) · Investing.com/Barchart[P3]
[1] 美-이란 호르무즈 해협 무력충돌 3일째 지속, 트럼프 대통령 통행료 20% 부과 발표·이란은 "해협의 수호자" 주장하며 반박 · CNN/Al Jazeera/CNBC[P2]
[2] Fed 워시 의장, 취임 후 첫 하원 반기 통화정책 증언(07-14) — 인플레이션 "임무 완수 아니다" 발언, 향후 정책경로 신호 제시 안함, AI 투자를 "경제의 가장 두드러진 특징"으로 언급 · Axios/CNN[P2]
[2] 미 국채 2년물 4.21%(+5bp), 10년물 4.56%(+2bp), 10Y-2Y +35bp(07-14) · 시장데이터 종합[P3]
[2] CME FedWatch 차기 FOMC(07-29) 확률 — 07-13 기준 동결 88%/인상 12%, 07-14 CPI 후 인용치는 출처 간 상이(인상 46.5% 또는 15%) · CNBC/Motley Fool[P2, 수치 불일치]
[3] 6월 CPI 헤드라인 YoY 3.5%(예상 3.8%, 이전 4.2%), Core CPI YoY 2.6%(예상 2.9%, 이전 2.9%) — 컨센서스 하회 · CNBC/BLS[P2/P1]
[3] PPI(6월) 07-15 08:30 ET 발표 예정, 본 문서 작성 시점 미발표 · BLS[P1]
[4] IBM 장중 -24%(1961년 이후 최악의 하루), 2분기 매출·EPS 사전경고 컨센서스 하회 · Fool.com[P2]
[4] Goldman Sachs +8.46%, JPMorgan +2.21%, Bank of America +2% — 2분기 실적 컨센서스 상회, 은행 실적시즌 개막 · Fool.com[P2]
[4] CleanSpark +11%, 조지아주 데이터센터 20년 임대계약($66억 규모) 체결 · CNBC[P2]
[4] HCA Healthcare -7%대, 2026년 EPS 가이던스 하향 · CNBC[P2]
[5] TSMC 2분기 매출 +36% YoY, 데이터센터向 수요 강세(07-13 원보도 재확인) · 24/7 Wall St.[P3]
[5] AVGO, Anthropic向 커스텀 AI칩 수주 2건($100억+$110억) 재확인 · 시장데이터 종합[P3]
[5] DRAM·NAND 3분기 계약가 각각 +13~18%/+10~15% 상승 전망(재확인), HBM發 메모리 생산능력 이전 지속 · 업계 리서치 종합[P3]
[5-A] MSFT/GOOGL/META/AMZN capex 가이던스 신규 변동 없음(직전 가이던스 유지, 4사 합산 2026년 $7,250억 전망) · 각사 IR 관련[P1/P3]
[6] Apple, OpenAI 및 전직 임원 2명·io Products 상대로 영업비밀 탈취 소송 제기(07-13) · Washington Post[P2]
[7] SOXX·SMH ETF 자금흐름 최신 확인 가능 수치는 07-08 기준(각각 $54.3억/$5.52억 순유입)으로 07-14 대비 stale · ETF.com[P3]
[7-A] NVDA·AVGO·CRDO·CLS·APLD·VRT·SMCI 대상 07-08 이후 신규 Form 4 공시 없음(N/A) · 검색 확인[N/A]
[8] Fed 워시 의장 상원 은행위 증언 07-15(수) 예정(정확 시각 확인 필요), PPI(6월) 07-15 08:30 ET 발표 예정 · BLS/cryptobriefing.com[P1/P3]
[8] Netflix 07-16, Tesla 07-22, AMD Advancing AI 07-22~23 컨퍼런스 예정 · 시장데이터 종합[P3]
```

---

## 자가 점검 결과
0. 방화벽 점검: 의견·전망·★·AI영향도·밸류체인·순위·다중추론 없음 — 확인 완료
1. 날짜: 웹 검색으로 2026-07-15(수) 확정, 미국 정규장 기준일은 직전 거래일인 2026-07-14(화) — 완료
2. 모든 수치·뉴스에 출처+검증 태그 부여 — 완료(일부 N/A 명시)
3. 확인 못한 칸 N/A 처리 — 완료(SOX 07-14 종가, VIX 07-14 등락률, QQQ 자금흐름, GOOGL/META 소송 날짜, AMZN capex 상세 등)
4. 원인·영향은 보도된 사실만 기재 — 완료
5. 동일 사건 대표 출처 통합 — 완료(단, 등락률 등 수치가 출처 간 상이한 경우 병기하고 불일치 명시)
6. [5]공급/[5-A]수요/[6]일반 분류 — 확인 완료
7. CAPEX·가이던스 출처일자 표기 — 완료(4사 모두 2026-04말~05월 원발표 기준으로 명시, 07-14 기준 stale 상태 확인됨)
8. Form 4 신규공시 여부 확인 — 완료(신규공시 없음, N/A)
9. [9]는 랭킹이 아닌 사실 나열 — 완료

## 리서치 한계 (다음 단계 참고)
- SOX 지수의 2026-07-14 정확한 종가·등락률을 검색으로 확인하지 못함. 대리지표(SOXX/SMH ETF 상승률)로 방향성만 파악 가능. Analysis 단계에서 반도체 섹터 판단 시 SOX 수치 공백을 감안할 것.
- VIX의 07-14 당일 종가·등락률을 확인하지 못함(검색 결과가 07-13 종가 17.16을 "전일 종가"로 반복 제시).
- CME FedWatch 차기 FOMC 확률이 출처 간 심하게 불일치함(07-13 CNBC "동결 88%" vs 07-14 CPI 이후 인용치가 매체별로 "인상 46.5%" 또는 "인상 15%"로 제각각). 원 데이터 소스(CME Group 공식 페이지)를 직접 열람하지 못해 확정하지 못함 — Analysis 단계에서 최신치 우선 참고 시 주의 필요.
- IBM/Goldman/JPMorgan의 07-14 등락률이 출처(Fool.com 등)마다 소수점 단위로 병기된 두 수치가 혼재하여(-17%~-24%, +8.46%~+6.92%, +2.21%~+2.06%) 확정하지 못하고 병기함.
- ETF(SOXX/SMH/QQQ) 07-09~14 개별 세션 순유입/유출 수치를 검색으로 확인하지 못함(가장 최근 확인 가능한 수치는 07-08 기준으로 6일 이상 경과, stale 데이터).
- WebFetch(URL 원문 열람) 도구 사용 권한이 이번 세션에서 부여되지 않아(승인 대기 중 미승인), 전 항목을 WebSearch 스니펫에 의존했음. CNBC 등 주요 라이브블로그 원문 전체를 열람하지 못해 일부 세부사실(구체 시각, 추가 종목명 등)이 누락됐을 가능성 있음.
- GOOGL 반독점 과징금 확정판결, META 소송 진행 허용 결정의 정확한 날짜를 확인하지 못함(사건 발생 사실 자체만 확인).
- AMZN의 2026년 capex 구체 가이던스 수치를 재확인하지 못함(MSFT/GOOGL/META 대비 상세치 미확보).
- [7-A] Form 4의 경우 "신규공시 없음"으로 처리했으나, 이는 검색 결과 미노출을 근거로 한 것이며 SEC EDGAR 원문 직접 조회는 수행하지 못했음(WebFetch 권한 제한).
