# 미국 시장 데일리 수집 결과 (Collect)
# 기준일: 2026-07-08 (수) · 미국 정규장 종가 기준 · 실행모드: 데일리
# 생성시각(KST): 2026-07-09 10:30

---

## [1] 미국 주요 지수 + 리스크 지표

| 항목 | 종가/수치 | 등락률 | (보도된) 원인 | 출처+태그 |
|------|-----------|--------|----------------|-----------|
| S&P 500 | 7,482.71 | -0.28% | 트럼프 대통령, 이란과의 휴전이 "끝났다(over)"고 발언 → 리스크 회피 | Yahoo Finance · "Stock market today: Nasdaq rises, Dow and S&P 500 retreat..." · P2 |
| NASDAQ Composite | 25,870.65 | +0.20% | 지수 전반 하락 속에서도 나스닥은 반등 마감(반도체 개별종목 혼조 속 AI 밸류에이션 저가매수 유입 보도) | Yahoo Finance · 위 동일 기사 · P2 |
| Dow Jones | 52,348.39 (-576.76pt) | -1.09% | 이란 휴전 종료 발언 이후 유가 급등 → 항공·크루즈 등 경기민감주 매도, 장중 한때 -1.51%(52,126.81)까지 낙폭 확대 | Yahoo Finance · Kiplinger · "Dow Falls 577 Points After Hormuz Ceasefire Fails" · P2 |
| Russell 2000 | N/A | N/A | 7/8 종가 검색으로 확인 불가(직전 확인 가능 수치: 7/6 3,018.68 부근) | N/A ※ 확인 필요 |
| SOX (PHLX 반도체) | N/A | N/A | 7/8 종가 검색으로 확인 불가(직전 확인 가능 수치: 7/6 13,104.26, +3.79%) | N/A ※ 확인 필요 |
| ES (S&P500 선물) | 7,544.00 부근 | N/A | 이란 관련 헤드라인에 따라 등락 반복 | Investing.com · P3 ※ 정확한 7/9 KST 시각 기준 미확인 |
| NQ (나스닥100 선물) | 29,400.50 부근 | N/A | 반도체주 낙폭 확대 우려로 선물 하락 압력 보도 | Investing.com · P3 ※ 정확한 7/9 KST 시각 기준 미확인 |
| VIX | 16.13 | +3.6% (일부 보도 장중 18.01 고점 언급) | 이란 휴전 종료 발언에 따른 변동성 확대 | Investing.com/CBOE 참조 기사 · P3 ※ 타 소스 장중 18.33 언급 — 교차검증 필요 |
| DXY (달러 인덱스) | 101.0695 | +0.05% | 지정학 리스크 속 안전자산 수요, 대이란 공습 보도 이후 달러 강세 지속 | TradingEconomics · P3 |
| WTI (서부텍사스중질유) | 73.52 | +4.37% | 이란-이스라엘/미국 긴장 재점화, 호르무즈 해협 관련 공급 우려 | CNBC · "Treasury yields climb to 4.57% as jumping oil prices reignite inflation fears" · P2 |
| Brent (북해산원유) | 78.19 | +5.43% | 동일 원인(이란 휴전 종료 발언) | CNBC · 위 동일 기사 · P2 |
| Gold (금) | 4,087.37 | -0.45% | 달러 강세 및 안전자산 내 자금이동으로 하락 | TradingEconomics · P3 |

---

## [2] 금리 / 연준

| 항목 | 사실 내용(발언·수치) | 출처+태그 |
|------|----------------------|-----------|
| 기준금리 (Federal Funds Rate) | 3.50–3.75% 유지 (6월 16–17일 FOMC 만장일치 동결, 직전 결정 유지 중) | Fed · federalreserve.gov/newsevents/pressreleases/monetary20260617a.htm · P1 |
| FOMC 의사록(6/16–17 회의) 공개 | 7월 8일 14:00 ET 공개. "정책 성명 130단어로 이례적으로 짧았고 금리 방향에 대한 포워드가이던스 없음"이라고 보도 | Fed · federalreserve.gov · P1; TradingKey · "FOMC Minutes: Fed Shifts to Neutral Wait-and-See Stance" · P3 |
| 의사록 내용 — 위원 간 견해차 | 일부 위원은 "즉각적인 금리 인상 근거가 있다"는 의견을 냈으나 보류를 선택; 인플레이션 압력이 에너지·관세 등 외생 요인을 넘어 교통·항공료·서비스 물가 등으로 확산되고 있다고 명시 | TradingKey · 위 동일 기사 · P3 |
| 6월 SEP(점도표) 분포 | 연내 최소 1회 인상 전망 위원 9명, 동결 전망 8명, 인하 전망 1명으로 분열 (Warsh 의장 본인 전망은 미제출) | TechTimes · "Fed Minutes Due Wednesday: Nine Hawkish Dots and Warsh's Deliberate Silence" · P3 |
| 2년물 국채금리 | 4.206% (+4bp 이상) | CNBC · "Treasury yields climb to 4.57%..." · P2 |
| 10년물 국채금리 | 4.571% (+4bp 이상) | CNBC · 위 동일 기사 · P2 |
| 30년물 국채금리 | 5.069% (+2bp 이상) | CNBC · 위 동일 기사 · P2 |
| 10Y-2Y 스프레드 | +0.365%p (+36.5bp, 역전 없음) | 산술 계산 (위 2Y·10Y 수치 기반) · P2 |
| CME FedWatch — 7월 29일 FOMC 동결 확률 | 70.1% (7/8 기준) | 검색 결과(CME FedWatch 참조) · P3 |
| CME FedWatch — 9월 FOMC 인상 확률 | 68.8% (전일 62%에서 상승) | Forbes · "Fed Minutes Signal No Interest Rate Cuts Until 2027—As Renewed Iran Conflict Spikes Rate Hike Odds" · P3 |
| CME FedWatch — 12월 FOMC 인상 확률 | 85.3% | Forbes · 위 동일 기사 · P3 ※ 회의별(7월=동결 우세, 9월·12월=인상 우세) 수치로 상호 모순은 아니나, 원 소스(CME 직접) 재확인 권장 |
| 이란 사태와 인플레이션 연계 보도 | 유가 급등이 인플레이션 우려를 자극해 금리 인상 기대를 높였다고 다수 매체 보도 | CNBC, Forbes, NPR · P2/P3 |

---

## [3] 주요 경제지표 〔조건부〕

N/A — 금일(2026-07-08 ET) CPI·PPI·GDP·Payroll·ISM 등 주요 지표 발표 없음. (다음 지표: 7/14 CPI)

---

## [4] 특징 종목 (등락률 ±5% 이상)

> AI 인프라 대상 종목(NVDA·AVGO·AMD 등)은 [5]에서 별도 처리

| 종목 | 티커 | 등락률 | 거래량 | (보도된) 핵심 사실 | 출처+태그 |
|------|------|--------|--------|---------------------|-----------|
| Intel | INTC | -7.67%(일부 소스 -9.66%) | N/A | $110.68 마감(일부 소스 $110.39); 7일 연속 21% 하락. 18A 파운드리 공정 수익 유의미 양산 시점이 2026년 말~2027년으로 지연됐다는 보도, AMD가 데이터센터 매출에서 처음으로 인텔을 추월했다는 보도, BofA의 AI 버블 경고 노트 및 삼성 실적발 반도체 매도세가 복합 원인으로 보도됨 | Yahoo Finance · "Intel Corp. (INTC) Loses 9.66% on Profit-Taking" · P2; Forbes · "Semiconductor Selloff Deepens As AI Spending Fears Hit Intel" · P3 |

> ※ 그 외 개별 종목 중 ±5% 이상 확인된 케이스는 [5] Broadcom(AVGO, AI 인프라 종목) 참조. 에너지주(Diamondback·APA·Occidental 등 +1.5~3%대)·항공/크루즈주(United·Carnival·Norwegian 등 -2~3.5%대)는 ±5% 미만으로 이 표에서 제외.

---

## [5] AI 인프라 — 공급 측

| 기업 | 뉴스 제목 | 사실 내용(무슨 일이) | 출처일자 | 출처+태그 |
|------|-----------|----------------------|----------|-----------|
| Broadcom (AVGO) | "Broadcom Spikes 5% on Expanded Apple Chip Deal" | Apple이 Broadcom과의 다년 칩 공급 계약을 2031년까지 확대한다고 발표. $300억 규모, 미국산 칩 150억 개 이상 생산 목표, 콜로라도 Fort Collins 공장에 $15억 규모 증설 포함. 발표 후 AVGO 주가 +5% $390 마감 | 2026-07-08 | CNBC · "Apple commits $30 billion to Broadcom for U.S. chipmaking push" · P2; Yahoo Finance/24·7 Wall St. · P2 |
| NVIDIA (NVDA) | "NVDA Moved Up by 3.47% on Jul 8" | 베이징이 Alibaba·ByteDance·DeepSeek 등 자국 AI 기업에 NVIDIA H200 칩의 제한적 구매를 허용할 계획이라는 The Information 보도가 나오며 장중 반등, 3.47% 상승 마감. 전일(7/7) 종가는 $196.93(+0.706%)으로 보도됨 | 2026-07-08 | Bloomberg · "China to Let AI Firms Buy Nvidia H200 Chips, Information Says" · P2; TradingKey · "NVIDIA Corp Stock (NVDA) Moved Up by 3.47% on Jul 8" · P3 |
| 베이징 — NVIDIA H200 수입 허용 방침 | "China plans to let top AI firms buy limited amount of Nvidia H200 chips" | H200은 AI 학습(training) 용도로만 허용, 추론(inference)은 자국산 칩 우선 사용 요구 방침. 총 승인 물량은 20만 개 미만으로, 기업들이 당초 요청한 물량의 절반 이하로 제한될 전망. 기업별로 필요 수량·용도를 신청해야 승인 | 2026-07-08 | Reuters(Investing.com 재인용) · "China plans to let top AI firms buy limited amount of Nvidia H200 chips, the Information reports" · P2 |
| Intel (INTC) | 반도체 매도세 지속 | -7.67%~-9.66% (상세는 [4] 참조); 18A 공정 수익성 있는 양산 지연 보도, AMD에 데이터센터 매출 역전 허용 보도 | 2026-07-08 | Yahoo Finance · P2 |
| AMD | 개별 뉴스 없이 소폭 하락 | -1% $513 마감(특별한 부정적 뉴스 없이 소폭 하락으로 보도) | 2026-07-08 | 24/7 Wall St. · "Broadcom Spikes 5% on Expanded Apple Chip Deal; Intel and AMD Drift Lower" · P2 |
| TSM (Taiwan Semi) | 애널리스트 목표주가 상향 | Citi가 목표주가를 NT$3,800으로 상향하고 2026년 매출 성장률 30% 이상 전망을 제시, AI 칩 수요 강세 근거로 인용. Q2 실적은 7월 16일 발표 예정 | 2026-07-08(보도일) | TradingKey · "Taiwan Semiconductor Manufacturing Co Ltd Stock (TSM) Moved Up by 4.83% on Jul 6" · P3 ※ Citi 코멘트 정확한 발표일 재확인 필요 |
| HBM/DRAM/NAND 현물가, AI서버 출하 | N/A | 금일 신규 공시 데이터 확인 불가 | N/A | N/A |

---

## [5-A] AI 인프라 — 수요 측 / 하이퍼스케일러 CAPEX 〔실적시즌 외〕

실적시즌 외 — 직전 가이던스 유지. Microsoft·Amazon·Alphabet·Meta의 2026년 Q2(4~6월) 실적 발표일은 7/8 기준 아직 공식 발표되지 않음(직전 Q1은 4/29~4/30 발표, 통상 관례상 Q2는 7월말~8월초 예상되나 확정 아님).

| 항목 | 예정 실적 발표일 | 출처일자 | 출처+태그 |
|------|----------------|----------|-----------|
| Microsoft (MSFT) | 미정(공식 발표 전, 7월말~8월초 예상) | 2026-07-08 확인 시점 | 확인 필요 · P3 |
| Amazon (AMZN) | 미정(공식 발표 전, 7월말~8월초 예상) | 2026-07-08 확인 시점 | 확인 필요 · P3 |
| Alphabet (GOOGL) | 미정(공식 발표 전, 7월말~8월초 예상) | 2026-07-08 확인 시점 | 확인 필요 · P3 |
| Meta (META) | 미정(공식 발표 전, 7월말~8월초 예상) | 2026-07-08 확인 시점 | 확인 필요 · P3 |

---

## [6] 시총 상위 10 — AI 무관 일반 이슈

| 기업 | 사실 내용 | 출처일자 | 출처+태그 |
|------|-----------|----------|-----------|
| Apple (AAPL) | Broadcom과 $300억 규모 칩 공급 계약을 2031년까지 확대 발표(AI 반도체 공급망 성격이 강해 [5]에서 주로 다룸; Apple 측 CAPEX/제조 투자 이슈로서 기재) | 2026-07-08 | CNBC · "Apple commits $30 billion to Broadcom for U.S. chipmaking push" · P2 |
| Tesla (TSLA) | 신규 모델 "Model Y L"(3열 SUV) 출시 보도, Q2 실적 발표는 7월 22일 예정 | 2026-07-08 이전 보도 | 확인 필요 · P3 |
| MSFT / NVDA / AMZN / GOOGL / META / BRK | 금일 신규 일반(AI 무관) 이슈 확인 불가 | — | N/A |

---

## [7] 기관·대형 자금 수급

| 항목 | 종목/ETF | 사실 내용 | 규모(수치) | 출처+태그 |
|------|----------|-----------|------------|-----------|
| ETF 일일 자금 흐름(가장 최근 확인 가능 일자: 7/6) | SMH (VanEck 반도체) | 순유입 | +$1.8B (2026-07-06 단일일 기준) | ETF.com · "Daily ETF Flows: SMH Pulls In $1.8B" · P3 ※ 7/8 단일일 수치는 미확인 |
| ETF 자금 흐름 (최근 5일 기준, 정확한 일자 불명) | SMH (VanEck 반도체) | 순유입 | +$104.53M(5일 기준) / 1개월 기준 -$355.3M | ETF.com 참조 · P3 ※ 위 7/6 단일일 수치와 별개 지표 — 교차검증 필요 |
| ETF 자금 흐름 (최근 5일 기준, 정확한 일자 불명) | SOXX (iShares 반도체) | 순유출 | -$490.68M(5일 기준) / 1개월 기준 +$3.64B | ETF.com 참조 · P3 ※ 7/8 단일일 수치 아님 — 확인 필요 |
| QQQ 자금 흐름 | QQQ | 금일 확인 가능한 수치 없음 | — | N/A |
| 블록딜/옵션 이상거래 | N/A | 금일 확인된 건 없음 | — | N/A |

---

## [7-A] Insider Trading (SEC Form 4) 〔조건부〕

N/A — 2026-07-08 기준 NVDA·AVGO·CRDO·CLS·APLD·VRT·SMCI 신규 Form 4 공시 확인 불가.

> 참고(신규 아님): Celestica(CLS) CEO Robert Mionis 관련 신탁이 6월 17일 10b5-1 사전계획에 따라 18,176주 매도($377.93–$392.205) — 6월 공시분, 7/8 신규 아님.
> 참고(신규 아님): NVIDIA 이사 Mark A. Stevens 관련 신탁이 6월 18일 장내에서 총 885,000주 매도(가중평균 $209~$210) — 6월 공시분, 7/8 신규 아님.

---

## [8] 향후 14일 주요 일정

**경제 일정**

| 날짜 | 시각(ET / KST) | 이벤트 | 컨센서스 | 이전치 | 출처 |
|------|----------------|--------|----------|--------|------|
| 2026-07-14 (화) | 08:30 ET / 21:30 KST | CPI (6월) 발표 | 확인 필요 | 확인 필요 | BLS 일정 · P1 |
| 2026-07-15 (수) | 08:30 ET | PPI (6월) 발표 | 확인 필요 | 확인 필요 | BLS 일정 · P1 |
| 2026-07-16 (목) | 08:30 ET | 소매판매(Advance Retail Sales, 6월) 발표 | 확인 필요 | 확인 필요 | Census Bureau 일정 · P1 |
| 2026-07-28~29 (화~수) | — / 14:00 ET(7/29) | FOMC 회의 및 금리 결정 + Warsh 기자회견 | 7/29 회의 동결 확률 70.1%(7/8 CME FedWatch 기준); 9월·12월은 인상 확률 우세(68.8%/85.3%) 보도 | 3.50–3.75% | Fed Calendar · P1; CME FedWatch/Forbes 참조 · P3 |

> ※ 상기 외 Fed 위원 연설 일정(Bowman·Waller 등) — 직전 연설은 Waller 7/6(로마, 통화정책 관련), Bowman 7/7(AI 관련 감독 원칙) 기 종료. 7/9 이후 신규 예정 연설 구체 일정 미확인.

**기업 일정**

| 날짜 | 기업 | 이벤트 | 컨센서스 EPS | 컨센서스 매출 | 출처 |
|------|------|--------|--------------|---------------|------|
| 2026-07-14 (화) | JPMorgan, Bank of America, Citigroup, Wells Fargo | 2분기 실적 발표 (장 개장 전, 은행 실적시즌 개막) | JPM $5.49 · BofA $1.12(그 외 확인 필요) | JPM $48.7B · BofA $30.7B(그 외 확인 필요) | IG/Yahoo Finance(Zacks Earnings Preview) · P3 |
| 2026-07-16 (목) | Taiwan Semiconductor (TSM) | Q2 실적 발표 | 확인 필요 | 확인 필요 | TradingKey 참조 · P3 |
| 2026-07-22 (수) | Tesla (TSLA) | Q2 실적 발표(장 마감 후, 17:30 EDT 웹캐스트) | 확인 필요 | 확인 필요 | Tesla IR 참조 · P1/P3 |
| 미정 | Alphabet(GOOGL) / Microsoft(MSFT) / Meta(META) / Apple(AAPL) / Amazon(AMZN) | Q2 실적 발표 — 7/8 기준 공식 일정 미발표(통상 7월말~8월초 예상, 직전 분기는 4/29~4/30 발표) | 확인 필요 | 확인 필요 | 확인 필요 · P3 |

---

## [9] 오늘의 사실 목록 (순위 없음)

```
[1] S&P500 7,482.71(-0.28%), NASDAQ 25,870.65(+0.20%), Dow 52,348.39(-1.09%, -576.76pt) 마감 · Yahoo Finance P2
[1] 트럼프, NATO 정상회의에서 "이란과의 휴전 끝났다" 발언 · Kiplinger/CNBC P2
[1] WTI $73.52(+4.37%), Brent $78.19(+5.43%) · CNBC P2
[1] VIX 16.13(+3.6%, 장중 18.01 고점 보도) · P3
[1] DXY 101.0695(+0.05%), Gold $4,087.37(-0.45%) · TradingEconomics P3
[2] FOMC 의사록(6/16-17 회의) 7/8 14:00 ET 공개, 130단어 짧은 성명·포워드가이던스 부재 · Fed P1
[2] 의사록: SEP 인상 전망 9명 vs 동결 8명 vs 인하 1명으로 분열, Warsh 본인 전망 미제출 · TechTimes P3
[2] 10년물 4.571%(+4bp), 2년물 4.206%(+4bp), 스프레드 +36.5bp · CNBC P2
[2] CME FedWatch: 7/29 FOMC 동결 확률 70.1%, 9월 인상 확률 68.8%(전일 62%↑), 12월 인상 확률 85.3% · P3
[3] 금일 주요 경제지표 발표 없음(다음: 7/14 CPI) · N/A
[4] Intel(INTC) -7.67%~-9.66% $110대 마감, 18A 지연·AMD 데이터센터 역전·BofA 버블경고 복합 원인 · Yahoo Finance/Forbes P2/P3
[5] Apple-Broadcom $300억 칩 공급계약 2031년까지 확대, AVGO +5% $390 마감 · CNBC P2
[5] 베이징, Alibaba·ByteDance·DeepSeek에 NVIDIA H200 제한적 구매 허용 방침 보도 · Bloomberg P2
[5] NVDA +3.47% 마감(전일 $196.93) · TradingKey P3
[5] TSM, Citi 목표주가 NT$3,800 상향·2026 매출성장률 30%+ 전망, Q2 실적 7/16 예정 · TradingKey P3
[6] Tesla Model Y L(3열 SUV) 출시 보도, Q2 실적 7/22 예정 · P3
[7] SMH 7/6 단일일 +$1.8B 순유입 · ETF.com P3
[8] 다음 주요 일정: 7/14 CPI·은행 실적 개막(JPM·BofA·C·WFC), 7/15 PPI, 7/16 소매판매·TSM 실적, 7/22 TSLA 실적, 7/28-29 FOMC · P1/P3
```

---

## 출력 전 자가 점검 결과

0. **방화벽**: 투자 의견·전망·★·AI영향도·밸류체인·순위·다중추론 없음 ✅
1. 날짜를 검색으로 확정 (2026-07-08 ET 미국 정규장 종가 기준, 다수 매체가 "Wednesday"로 확인; 검색 시점 KST 2026-07-09 오전) ✅
2. 모든 수치·뉴스에 출처+검증 태그 부여 ✅
3. 확인 못한 칸은 N/A 또는 "확인 필요" 처리 ✅
4. 원인은 보도된 사실만 기재, 본인 추론 없음 ✅
5. 동일 사건 대표 출처 1개 통합(나머지는 병기) ✅
6. [5]공급/[5-A]수요/[6]일반 분류 완료 ✅
7. [5-A] 실적시즌 외 — 직전 가이던스 유지 처리 ✅
8. Form 4: 7/8 신규 공시 없음(N/A), 6월 공시 2건은 참고로만 별도 표기 ✅
9. [9] 섹션순 사실 나열, 순위 없음 ✅

## 미확인 항목 (2단계 Analysis 전 재확인 권장)

- Russell 2000 · SOX 지수 7/8 종가: 검색으로 확인 불가(직전 확인 가능치: Russell 2000 ~3,018.68(7/6), SOX 13,104.26(7/6, +3.79%))
- VIX 종가: 16.13(+3.6%) vs 타 소스 언급 18.33 — 상충, 교차검증 필요
- ES/NQ 선물: 7/9 KST 기준 정확한 시각·수치 불명확
- CME FedWatch 9월(68.8%)·12월(85.3%) 인상확률과 7/29 동결확률(70.1%)이 각기 다른 회의 기준 수치임을 재확인(원 소스 CME 직접 대조 권장)
- SMH·SOXX 자금 흐름: 7/6 단일일 SMH +$1.8B는 확인했으나 SOXX·QQQ의 7/8 단일일 수치는 미확인, 5일/1개월 누적치와 혼동 주의
- MSFT·AMZN·GOOGL·META Q2 실적 발표일: 7/8 기준 공식 미발표(추정치만 존재)
- TSM Citi 목표주가 상향 코멘트의 정확한 발표일자(7/6 vs 7/8) 재확인 필요
- 은행(JPM·BofA·C·WFC) 중 Citigroup·Wells Fargo 컨센서스 EPS/매출 수치 미확인
