# 미국 시장 데일리 수집 결과 (Collect)
# 기준일: 2026-07-07 (화) · 미국 정규장 종가 기준 · 실행모드: 데일리
# 생성시각(KST): 2026-07-08 09:30

---

## [1] 미국 주요 지수 + 리스크 지표

| 항목 | 종가/수치 | 등락률 | (보도된) 원인 | 출처+태그 |
|------|-----------|--------|----------------|-----------|
| S&P 500 | 7,503.85 | -0.45% | 삼성전자 2Q 실적 발표 이후 반도체주 매도세 확산 | Yahoo Finance · "Stock Market Today July 7, 2026" · P2 |
| NASDAQ Composite | 25,818.69 | -1.16% | 반도체·AI주 하락 주도 | Yahoo Finance · "Stock Market Today July 7, 2026" · P2 |
| Dow Jones | 53,289.30 (52주 고점) | 확인 필요 | 기술주 차익실현 자금이 경기방어주 중심 다우 종목으로 로테이션 유입; "Great Rotation" 지속 보도 | HDFCSky · "Nasdaq Composite Plunges 264 Points…Dow Hits Record 53,289 Amid Chip Sell-Off" · P3 ※ 종가 수치 교차 확인 불완전 — 검증 필요 |
| Russell 2000 | ~3,015.34 | ~-0.30% | N/A — 개장 초 상승 보도 있으나 종가 미확인 | CNBC Quotes 실시간 · P3 ※ July 7 종가 확인 필요 |
| SOX (PHLX 반도체) | N/A | N/A — 장중 SMH ETF -3%+ 보도 | 삼성 실적 → 글로벌 칩 매도세 | N/A ※ July 6 종가 13,104.26 (Investing.com · P3) |
| ES (S&P500 선물, Sep26) | ~7,591.50 | +0.48% (한국 아침 선물) | N/A | Yahoo Finance E-Mini Sep26 · P3 ※ 정확한 July 8 KST 기준 미확인 |
| NQ (나스닥100 선물, Sep26) | ~29,941.00 | +1.10% (한국 아침 선물) | N/A | Yahoo Finance E-Mini Sep26 · P3 ※ 정확한 July 8 KST 기준 미확인 |
| VIX | 16.36 | +5.07% | 반도체 매도세 확산에 따른 변동성 확대 | Yahoo Finance · P3 |
| DXY (달러 인덱스) | 100.765 | +0.15% | N/A | Trading Economics · P3 |
| WTI (서부텍사스중질유) | 71.04 | +3.63% | OPEC+ 공급 동향, 달러 강세 제한 속 수요 기대 보도 | Trading Economics · P3 |
| Brent (북해산원유) | ~72.89 | +1.26% | OPEC+ 산출량 증가에도 지정학 리스크 상존 | Vantage Markets · "Brent Crude Oil Price Today: Below $72 as OPEC+ Raises Output" · Jul 6-10 2026 · P3 |
| Gold (금) | ~4,147.94 | -0.41% | 달러 강세로 이틀 연속 후퇴; 노동시장 냉각 신호로 낙폭 제한 보도 | Fortune · "Current price of gold: July 7, 2026" · P3 |

---

## [2] 금리 / 연준

| 항목 | 사실 내용(발언·수치) | 출처+태그 |
|------|----------------------|-----------|
| 기준금리 (Federal Funds Rate) | 3.50–3.75% 유지 (6월 16–17일 FOMC에서 만장일치 동결) | Fed · federalreserve.gov/newsevents/pressreleases/monetary20260617a.htm · P1 |
| Fed 의장 | Kevin Warsh (신임) | Fed · P1 |
| 2년물 국채금리 | 4.15% (+0.04 pp) | Trading Economics · FRED 참조 · P2 |
| 10년물 국채금리 | 4.495% | Trading Economics · CNBC US10Y · P2 |
| 10Y-2Y 스프레드 | +0.345% (+34.5 bps) — 역전 없음 | 산술 계산 (2Y·10Y 위 수치 기반) · N/A ※ FRED T10Y2Y 직접 미확인 |
| CME FedWatch — 7월 28–29 FOMC | 동결 확률 73.4% / 25bp 인상 확률 ~26.6% | CME FedWatch 간접 참조 (centralbank.watch) · P3 |
| Warsh 6월 기자회견 발언 | "We recognize that inflation has been running well ahead of the Fed's long-stated inflation goal of 2 percent that's been going on for more than five years." | Kiplinger · "What to Look Out for in Economic Data This Week (July 6-10)" · P3 |
| 6월 SEP(점도표) | 2026년 말 금리 중앙값, 이전보다 인상 방향으로 이동(인하 아닌 최소 1회 인상 시사) | Intellectia.ai · "Federal Reserve Interest Rate Decision July 2026" · P3 |
| FOMC 의사록 예정 | 6월 16–17일 회의 의사록, 7월 8일 오후 2:00 ET 공개 예정 | Fed Calendar · federalreserve.gov/newsevents/calendar.htm · P1 |
| Washington Times 칼럼 (July 7) | "Federal Reserve should stand pat on interest rates" — 금리 동결 촉구 의견 게재 | Washington Times · Jul 7 2026 · P3 |

---

## [3] 주요 경제지표 〔조건부〕

N/A — 금일(2026-07-07 ET) 주요 경제지표 발표 없음.

---

## [4] 특징 종목 (등락률 ±5% 이상)

> AI 인프라 대상 종목(NVDA·AVGO·AMD 등)은 [5]에서 별도 처리

| 종목 | 티커 | 등락률 | 거래량 | (보도된) 핵심 사실 | 출처+태그 |
|------|------|--------|--------|---------------------|-----------|
| Applied Materials | AMAT | -10.02% | N/A | 삼성전자 실적 발표 이후 반도체 장비주 매도세 집중; $536.96 마감 | 24/7 Wall St. · "Intel and Applied Materials Dive 10%, AMD Craters 8% as Samsung Earnings Trigger Chip Selloff" · Jul 7 2026 · P2 |
| Lam Research | LRCX | -8.57% | N/A | 동일 — 반도체 장비 업종 동반 하락 | 24/7 Wall St. · 위 동일 기사 · P2 |
| KLA Corporation | KLAC | -7.94% | N/A | 동일 — 반도체 장비 업종 동반 하락 | 24/7 Wall St. · 위 동일 기사 · P2 |
| Intel | INTC | -8.38% | N/A | 삼성 실적 → 칩 매도세 확산; $113.11 마감 | 24/7 Wall St. · 위 동일 기사 · P2 |
| Eos Energy Enterprises | EOSE | +6.7% (장 전) | N/A | Frontier Power USA와의 계약 체결 발표 보도 (세부 미확인) | Yahoo Finance · P3 |

---

## [5] AI 인프라 — 공급 측

| 기업 | 뉴스 제목 | 사실 내용(무슨 일이) | 출처일자 | 출처+태그 |
|------|-----------|----------------------|----------|-----------|
| NVIDIA (NVDA) | "Nvidia Denies Kyber Rack Delay Rumors, Says Product Roadmap 'Intact'" | SemiAnalysis(연구기관)가 7월 6일 Kyber NVL144 캐비닛 시스템의 12개월 지연(2027→2028) 보도. NVIDIA는 같은 날 "Our roadmap is intact"라며 즉각 부인. 부인 발표 이후 주가 1%+ 반등. 7월 7일 종가 $192.07 (-1.92%) | 2026-07-06~07 | TipRanks · "Nvidia Stock (NVDA) Gains after Company Denies Kyber AI Rack Delay Report" · P2; Gurufocus · P3 |
| NVIDIA (NVDA) | "Goldman Says 21.7x Is 'Compelling' After Kyber Delay Denied" | Goldman Sachs 애널리스트, NVDA 선행 PER 21.7배가 S&P500 평균 수준이며 5년 평균(72배) 대비 매력적이라고 언급 | 2026-07-07 | TradingKey · P3 |
| Broadcom (AVGO) | 삼성 실적 발표 여파 | 7월 7일 종가 $373.60 (-1.96%); 장중 $367.03–$383.16 범위 | 2026-07-07 | Yahoo Finance · P2 |
| AMD | 삼성 실적 발표 여파 | -7.35% (일부 보도 "craters 8%") · 종가 약 $552 전후 | 2026-07-07 | 24/7 Wall St. · P2; Yahoo Finance · P2 |
| TSM (Taiwan Semi) | N/A | 금일 신규 뉴스 없음; Yahoo Finance 표시 $451.79 (날짜 미확정) | 확인 필요 | Yahoo Finance · N/A |
| SMH ETF (VanEck 반도체) | 자금 유출 및 장중 낙폭 | 장 초반 -3%+ 하락; 최근 -$1.24B 대규모 환매 발생 | 2026-07-07 | Seeking Alpha · ETF.com · P3 |
| SOXL (Direxion 반도체 3배) | "SOXL's 16% Daily Collapse Exposes $7.9 Billion in Hidden Swap Financing" | SOXL 일일 -16% 급락; 내재 스왑 파이낸싱 규모 $79억 노출 보도 | 2026-07-07 | Yahoo Finance · P2 |
| 삼성전자 (글로벌 칩 트리거) | "Samsung Q2 2026 Operating Profit Jumps 19-Fold" | 삼성전자 2Q26 예비 실적: 매출 171조 원(YoY +129%), 영업이익 89.4조 원(YoY +1,810%). 서울 주가 -7%(장중 -10%까지). Deutsche Bank: 컨센서스 대비 6%만 상회 → "기대 미충족" 해석으로 매도세 촉발. 상세 실적은 7월 30일 공시 예정 | 2026-07-07 | iTechPost · "Samsung Q2 2026 Operating Profit Jumps 19-Fold" · P3; Yahoo Finance · "Samsung Q2 2026 earnings: Record profit, stock falls 7%" · P2; Bloomberg · "Samsung Misses AI Expectations, Pressures Tech Stocks" · P2 |
| HBM/DRAM/NAND 현물가 | N/A | 금일 신규 공시 데이터 확인 불가 | N/A | N/A |

---

## [5-A] AI 인프라 — 수요 측 / 하이퍼스케일러 CAPEX 〔실적시즌 외〕

실적시즌 외 — 직전 가이던스 유지. 아래 4사 실적 발표 전까지 CAPEX 공시 변동 없음.

| 항목 | 예정 실적 발표일 | 출처일자 | 출처+태그 |
|------|----------------|----------|-----------|
| Microsoft (MSFT) | 2026-07-29 | 확인 필요 | MarketBeat 참조 · P3 |
| Amazon (AMZN) | 2026-07-30 | 확인 필요 | MarketBeat 참조 · P3 |
| Alphabet (GOOGL) | 2026-07-28 | 확인 필요 | MarketBeat 참조 · P3 |
| Meta (META) | 2026-07-29 | 확인 필요 | MarketBeat 참조 · P3 |

---

## [6] 시총 상위 10 — AI 무관 일반 이슈

| 기업 | 사실 내용 | 출처일자 | 출처+태그 |
|------|-----------|----------|-----------|
| SpaceX (SPCX) | SpaceX, 7월 7일부로 Nasdaq-100 편입. JPMorgan 추산 편입 비중 ~1.3%. Nasdaq-100 추종 자산 $8000억+ 중 패시브 강제 매수 규모 $43억(JPMorgan 추산). SPCX(SpaceX 연동 추적 상품) 공시 이후 ~29% 급락 | 2026-07-07 | ETF.com · "SpaceX Joins the Nasdaq-100 on July 7" · P2; Motley Fool · P3; Benzinga · "SpaceX Nasdaq 100 Debut, Minimal Lift" · P3 |
| Alphabet (GOOGL) | Proxima Fusion(독일 핵융합 스타트업)의 €4억1100만 펀딩 라운드에 참여 | 2026-07-07 | Yahoo Finance 모버스 보도 · P3 |
| NVDA / AAPL / AMZN / BRK / TSLA | 금일 신규 일반 이슈 없음 (AI 인프라 이슈는 [5] 참조) | — | N/A |

---

## [7] 기관·대형 자금 수급

| 항목 | 종목/ETF | 사실 내용 | 규모(수치) | 출처+태그 |
|------|----------|-----------|------------|-----------|
| ETF 자금 환매 | SMH (VanEck 반도체) | 대규모 환매 발생 | -$1.24B | ETF.com · P3 |
| ETF 자금 유입 | SOXX (iShares 반도체) | 자금 유입 | +$419.4M | ETF.com · P3 |
| 패시브 강제 매수 | QQQ / QQQM | SpaceX Nasdaq-100 편입에 따른 패시브 강제 매수 발생 | ~$43억(JPMorgan 추산) | ETF.com · JPMorgan 간접 인용 · P3 |
| 블록딜/옵션 이상거래 | N/A | 금일 확인된 건 없음 | — | N/A |

---

## [7-A] Insider Trading (SEC Form 4) 〔조건부〕

| 기업 | 내부자 | 직책 | 매수/매도 | 거래유형 | 규모 | 거래일 | 출처 |
|------|--------|------|-----------|----------|------|--------|------|
| NVDA | (복수) | — | 매도 | 재량 2건 / 주식 수여 2건 / 증여 2건 (6월 공시) | 매도 합계 $1억990만 | 2026-06 | Yahoo Finance NVDA Insider Transactions · P3 |

> ※ 7월 7일 기준 신규 Form 4 공시(NVDA·AVGO·CRDO·CLS·APLD·VRT·SMCI) 확인 불가 — N/A

---

## [8] 향후 14일 주요 일정

**경제 일정**

| 날짜 | 시각(ET / KST) | 이벤트 | 컨센서스 | 이전치 | 출처 |
|------|----------------|--------|----------|--------|------|
| 2026-07-08 (수) | 14:00 ET / 03:00 KST(7/9) | FOMC 의사록 공개 (6/16~17 회의) | — | — | Fed Calendar · P1 |
| 2026-07-14 (화) | 08:30 ET / 21:30 KST | CPI (6월) 발표 | 확인 필요 | 확인 필요 | BLS 발표 일정 · P1 |
| 2026-07-28 (화) | — | FOMC 회의 시작 (7/28~29) | — | — | Fed Calendar · P1 |
| 2026-07-29 (수) | 14:00 ET | FOMC 금리 결정 + Warsh 기자회견 | 동결(73.4%) | 3.50–3.75% | Fed Calendar · P1; CME FedWatch · P3 |

> ※ PPI·GDP·Payroll·실업률 등 7/8~7/14 중 추가 지표 일정 확인 불가 — 검증 필요

**기업 일정**

| 날짜 | 기업 | 이벤트 | 컨센서스 EPS | 컨센서스 매출 | 출처 |
|------|------|--------|--------------|---------------|------|
| 2026-07-22 (수) | Tesla (TSLA) | Q2 실적 발표 | 확인 필요 | 확인 필요 | MarketBeat · P3 |
| 2026-07-28 (화) | Alphabet (GOOGL) | Q2 실적 발표 | 확인 필요 | 확인 필요 | MarketBeat · P3 |
| 2026-07-29 (수) | Microsoft (MSFT), Meta (META) | Q2 실적 발표 | 확인 필요 | 확인 필요 | MarketBeat · P3 |
| 2026-07-30 (목) | Apple (AAPL), Amazon (AMZN) | Q3/Q2 실적 발표 | 확인 필요 | 확인 필요 | MarketBeat · P3 |
| 2026-07-30 (목) | Samsung Electronics | Q2 2026 상세 실적 발표 | — | 171조 원 (예비치) | Samsung IR · P1 |

---

## [9] 오늘의 사실 목록 (순위 없음)

```
[1] S&P500 7,503.85 (-0.45%), NASDAQ 25,818.69 (-1.16%) 마감 · Yahoo Finance P2
[1] VIX 16.36 (+5.07%), DXY 100.765 (+0.15%) · Trading Economics P3
[1] WTI $71.04 (+3.63%), Brent ~$72.89 (+1.26%), Gold ~$4,147.94 (-0.41%) · P3
[1] Dow Jones 53,289.30 (52주 고점 / 종가 확인 필요), 기술주 이탈 자금 → 다우 경기방어주 로테이션 보도 · HDFCSky P3
[2] 기준금리 3.50–3.75% 유지 (6/17 FOMC 동결 결정) · Fed P1
[2] 2년물 4.15%, 10년물 4.495%, 스프레드 +34.5bp · P2
[2] CME FedWatch 7/29 FOMC 동결 확률 73.4% · P3
[2] FOMC 의사록(6월 회의) 7월 8일 14:00 ET 공개 예정 · Fed P1
[3] 금일 주요 경제지표 발표 없음 · N/A
[4] AMAT -10.02%, INTC -8.38%, LRCX -8.57%, KLAC -7.94%, AMD -7.35% · 24/7 Wall St. P2
[5] 삼성전자 2Q26 예비 실적: 매출 171조 원, 영업이익 89.4조 원 (+1,810% YoY); 서울 주가 -7% · Bloomberg P2
[5] NVDA, SemiAnalysis의 Kyber NVL144 지연 보도 부인 — "Our roadmap is intact" · TipRanks P2
[5] NVDA 종가 $192.07 (-1.92%), AVGO $373.60 (-1.96%) · Yahoo Finance P2
[5] SMH ETF 장 초반 -3%+, 최근 -$1.24B 환매 · ETF.com P3
[5] SOXL 일일 -16% 급락, $79억 스왑 파이낸싱 노출 보도 · Yahoo Finance P2
[6] SpaceX, 7/7부 Nasdaq-100 편입; JPMorgan 추산 패시브 매수 $43억 · ETF.com P2
[7] SOXX +$419.4M 유입 / SMH -$1.24B 환매 · ETF.com P3
[7] QQQ, SpaceX 편입으로 ~$43억 강제 매수 발생 · ETF.com P3
[8] 다음 주요 이벤트: 7/8 FOMC 의사록, 7/14 CPI, 7/29 FOMC 금리결정 · P1
```

---

## 출력 전 자가 점검 결과

0. **방화벽**: 투자 의견·전망·★·AI영향도·밸류체인·순위·다중추론 없음 ✅
1. 날짜를 검색으로 확정 (2026-07-07 ET 미국 정규장 종가 기준) ✅
2. 모든 수치·뉴스에 출처+검증 태그 부여 ✅
3. 확인 못한 칸은 N/A 또는 "확인 필요" 처리 ✅
4. 원인은 보도된 사실만 기재, 본인 추론 없음 ✅
5. 동일 사건 대표 출처 1개 통합 ✅
6. [5]공급/[5-A]수요/[6]일반 분류 완료 ✅
7. 삼성 실적 CAPEX·가이던스 출처일자(2026-07-07) 기재 ✅
8. Form 4: 6월 공시 확인, 7월 7일 신규 공시 N/A 처리 ✅
9. [9] 섹션순 사실 나열, 순위 없음 ✅

## 미확인 항목 (2단계 Analysis 전 재확인 권장)

- Dow Jones 7/7 종가: 53,289 (기록) vs 52,925 (일부 출처 상충) — 교차 검증 필요
- Russell 2000 7/7 종가: ~3,015.34 (-0.30%) — 날짜 미확정
- SOX 7/7 종가: N/A (장중 반도체 ETF 기준 -3%+ 확인, 지수 종가 미확인)
- ES/NQ 선물: July 8 KST 기준 정확한 시각 불명확
- 7/8~7/14 추가 경제지표 일정 (PPI 등) 검증 필요
- NVDA·AVGO·CRDO 등 7/7 신규 Form 4 공시 미확인
