# 미국 시장 데일리 수집 결과 (Collect)
# 기준일: 2026-07-23 (목) · 미국 정규장 종가 기준 · 실행모드: [실적시즌]  (Tesla/Alphabet earnings just reported — use 실적시즌 mode, covering [5-A] and [6] fully)
# 생성시각(KST): 2026-07-24 07:30

## [1] 미국 주요 지수 + 리스크 지표 (Daily)

| 항목 | 종가/수치 | 등락률 | (보도된) 원인 | 출처+태그 |
|---|---|---|---|---|
| S&P500 | 7,408.30 | -1.21% | 중동(예멘 후티) 사우디 유조선 공격 보도로 유가 급등, 알파벳(-7%)·테슬라(-14%) 실적 반응이 지수 하방 압력 | Washington Post(AP) · "How major US stock indexes fared Thursday 7/23/2026" · 2026-07-23 · https://www.washingtonpost.com/business/2026/07/23/wall-street-dow-nasdaq-stocks/70df2dda-86d3-11f1-9cec-0fb26676f07e_story.html [P2] |
| NASDAQ 종합 | 25,137.69 | -2.15% | 알파벳(-7%)·테슬라(-14%) 실적 발표 후 주가 급락이 기술주 비중 큰 지수에 집중 타격 | CNBC · "Dow drops 500 points as Brent crude surges above $100; Alphabet and Tesla tank: Live updates" · 2026-07-23 · https://www.cnbc.com/2026/07/22/stock-market-today-live-updates.html [P2] |
| Dow | 51,711.65 (-506.93pt) | -0.97% | 상동(유가 급등 + 대형 기술주 실적 충격) | Washington Post(AP) · 상동 · 2026-07-23 [P2] |
| Russell 2000 | 2,932.45 (-27.49pt) | -0.93% | 개별 기사 확인 불가, 데이터 제공처 종가 기준 | Yahoo Finance/TradingEconomics 종합 데이터 · 2026-07-23 [P3] |
| SOX (필라델피아 반도체지수) | N/A (정확한 종가 확인 불가) | N/A | 6/22 고점 대비 -20% 하회, "베어마켓" 진입으로 보도 | RealClearMarkets · "Why Semiconductor 'Bear Market' Isn't Foreboding" · 2026-07-23 · https://www.realclearmarkets.com/2026/07/23/why_semiconductor_bear_market_isnt_foreboding_1195981.html [P3] |
| ES 선물(S&P500, Sep'26) | 약 7,541.25 (검색 시점 스냅샷) | N/A | 확인 필요 — 정규장 마감 후 프리마켓 변동 중 캡처값, 등락률 계산 불가 | Investing.com/TradingView 종합 · 2026-07-24 [P3] |
| NQ 선물(Nasdaq100, Sep'26) | 29,085.00 | -0.33% (프리마켓, 약 02:55 ET) | 확인 필요 | Yahoo Finance · "Nasdaq 100 Sep 26 (NQ=F)" · 2026-07-24 · https://finance.yahoo.com/quote/NQ=F/ [P3] |
| VIX | 16.64 | -2.4% | N/A (개별 원인 기사 확인 불가) | Yahoo Finance/CNBC 종합 · 2026-07-23 [P3] |
| DXY(달러인덱스) | 약 101.0~101.2 (정확한 종가 확인 불가) | N/A | N/A | FXStreet · "US Dollar Index Price Forecast: Weakens to near 101.00..." · 2026-07-23 · https://www.fxstreet.com/news/us-dollar-index-price-forecast-weakens-to-near-10100-but-retains-bullish-tone-above-100-day-sma-202607230653 [P3] |
| WTI | $92.19/배럴 (정산가) | +6%대(+6.37% 보도치 존재) | 사우디 유조선 공격 보도 + 트럼프 대통령의 이란 추가 타격 위협 | CNBC · "Oil prices: WTI, Brent rise after attacks on Saudi tankers" · 2026-07-23 · https://www.cnbc.com/2026/07/23/oil-prices-today-wti-brent-trump-iran-hormuz.html [P2] |
| Brent | $100.69/배럴 (정산가, 장중 $100.88~101 부근 고점 보도도 존재) | 약 +7% | 상동, 2026-05-26 이후 최초로 배럴당 $100 상회 | CNBC · 상동 · 2026-07-23 [P2] |
| Gold | 약 $4,045~4,063/온스 (변동), $4,100 하회 | 약 -2.06% | 유가 급등에 따른 인플레이션 우려와 안전자산 수요가 상충 | CNBC · "The price of gold today, July 23, 2026" · 2026-07-23 · https://www.cnbc.com/select/the-price-of-gold-today-july-23-2026/ [P2]; Yahoo Finance · "Gold prices today, Thursday, July 23, 2026" · 2026-07-23 [P2] |

## [2] 금리 / 연준 (Daily)

| 항목 | 사실 내용(발언·수치) | 출처+태그 |
|---|---|---|
| FOMC 정책금리 (현재) | 6월 FOMC에서 3.50~3.75% 유지 결정. 차기 FOMC는 2026-07-28~29, 결과 발표 2026-07-29 14:00 ET | Federal Reserve · FOMC 일정/6월 성명 · [P1] |
| 파월 후임 의장 케빈 워시(Kevin Warsh) 의회 증언 (2026-07-14) | "지난 5년간의 인플레이션 급등은 지나간 일이 될 것이다(the inflation surge of the last five years will be a thing of the past)", "지속적으로 높은 인플레이션에 대해서는 어떠한 관용도 없다(no tolerance for persistently elevated inflation)", 정책 "체제 전환(regime change)"을 언급하며 2020년 평균물가목표제(FAIT) 프레임워크를 "실수(a mistake)"였다고 발언 | Federal Reserve Board · Testimony by Chairman Warsh, Semiannual Monetary Policy Report to Congress · 2026-07-14 · https://www.federalreserve.gov/newsevents/testimony/warsh20260714a.htm [P1] |
| CME FedWatch (7/29 FOMC 결과 확률, 2026-07-21 기준) | 동결(3.50~3.75% 유지) 74.9%, 25bp 인상 25.1%, 인하 확률 0% | CNBC · "A July rate hike from the Fed? The odds are rising" · 2026-07-13 (데이터 갱신 2026-07-21) · https://www.cnbc.com/2026/07/13/-a-july-rate-hike-from-the-fed-the-odds-are-rising.html [P2] |
| CME FedWatch (9월 FOMC 확률, 참고치) | 동결 29.8%, 25bp 인상 50.6%, 50bp 인상 19.6%로 보도 (인하 확률 낮음) | 상동 종합 데이터 · 2026-07-21 [P3] |
| 미 10년물 국채금리 | 4.66% (2026-07-23, 전일 대비 소폭 하락) | TradingEconomics · "US 10 Year Treasury Note Yield" · 2026-07-23 [P1(FRED 원계열 기반)/P3] |
| 미 2년물 국채금리 | 4.26% (2026-07-21 기준, 07-23 당일 수치 확인 불가) | 종합 데이터, 07-23 값은 N/A — 확인 필요 [P3] |
| 10Y-2Y 스프레드 | 정확한 07-23 스프레드 산출 불가(2년물이 07-21 값) — N/A, 확인 필요 | N/A |

## [3] 주요 경제지표 (2026-07-23 ET 발표분)

| 지표 | 발표시각(ET·KST) | 발표치 | 예상치 | 이전치 | 서프라이즈 | 출처 |
|---|---|---|---|---|---|---|
| 신규 실업수당 청구건수(주간, 7/18 마감주) | 08:30 ET · 21:30 KST(7/23) | 187,000명 | 211,000명(Bloomberg 보도 기준; 일부 매체 212,000명) | 209,000명(수정치, 원발표 208,000명) | -24,000 | Bloomberg · "US Initial Jobless Claims Fall to Lowest Level Since 1969" · 2026-07-23 · https://www.bloomberg.com/news/articles/2026-07-23/us-initial-jobless-claims-fall-to-lowest-level-since-1969 [P2]; CNN · "The number of Americans filing for unemployment is the lowest since 1969" · 2026-07-23 [P2] |
| 연속 실업수당 청구건수 | 08:30 ET | 179.6만명 | N/A | 179.8만명(수정치) | N/A | Bloomberg 상동 [P2] |

기타 지표(CPI/PPI/GDP/고용보고서/소매판매/ISM 등): 2026-07-23 발표분 없음. (기존주택판매는 6월분이 2026-07-09에 이미 발표되어 금일 발표 대상 아님 — 확인함)

## [4] 특징 종목 (Daily, [5]/[5-A]/[6] 제외)

| 종목 | 티커 | 등락률 | 거래량 | (보도된) 핵심 사실 | 출처+태그 |
|---|---|---|---|---|---|
| Lockheed Martin | LMT | +11.4% ($573.21) | N/A | Q2 EPS $7.94(예상 $7.09), 매출 $200.63억(예상 $193.44억) 어닝 서프라이즈 | Benzinga · "Lockheed Martin, Quest Diagnostics, Thermo Fisher Scientific And Other Big Stocks Moving Higher On Thursday" · 2026-07-23 · https://www.benzinga.com/trading-ideas/movers/26/07/60640846/ [P3] |
| Honeywell | HON | +5% | N/A | 2026년 조정영업이익 및 비GAAP 마진 가이던스 상향, Q2 실적 컨센서스 상회 | Benzinga 상동 · 2026-07-23 [P3] |

(Quest Diagnostics, Thermo Fisher, Southwest Airlines 등도 기사에서 "상승 종목"으로 언급되었으나 ±5% 이상 등락률을 개별 확인하지 못해 표에서 제외 — 확인 필요)

## [5] AI 인프라 — 공급 측 (Daily)

| 기업 | 뉴스 제목 | 사실 내용(무슨 일이) | 출처일자 | 출처+태그 |
|---|---|---|---|---|
| NVIDIA | 미국 전역 "다크파이버" 확보 보도 | 롱홀 다크파이버(구간당 최대 100페어)를 미국 전역에서 매입 중이라는 보도, 니덤은 3년간 $50~100억 투자 규모로 추정. NVIDIA는 공식 확인하지 않음(미확인 보도) | 2026-07-23 | Yahoo Finance · "NVIDIA is Acquiring 'Dark Fiber' Across the United States" · https://finance.yahoo.com/technology/articles/nvidia-acquiring-dark-fiber-across-041635928.html [P3, 미확인] |
| NVIDIA | GB200/B200 공급 상황 | GB200 시스템 조달 리드타임 12~24주 지속, B200 생산 물량이 2026년 2분기까지 사전 배정된 상태로 보도 | 2026-07-22 | 산업 리서치 종합(IntuitionLabs 등) [P3] |
| Broadcom | 애플 $300억 규모 커스텀칩 다년 계약 | 애플과 커스텀 실리콘 파트너십을 2031년까지 연장, 15억개 이상 미국산 칩 생산 포함, 포트콜린스(콜로라도) 시설에 $15억 확장 투자 | 2026-07-08~09 | Yahoo Finance · "Apple Announces $30 billion Multi-year Chip Deal With Broadcom (AVGO)" · https://finance.yahoo.com/technology/articles/apple-announces-30-billion-multi-065814718.html [P2] |
| Broadcom | Q3 AI 매출 가이던스 | Q3 AI 반도체 매출 약 $160억(전년비 +200% 이상)으로 가이던스, 구글·메타·오픈AI향 하이퍼스케일러 디자인윈 반영. 현재까지 AI 반도체 수주 $300억 이상, 출하 완료분 $108억 | 2026-07-09 (가이던스 발표일) | Motley Fool/phemex 종합 · 2026-07-06~09 [P3] |
| AMD | Advancing AI 2026 행사 — MI400 시리즈 공식 공개 | MI400 칩 1개당 HBM4 432GB 탑재, FP4 기준 2.9엑사플롭스 성능. MI440X(8-GPU 랙, Epyc Venice CPU 1개 탑재)·MI430X(소버린AI/HPC용) 제품 라인업 공개. Helios 랙(2026년 3분기 출시 예정, 최대 3엑사플롭스/랙)도 공개. 오픈AI가 6GW 규모 AMD GPU 배치를 약속했다고 발표, MS 애저·오라클이 Helios 초기 고객사로 거명됨 | 2026-07-22~23 | AMD IR · "AAI 2026: AMD Delivers Full-Stack Compute for the Agentic AI Era" · https://ir.amd.com/news-events/press-releases/detail/1294/ [P1] |
| TSMC | Q2 2026 실적 발표 | 매출 $402억(전년비 +34%), 가이던스 상단($390억~$402억)에 근접 달성, 5분기 연속 사상 최대 매출·이익 기록. AI 반도체 수요를 "매우 견조"하다고 설명하며 연간 성장 전망 및 설비투자 계획 상향 | 2026-07-16 | 종합 보도(Yahoo Finance 등) · 2026-07-16 [P1/P2] |
| Arista Networks | Q2 2026 실적 발표일 예고 | 2026-08-04 장마감 후 실적 발표, 콘퍼런스콜 오후 1:30 PT(오후 4:30 ET) 예정 공지 | 2026-07-07 | Arista Networks 공식 보도자료 · https://www.arista.com/en/company/news/press-release/24143-pr-20260706 [P1] |
| Arista Networks | 주가/AI 매출 목표 | 2026-07-21 종가 $174.58(시총 $2,198.2억). CEO가 2026년 AI 매출 목표를 $35억으로 상향 언급, 자사주 매입 중단 및 재고 확대 중이라고 보도 | 2026-07-21 | TradingKey/StocksToTrade 종합 · 2026-07-21 [P3] |
| Credo Technology | 애널리스트 목표주가 상향 | Evercore ISI가 커버리지 개시(Outperform, 목표가 $325), Stifel이 목표가 $250→$350로 상향, BofA가 $252→$340로 상향. 주가는 최근 고점($290 부근) 대비 약 25% 하락한 $212 부근에서 거래 | 2026-07-20 | StocksToTrade 종합 · 2026-07-20 [P3] |
| Celestica | 주가 상승 및 실적 일정 | 2026-07-20 주가 +2.38%, 하이퍼스케일 데이터센터 지출 및 AI서버 수요 확대가 배경으로 보도. Q2 2026 실적은 2026-07-27 장마감 후 발표, 콘퍼런스콜은 07-28 오전 8:00 ET 예정 | 2026-07-20 / 발표예정 07-27 | Kalkine/GlobeNewswire 종합 · 2026-07-20, 2026-07-06 [P2/P1] |
| Vertiv | Strategic Thermal Labs 인수 | 액체냉각 전문 기업 Strategic Thermal Labs 인수 발표(AI/고밀도 데이터센터용 냉각 솔루션 강화 목적) | 2026-07-20 | Yahoo Finance · "Vertiv (VRT) Is Buying Strategic Thermal Labs For AI Cooling Growth" [P2] |
| Vertiv | 이탈리아 토냐나(Tognana) 생산능력 확장 | 2026년 말까지 칠러(chiller) 생산능력을 2배로 확대할 계획 발표, 2027년 초 대규모 테스트 연구소 완공 예정 | 2026-07-21 | PR Newswire · "Vertiv Expands Global Manufacturing Capacity for AI-Ready Data Center Cooling Solutions" · https://www.prnewswire.com/news-releases/vertiv-expands-global-manufacturing-capacity-for-ai-ready-data-center-cooling-solutions-302830933.html [P1] |
| Super Micro Computer | 잠정 실적 발표(Q4 FY2026) | GAAP·비GAAP 매출총이익률 가이던스를 기존 8.2~8.4%에서 15~17%로 상향. 분기 신규 수주 $600억 이상, 사상 최대 백로그 기록. 주가 2026-07-22 +22.5%(주가 $31.25) | 2026-07-22 | Motley Fool/FX Leaders 종합 · 2026-07-22 [P2] |
| Super Micro Computer | H15 서버 포트폴리오 출시 | 6세대 AMD EPYC 9006 시리즈 CPU 탑재 신규 H15 서버 포트폴리오 발표, 세대 대비 CPU 성능 1.7배 향상 | 2026-07-23 | StockTitan · "Supermicro Introduces New Server Portfolio with 6th Gen AMD EPYC" [P1] |
| Applied Digital | Polaris Forge 1 2단계 가동 | Polaris Forge 1 캠퍼스 2번 건물 1단계가 서비스 개시(Ready for Service), 75MW 가동 용량 추가로 캠퍼스 총 가동용량 175MW 도달. 5개 AI Factory 캠퍼스 합산 계약임대수익 $360억, 임계 IT 부하 1.4GW로 보도 | 2026-07-01 | Applied Digital IR 보도자료 종합 · 2026-07-01 [P1] |
| 메모리(HBM/DRAM/NAND) | 메모리 가격 급등 지속 | DRAM 현물가가 지난 1년간 약 700% 상승했다고 블룸버그가 보도. DDR5 현물가는 2025-09 $6.84 → 2025-12 $27.20으로 상승. HBM은 2026년 물량이 완판된 상태이며, SK하이닉스 CEO는 메모리 공급부족이 2030년 이후까지 지속될 수 있다고 2026년 7월 발언 | 2026-07월 중(구체 일자 확인 필요) | Tom's Hardware/tech-insider 종합 보도 · 2026-07 [P3] |

## [5-A] AI 인프라 — 수요 측 / 하이퍼스케일러 CAPEX (실적시즌)

| 항목 | 사실 내용(발표 수치·문구) | 전분기 대비(산술) | 출처일자 | 출처+태그 |
|---|---|---|---|---|
| Alphabet(GOOGL) Q2 2026 실적 | 매출 $1,198억(+24% YoY), 희석 EPS $9.11, 구글클라우드 매출 +82% YoY | Q2 capex $449억 vs Q1 capex 약 $224.5억 추정 시 약 +100% YoY(회사 발표 문구 기준, 전분기 대비 수치는 회사가 YoY로만 제시 — QoQ 산술치는 확인 필요) | 2026-07-22 | Alphabet 실적 발표/Investing.com · "Alphabet Q2 2026 slides: 24% revenue growth, cloud surges despite capex" · https://www.investing.com/news/company-news/alphabet-q2-2026-slides-24-revenue-growth-cloud-surges-despite-capex-93CH-4807148 [P1] |
| Alphabet 2026 연간 자본지출(Capex) 가이던스 | 기존 $1,800~1,900억에서 $1,950~2,050억으로 상향. 서버 약 60%, 데이터센터·네트워킹 약 40% 배분 계획 | 상향폭: 하단 +$150억, 상단 +$150억 | 2026-07-22 | 상동 [P1] |
| Microsoft(MSFT) | 2026 회계연도 Capex $1,900억으로 설정(애널리스트 평균 추정치 $1,520억 상회). CFO 에이미 후드는 이 중 $250억을 메모리 반도체·부품 단가 상승 요인으로 설명 | 가이던스 시점 대비 상향폭 약 +$380억(대비 애널리스트 평균) | 확인 필요(가이던스 발표 정확 일자 미확인) | 종합 보도 · 2026-07 [P3] |
| Microsoft 주가 반응(07-23) | 알파벳의 capex 상향 가이던스 이후 AI 지출 우려로 MSFT 주가 -2%대 하락 | N/A | 2026-07-23 | CNBC · "Stocks making the biggest moves midday: Alphabet, Tesla, Amazon, Southwest Airlines & more" · https://www.cnbc.com/2026/07/23/stocks-making-the-biggest-moves-midday-googl-tsla-amzn-luv.html [P2] |
| Amazon(AMZN) | 2026년 연간 capex 약 $2,000억 전망(Q1 단독 $442억 집행, AWS 매출 +28%) | N/A(연간 가이던스, QoQ 비교 불가) | 확인 필요(가이던스 정확 발표일 미확인) | 종합 보도 · 2026-07 [P3] |
| Amazon 주가 반응(07-23) | 알파벳 capex 상향 이후 AI 지출 우려로 AMZN 주가 -4% 하락 | N/A | 2026-07-23 | CNBC 상동 · 2026-07-23 [P2] |
| Meta(META) | 2026년 capex 가이던스를 기존 $1,150~1,350억에서 $1,250~1,450억으로 상향(2026-Q1 실적 발표 시) | 상향폭 하단 +$100억, 상단 +$100억 | 2026-04-29 (Q1 실적 발표일, 이후 신규 변동 미확인) | Fortune · "Meta just bumped its 2026 capex forecast up to as much as $145 billion" · https://fortune.com/2026/04/29/meta-zuckerberg-145-billion-ai-spending-roi/ [P2] |
| 4개사(Alphabet·MS·Meta·Amazon) 2026년 capex 합산 전망 | 합산 약 $7,250억으로 전년 대비 +77% | N/A | 2026-07 (보도일 확인 필요) | Yahoo Finance · "Google, Microsoft, Meta, and Amazon capex spending to hit $725 billion in 2026, up 77% from last year" [P3] |

## [6] 시총 상위 10 — AI 무관 일반 이슈 (실적시즌)

| 기업 | 사실 내용 | 출처일자 | 출처+태그 |
|---|---|---|---|
| Tesla(TSLA) | Q2 2026 실적: 매출 $282.4억(+26% YoY, 컨센서스 약 $264억 상회), 비GAAP EPS $0.33(컨센서스 약 $0.47 대비 하회). 영업이익 -57% YoY $3.98억(영업이익률 1.4%, 전년동기 4.1%). 규제크레딧 수익 -67% YoY $1.46억(전년동기 $4.39억). 잉여현금흐름 -$10.9억(마이너스 전환) | 2026-07-22 (실적 발표) | Bloomberg · "Tesla Earnings: (TSLA) Shares Fall After Profit Tumbles as AI Spending Jumps" · https://www.bloomberg.com/news/articles/2026-07-22/tesla-second-quarter-earnings-miss-wall-street-s-expectations [P2] |
| Tesla(TSLA) | 실적 발표 후 주가 -14.1% 급락(2025-06-05 이후 최대 하루 낙폭), 시가총액 약 $1,400억 증발, 머스크 순자산 $186억 감소(약 $7,317억으로) | 2026-07-23 | Forbes · "Tesla Plummets 14%—Costing Elon Musk $18 Billion" · https://www.forbes.com/sites/tylerroush/2026/07/23/teslas-worst-day-in-a-year-cuts-elon-musks-net-worth-by-18-billion/ [P2] |
| Apple(AAPL) | 2026 회계연도 3분기 실적 발표 예정일 2026-07-30(장마감 후), 컨센서스 EPS $1.88(전년동기 $1.57 대비 +19.8%). 팀 쿡이 CEO로서 마지막으로 실적 콘퍼런스콜에 참여할 것으로 보도(경영진 교체 예정) | 발표예정일 2026-07-30 / 보도일 2026-07-02 | 9to5Mac · "Apple sets Q3 2026 earnings release for July 30" · https://9to5mac.com/2026/07/02/apple-sets-q3-2026-earnings-release-for-july-30/ [P2] |

(NVDA/AVGO/MSFT/AMZN/META/BRK/TSM: 금일 기준 AI 인프라 무관 일반 이슈 확인 안 됨 — N/A)

## [7] 기관·대형 자금 수급 (Daily)

| 항목 | 종목 | 사실 내용 | 규모(수치) | 출처+태그 |
|---|---|---|---|---|
| ETF 자금유입 | SOXX(iShares Semiconductor ETF) | 하루 순유입 | $13.8억(2026-07-19 기준 보도) | ETF.com/Benzinga 종합 · 2026-07-19 [P3] |
| ETF 자금유입 | SMH(VanEck Semiconductor ETF) | 하루 순유입 | $4.549억(2026-07-19 기준 보도) | 상동 · 2026-07-19 [P3] |
| ETF 자금유입 | QQQ(Invesco QQQ Trust) | 하루 순유입 | $13.7억(2026-07-19 기준 보도, SOXX에 근소하게 뒤짐) | 상동 · 2026-07-19 [P3] |
| 옵션 거래량 | TSLA | 최근 평균 대비 이례적으로 높은 옵션 거래량 | 계약 약 220만건(기초주식 환산 약 2억1,840만주 상당) | 종합 보도 · 시점 확인 필요(2026-07월 중) [P3] |
| 옵션 거래량 | NVDA | 최근 평균 대비 이례적으로 높은 옵션 거래량 | 계약 약 300만건(기초주식 환산 약 2억9,700만주 상당) | 종합 보도 · 시점 확인 필요(2026-07월 중) [P3] |

(위 ETF/옵션 수치는 07-23 당일 특정 기사로 확정되지 않아 최근 확인된 날짜를 병기함 — 07-23 당일치는 확인 필요)

## [7-A] Insider Trading / SEC Form 4

| 기업 | 내부자 | 직책 | 매수/매도 | 거래유형 | 규모 | 거래일 | 출처 |
|---|---|---|---|---|---|---|---|
| Credo Technology(CRDO) | Daniel W. Fleming | CFO | 매도 | 10b5-1(2026-01-12 채택 계획) | 7,580주, $240.50~$249.99 | 2026-07-08 | StockTitan(SEC Form4) · https://www.stocktitan.net/sec-filings/CRDO/form-4-credo-technology-group-holding-ltd-insider-trading-activity-bd91c7d7a655.html [P1] |
| Credo Technology(CRDO) | Cheng Chi Fung | CTO | 매도 | 10b5-1(Cheng Huang Family Trust, 2025-09-05 채택 계획) | 31,290주 | 2026-07-07~08 | Motley Fool · "Credo's CTO Sold 31,290 Shares" · https://finance.yahoo.com/markets/stocks/articles/credos-cto-sold-31-290-222037582.html [P2] |
| Broadcom(AVGO) | Mark David Brazeal | Chief Legal & Corporate Affairs Officer | 매도 | 재량(해당 Form 4에 10b5-1 계획 명시 없음으로 보도) | 25,000주 × 복수 거래(예: 2026-07-10 약 $1,003만, 2026-07-08 약 $948만, 2026-06-25 약 $968만) | 2026-06-25 / 07-08 / 07-10(매체별 날짜 소폭 상이, 확인 필요) | Investing.com · "Broadcom chief legal officer Mark Brazeal sells $10m in shares" [P1 SEC Form4 기반 보도] |
| Super Micro Computer(SMCI) | 복수 이사·임원(Judy L. Lin, Tally C. Liu 등) | 이사/CFO 등 | 매도 아님(RSU 베스팅/세금원천 주식) | 옵션행사(RSU 베스팅) | 개별 건당 1,613~19,725주 | 2026-06-30~07-01 | StockTitan(SEC Form4) 종합 · 2026-07 [P1] |
| Applied Digital(APLD) | Wes Cummins | CEO 겸 회장 | 매도 아님(PSU 베스팅) | 옵션행사(성과주식단위 베스팅, 세금원천 26.7% 주식 소각) | 80만주 베스팅, 31.48만주 세금원천 처리 | 2024-11-15 부여분 베스팅(정확 베스팅/공시일 확인 필요) | StocktTitan(SEC Form4) 종합 [P1] |
| Vertiv(VRT) | 복수 임원(Eric M. Johnson, Anders Karlborg, Scott Armul, Krishna Mikkilineni 등) | CAO/EVP/CPTO/Director | 매도 아님(배당등가주/옵션 부여/세금원천) | 옵션행사/부여(신규 부여, 세금원천) | 소규모(개별 3~3,076주) | 2026-05-04~06-17 | StockTitan(SEC Form4) 종합 [P1] |

(NVDA/CLS 관련 신규 Form 4는 검색 범위 내 확인되지 않음 — 확인 필요)

## [8] 향후 14일 주요 일정 (2026-07-24 ~ 2026-08-07)

### 경제 캘린더

| 날짜 | 시각(ET·KST) | 이벤트 | 컨센서스 | 이전치 | 출처 |
|---|---|---|---|---|---|
| 2026-07-28~29 | 발표 07-29 14:00 ET(07-30 03:00 KST) | FOMC 정례회의·정책금리 결정 | 동결(3.50~3.75%) 우세(CME FedWatch 74.9%) | 3.50~3.75%(6월 동결) | Federal Reserve/CNBC 종합 [P1/P2] |
| 2026-07-30 | 08:30 ET(21:30 KST) | 2026년 2분기 GDP 속보치 | N/A(확인 필요) | 확인 필요 | BEA 발표 일정 [P1] |
| 2026-07-31 | 08:30 ET(21:30 KST) | PCE/근원PCE 물가지수(6월분) | 헤드라인 +0.2%m/m·+2.6%y/y, 근원 +0.3%m/m·+2.9%y/y(시장 컨센서스) | 확인 필요 | Morningstar 등 종합 · 2026-07 [P3] |
| 2026-08-01 | 08:30 ET(21:30 KST) | 7월 고용보고서(비농업부문 고용, 실업률), ISM 제조업 PMI 최종치 등 | 비농업 고용 약 +13만 명 내외(추정치, 매체별 편차 있음), 실업률 약 4.2%(추정) | 확인 필요 | Capital Economics 종합 · 2026-07 [P3] |
| 2026-08-03 | 10:00 ET(23:00 KST) | ISM 제조업 PMI(7월분) | N/A(확인 필요) | 53.3%(6월) | ISM · 발표 일정 [P1] |

### 기업 실적 캘린더

| 날짜 | 기업 | 이벤트 | 컨센서스 EPS | 컨센서스 매출 | 출처 |
|---|---|---|---|---|---|
| 2026-07-27(장마감 후) | Applied Digital(APLD) | FY2026 4분기·연간 실적 발표 | 확인 필요 | 확인 필요 | Applied Digital IR 보도자료 [P1] |
| 2026-07-27(장마감 후)/콜 07-28 08:00 ET | Celestica(CLS) | Q2 2026 실적 발표 | 확인 필요 | 확인 필요 | Celestica/GlobeNewswire 보도자료 [P1] |
| 2026-07-28~29 | (참고) FOMC 회의 기간과 겹침 | — | — | — | — |
| 2026-07-29(장마감 후) | Microsoft(MSFT) | FY2026 4분기 실적 발표(콜 14:30 PT) | 확인 필요 | 확인 필요 | Microsoft 공식 발표 · https://news.microsoft.com/source/2026/07/08/ [P1] |
| 2026-07-29(콜 16:30 ET) | Meta(META) | Q2 2026 실적 발표 | 확인 필요 | 확인 필요 | IG/종합 보도 [P2] |
| 2026-07-29 | Vertiv(VRT) | Q2 2026 실적 발표 | 약 $1.43 | 확인 필요 | 종합 보도 · 2026-07 [P3] |
| 2026-07-30(장마감 후) | Amazon(AMZN) | Q2 2026 실적 발표(콜 17:00 ET) | $1.82 | $1,967.1억 | aboutamazon.com 공식 발표 · https://www.aboutamazon.com/news/company-news/amazon-earnings-q2-2026-report [P1] |
| 2026-07-30(장마감 후, 콜 17:00 ET) | Apple(AAPL) | Q3 FY2026 실적 발표 | $1.88 | 확인 필요 | 9to5Mac 등 종합 · 2026-07-02 [P2] |
| 2026-08-04(장마감 후, 콜 13:30 PT/16:30 ET) | Arista Networks(ANET) | Q2 2026 실적 발표 | 확인 필요 | 확인 필요 | Arista 공식 보도자료 · 2026-07-06 [P1] |

## [9] 오늘의 사실 목록 (순위 없음)

- [1] S&P500 종가 7,408.30(-1.21%), NASDAQ 25,137.69(-2.15%), Dow 51,711.65(-506.93pt, -0.97%) · Washington Post(AP)/CNBC [P2]
- [1] Russell 2000 2,932.45(-27.49pt, -0.93%) · Yahoo Finance/TradingEconomics 종합 [P3]
- [1] SOX, 6/22 고점 대비 -20% 하회(베어마켓 진입 보도) · RealClearMarkets [P3]
- [1] VIX 16.64(-2.4%) · 종합 데이터 [P3]
- [1] WTI 정산가 $92.19(+6%대), Brent 정산가 $100.69(+7%, 2026-05-26 이후 최초 $100 상회) · CNBC [P2]
- [1] Gold $4,045~4,063/온스 구간, $4,100 하회(-2.06%) · CNBC/Yahoo Finance [P2]
- [1] 유가 급등 원인: 예멘 후티 반군의 사우디 유조선 공격 보도 및 트럼프 대통령의 이란 추가 타격 위협 · CNBC [P2]
- [2] 케빈 워시 연준의장, 2026-07-14 의회 증언에서 "지난 5년간의 인플레이션 급등은 지나간 일이 될 것" 및 "지속적으로 높은 인플레이션 용인하지 않겠다" 발언 · Federal Reserve [P1]
- [2] 차기 FOMC 2026-07-28~29, CME FedWatch(07-21 기준) 동결 확률 74.9% · Fed/CNBC [P1/P2]
- [2] 미 10년물 국채금리 4.66%(2026-07-23) · TradingEconomics [P3]
- [3] 신규 실업수당 청구건수 187,000명(예상 211,000명, 이전 209,000명 수정치), 1969년 이후 최저 수준 · Bloomberg/CNN [P2]
- [4] Lockheed Martin +11.4%($573.21), Q2 EPS $7.94(예상 $7.09) 서프라이즈 · Benzinga [P3]
- [4] Honeywell +5%, 2026년 EPS 가이던스 상향 · Benzinga [P3]
- [5] AMD, Advancing AI 2026 행사에서 MI400 시리즈(HBM4 432GB) 공식 공개, 오픈AI 6GW GPU 배치 약속 발표 · AMD IR [P1]
- [5] TSMC, Q2 2026 매출 $402억(+34% YoY)로 5분기 연속 최대 매출·이익 기록 · 종합 보도 [P1/P2]
- [5] Broadcom, 애플과 $300억 규모 다년 커스텀칩 계약(2031년까지) 연장 발표 · Yahoo Finance [P2]
- [5] Super Micro Computer, FY2026 4분기 매출총이익률 가이던스 8.2~8.4%→15~17%로 상향, 분기 신규수주 $600억 초과, 주가 07-22 +22.5% · Motley Fool [P2]
- [5] Applied Digital, Polaris Forge 1 캠퍼스 2번 건물 가동 개시로 총 가동용량 175MW 도달, 5개 캠퍼스 합산 계약임대수익 $360억 · Applied Digital IR [P1]
- [5] NVIDIA, 미국 전역 다크파이버 확보 추진 보도(니덤 추정 3년간 $50~100억), 회사는 공식 미확인 · Yahoo Finance [P3, 미확인]
- [5] DRAM 현물가 최근 1년간 약 700% 상승, HBM 2026년 물량 완판 보도 · Bloomberg/Tom's Hardware [P2/P3]
- [5-A] Alphabet, Q2 2026 매출 $1,198억(+24% YoY), 2026년 연간 capex 가이던스 $1,800~1,900억→$1,950~2,050억으로 상향 · Investing.com(회사 발표 기반) [P1]
- [5-A] Microsoft·Amazon 주가, 알파벳 capex 상향 이후 각각 -2%대, -4% 하락(2026-07-23) · CNBC [P2]
- [5-A] Meta, 2026년 capex 가이던스 $1,150~1,350억→$1,250~1,450억으로 상향(2026-04-29, Q1 실적 시) · Fortune [P2]
- [6] Tesla, Q2 2026 매출 $282.4억(+26% YoY, 컨센서스 상회) 그러나 비GAAP EPS $0.33(컨센서스 약 $0.47 하회), 영업이익률 1.4%(전년 4.1%) · Bloomberg [P2]
- [6] Tesla 주가 -14.1% 급락(2025-06-05 이후 최대 낙폭), 시총 약 $1,400억 증발 · Forbes [P2]
- [6] Apple, Q3 FY2026 실적 2026-07-30 발표 예정, 팀 쿡이 마지막으로 실적콜 참여 예정으로 보도 · 9to5Mac [P2]
- [7] SOXX ETF 하루 순유입 $13.8억, QQQ $13.7억, SMH $4.549억(2026-07-19 기준) · ETF.com/Benzinga [P3]
- [7] TSLA·NVDA 옵션 거래량이 최근 평균 대비 이례적으로 높은 수준(각각 약 220만/300만 계약)으로 보도 · 종합 보도 [P3]
- [7-A] Credo Technology CFO·CTO, 10b5-1 사전계획에 따라 각각 7,580주·31,290주 매도(2026-07-07~08) · SEC Form4(StockTitan) [P1]
- [7-A] Broadcom 최고법무책임자 Mark Brazeal, 25,000주 단위 반복 매도(2026-06-25/07-08/07-10경, 10b5-1 계획 명시 없음으로 보도) · SEC Form4 기반 보도 [P1]
- [8] 차기 FOMC 2026-07-28~29, GDP 속보치 07-30, PCE 07-31, 고용보고서 08-01, ISM 제조업 PMI 08-03 · Fed/BEA/ISM [P1]
- [8] Microsoft(07-29)·Meta(07-29)·Amazon(07-30)·Apple(07-30)·Arista(08-04) 실적 발표 예정, Amazon 컨센서스 EPS $1.82·매출 $1,967.1억, Apple 컨센서스 EPS $1.88 · 각사 공식 발표 [P1]
