# 미국 시장 데일리 수집 결과 (Collect)
# 기준일: 2026-07-21 (화) · 미국 정규장 종가 기준 · 실행모드: [데일리]
# 생성시각(KST): 2026-07-22 07:30

---

## [1] 미국 주요 지수 + 리스크 지표 (데일리)

| 항목 | 종가/수치 | 등락률 | (보도된) 원인 | 출처+태그 |
|---|---|---|---|---|
| S&P500 | 7,509.20 | +0.89% | 반도체株 강세 및 실적시즌 기대감이 지정학 리스크 우려를 상쇄, 3거래일 연속 하락 마감 후 반등 | Yahoo Finance/CNBC 종합 · "Stock Market Today, July 21: Micron Surges 12%..." · [P2] |
| NASDAQ 종합 | 25,837.21 | +1.29% | 반도체·메모리株 랠리(마이크론 등)가 견인 | 상동 · [P2] |
| Dow Jones | 52,224.64 | +385.38pt (+0.74%) | 3거래일 연속 하락(losing streak) 종료 | 상동 · [P2] |
| Russell 2000 | 2,987.40 | +44.97pt (+1.53%) | 개별 원인 보도 특정 안됨(반도체 랠리에 따른 전반적 위험선호 회복으로 추정 가능하나, 이는 보도된 사실이 아니므로 원인란은 미기재) | 검색 결과 종합(정확 출처 URL 특정 실패) · [P3] |
| SOX (필라델피아 반도체지수) | 12,356.164 | +612.315pt (+5.21%) | 마이크론(+12%)·샌디스크(+14%) 등 메모리株 급등 주도, 엔비디아·마벨·TSMC·SK하이닉스·Nebius 등 동반 상승 | Yahoo Finance/24-7 Wall St 종합 · [P2]/[P3] |
| ES (S&P500 선물, 한국시간 조간) | 확인 필요(N/A) | 확인 필요(N/A) | 검색으로 구체 수치 확인 실패 | N/A |
| NQ (나스닥 선물, 한국시간 조간) | 확인 필요(N/A) | 확인 필요(N/A) | 검색으로 구체 수치 확인 실패 | N/A |
| VIX | 17.05 | -1.60pt (-8.58%) | 지정학 리스크에도 반도체 랠리 속 변동성 완화 | Yahoo Finance · 상동 · [P2] |
| DXY (달러인덱스) | 100.92 | -0.03% | — | Trading Economics · [P3] |
| WTI 원유 | $83대 진입(장중 $82→$83 회복, 정확 종가 확인 필요·N/A) | 확인 필요(N/A, 장중 등락 심함) | 미-이란 중동 리스크(예멘 후티 반군의 사우디 해상교통 위협, 카스피안 파이프라인 컨소시엄 터미널 피격에 따른 카자흐스탄發 원유 수출 차질)와 미-이란 평화협상 기대감이 교차 | Trading Economics/Fortune 종합 · [P3] |
| Brent 원유 | $91.10 | +2.11% | 상동(중동 리스크 vs 평화협상 기대 교차) | Trading Economics · [P3] |
| Gold | $4,082.73 | +1.75% | 다음주 FOMC 대기 속 $4,000 상회 유지 | Yahoo Finance · 상동 · [P2] |

비고: 반도체지수(SOX)는 마이크론(+12%)·샌디스크(+14%)의 메모리 랠리가 핵심 동력으로 보도됨. Bank of America(Vivek Arya)는 마이크론 목표주가를 $1,550로 상향 — TradingKey/Yahoo Finance · [P2]/[P3]

---

## [2] 금리 / 연준 (데일리)

| 항목 | 사실 내용(발언·수치) | 출처+태그 |
|---|---|---|
| 2Y 국채금리 | 4.255%, 전일比 +4bp | CNBC · "Treasury yields edge higher as investors map geopolitical risks" (2026-07-21) · [P2] |
| 10Y 국채금리 | 4.63%, 전일比 +3bp | 상동 · [P2] |
| 10Y-2Y 스프레드 | +0.375%p (4.63%-4.255%, 산술 계산) | 자체 산술(2Y·10Y 수치 기반) |
| 6월 FOMC 결정문(재확인) | 연방기금금리 목표 범위 3.50~3.75% 유지(6/16-17 회의) | Federal Reserve · FOMC statement 2026-06-17 · [P1] |
| 다음 FOMC 회의 | 2026-07-28~29(현지시간), 금리 결정 발표 7/29 14:00 ET | Federal Reserve 공식 캘린더 · [P1] |
| CME FedWatch 확률 변화(시점별 보도) | 2026-07-13 기준 "25bp 인상" 확률 46.5%(Kalshi 36%)로 보도 vs 2026-07-21 기준 "동결(hold)" 확률 83.4%로 보도 — 시점 간 수치 상충하므로 각 보도 시점을 병기 | CNBC · "A July rate hike from the Fed? The odds are rising"(7/13) · [P2]; Fool.com 요약 인용(7/21 시점 수치) · [P3] |
| 연준 신규 발언 | 금일(7/21) 신규 연준 인사 공개발언 검색으로 확인되지 않음(직전 확인된 발언은 7/1 워시 의장 신트라 발언) | N/A |

---

## [3] 주요 경제지표 (조건부)

N/A — 금일(2026-07-21) CPI/Core CPI/PPI/GDP/Payrolls/실업률/신규실업수당청구/소매판매/ISM 제조업·서비스업 지표 중 해당 발표 없음.

참고(표 대상 지표 아님): Chicago Fed National Activity Index가 2026-07-22 발표 예정이라는 보도가 있으나, 본 표의 지정 지표 목록에 포함되지 않아 별도 집계하지 않음 — WebSearch 종합 · [P3]

---

## [4] 특징 종목 (데일리)

| 종목 | 티커 | 등락률 | 거래량 | (보도된) 핵심 사실 | 출처+태그 |
|---|---|---|---|---|---|
| Danaher | DHR | -13.7% | 확인 필요(N/A) | 2분기 조정 EPS $1.94(예상 $1.84 상회), 매출 $63억(예상 $61.4억 상회)로 실적은 서프라이즈했으나, 바이오프로세싱 부문 부진과 2026년 core-revenue 성장률 가이던스를 3~4%로 하향, 3분기 매출 가이던스 약세 | GuruFocus/ts2.tech · [P3] |
| MSCI | MSCI | -10.7% | 확인 필요(N/A) | 2분기 실적이 월가 예상치 미달 | TheStreet · "Stock Market Today (July 21, 2026)" · [P2] |
| Genuine Parts | GPC | -7.4% | 확인 필요(N/A) | 연간 이익 전망 하향 및 보수적 하반기 가이던스 제시 | Barchart · "Genuine Parts (GPC) Stock Trades Down, Here Is Why" · [P3] |
| Nebius Group | NBIS | +18.78%(보도 간 +18.78%~19% 소폭 상충) | 확인 필요(N/A) | 엔비디아가 SEC 공시를 통해 Nebius 지분 9.3%(약 2,226만주, $2,000만 워런트 투자분 포함, 평가액 약 $50억) 보유를 공시. 워런트 행사는 9/11 이전 금지 조항 명시 | CNBC · "Nebius stock surges nearly 19% as Nvidia discloses significant stake in neocloud"(2026-07-21) · [P2] |
| Micron Technology | MU | +12% | 확인 필요(N/A) | AI 메모리 수요發 랠리로 급등, BofA(Vivek Arya) 목표주가 $1,550로 상향 | Yahoo Finance/Motley Fool · "Stock Market Today, July 21: Micron Surges 12%..." · [P2] |
| SanDisk | SNDK | +14%(별도 보도는 +8~10%로 상충) | 확인 필요(N/A) | 메모리·스토리지 종목의 AI 수요 랠리에 동반 급등 | Yahoo Finance/24-7 Wall St · [P2]/[P3] |
| Intel | INTC | +6% | 확인 필요(N/A) | RBC 애널리스트의 2분기 실적 서프라이즈("beat call") 전망 발표가 계기. 실적발표는 7/23(목) 예정 | 24/7 Wall St · "Intel Jumps 6% on RBC's Q2 Beat Call, AMD Rises 4%, Broadcom Climbs 3%..." · [P3] |

---

## [5] AI 인프라 — 공급 측 (데일리)

| 기업 | 뉴스 제목 | 사실 내용(무슨 일이) | 출처일자 | 출처+태그 |
|---|---|---|---|---|
| NVDA | Nebius 지분 9.3% 공시 | SEC 공시를 통해 Nebius Group 클래스A 주식 약 2,226만주(9.3% 지분, 워런트분 포함) 보유 공개, 평가액 약 $50억. 워런트는 9/11 이전 행사 금지 | 2026-07-21 | CNBC · "Nebius stock surges nearly 19%..." · [P2]; Yahoo Finance · [P2] |
| NVDA | 반도체 랠리 동반 상승 | 마벨·TSMC·SK하이닉스·Nebius 등과 함께 반도체 랠리에 동반 상승 보도 | 2026-07-21 | 24/7 Wall St · 상동 · [P3] |
| AMD | 주가 +4% | 반도체 랠리 속 +4% 상승(Intel +6%, Broadcom +3%와 동반) | 2026-07-21 | 24/7 Wall St · "Intel Jumps 6% on RBC's Q2 Beat Call, AMD Rises 4%, Broadcom Climbs 3%..." · [P3] |
| AMD | 직전 실적 참고(신규 아님) | 1분기 2026 매출 $102.5억(YoY +38%), CEO 리사 수가 MI450 시리즈 트랙션·메타 6GW 배치 언급 | 확인 필요(N/A, 1분기 실적 발표 시점) | 24/7 Wall St 요약 인용 · [P3] |
| AVGO(Broadcom) | 주가 +3% | 반도체 랠리 속 +3% 상승 | 2026-07-21 | 24/7 Wall St · 상동 · [P3] |
| AVGO(Broadcom) | 직전 실적·가이던스 참고(신규 아님) | AI 반도체 매출 $108.0억(YoY +143%), 3분기 FY2026 AI 반도체 매출 가이던스 약 $160억으로 보도 | 확인 필요(N/A) | 24/7 Wall St 요약 인용 · [P3] |
| AVGO(Broadcom) | Apple 공급계약(참고, 신규 아님) | 2031년까지 애플과 $300억 이상 규모 칩 공급계약 체결, 2026-07-08 발표로 보도 | 2026-07-08 | 24/7 Wall St 요약 인용 · [P3] |
| TSM | 반도체 랠리 동반 상승 | 신규 개별 뉴스 없이 반도체 랠리에 동반 상승만 보도됨 | 2026-07-21 | 24/7 Wall St · 상동 · [P3] |
| CRDO/ANET/CLS/VRT/APLD/SMCI | — | 금일자 개별 신규 뉴스 검색으로 확인되지 않음 | N/A | N/A |
| HBM/DRAM/NAND 스팟가 | 메모리 가격 상승세 지속 | 3분기 2026 DRAM 계약가 전분기比 +13~18%, NAND 계약가 +10~15% 상승 전망(직전 분기 대비 상승폭은 둔화). 마이크론 HBM3E·HBM4는 2026년 물량이 이미 완판(sold out)되었다고 보도 | 확인 필요(N/A, 업계 리포트, 특정일 미상) | Tom's Hardware(TrendForce 인용) · [P3] |
| AI서버 출하량 | 2026년 출하량 전망 | 2026년 글로벌 AI서버 출하량이 전년比 28% 이상 증가할 것으로 전망, GPU 탑재 비중 69.7%, GB300 시스템이 출하 주도 전망 | 확인 필요(N/A, 리포트 발행일 특정 안됨) | TechPowerUp(TrendForce 인용) · [P3] |
| GPU/CoWoS 공급 | 패키징 캐파 격차 보도 | TSMC 월간 CoWoS 패키징 캐파가 2026년 14만개 수준에 도달할 것으로 전망되는 반면, 엔비디아向 CoWoS 수요는 2026년 63만개 수준으로 추정되어 캐파-수요 격차 존재한다는 보도 | 확인 필요(N/A) | 검색 요약 종합 · [P3] |

---

## [5-A] AI 인프라 — 수요 측 / 하이퍼스케일러 CAPEX (실적시즌 조건부)

신규 변동 없음 — Microsoft(7/29)·Amazon(7/30)·Meta(7/29) 실적은 아직 미발표. Alphabet은 금일(7/22) 장 마감 후 발표 예정이나 기준일(7/21) 시점에는 미발표 상태. 직전 확인된 2026 연간 CAPEX 가이던스(Microsoft $1,900억, Amazon 약 $2,000억, Alphabet 최대 $1,900억, Meta $1,250억~$1,450억, 4개사 합산 약 $7,250억)를 참고로 유지함 — 상세 출처는 직전 수집분(2026-07-20 기준) 참고.

| 항목 | 사실 내용(발표 수치·문구) | 전분기 대비(산술) | 출처일자 | 출처+태그 |
|---|---|---|---|---|
| Alphabet | 2분기 실적 발표 예정(2026-07-22 장 마감 후), 컨센서스 EPS $2.88(YoY +24.2%), 매출 $1,170억(YoY +21%) — 아직 발표 전 컨센서스치이며 실적 실제치 아님 | 산출 불가(N/A) | 2026-07-21 시점 컨센서스 | TipRanks/Yahoo Finance 종합 · [P3] |

---

## [6] 시총 상위 10 — AI 무관 일반 이슈 (실적시즌 조건부)

| 기업 | 사실 내용 | 출처일자 | 출처+태그 |
|---|---|---|---|
| AAPL | DOJ와의 아이폰 반독점 소송 관련 초기 화해협상(early settlement talks) 진행 중이라는 보도, 애플은 올해 들어 DOJ에 복수의 화해안 제시 | 2026-07-17(최초 보도), 2026-07-20 재확인 보도 | Bloomberg(2026-07-17)/Claims Journal(2026-07-20) · [P2]/[P3] |
| TSLA | 2분기 인도량 480,126대(YoY +25%)로 사상 최대 2분기 인도 기록, 2년 만에 첫 YoY 인도량 증가. 2분기 실적은 금일(7/22) 장 마감 후 발표 예정 | 2026-07-21 보도 기준(인도량은 4월 발표분) | TradingKey · "Tesla (TSLA) Q2 Earnings Wednesday — 480K Deliveries..." · [P3] |
| MSFT | 신규 변동 없음 — 실적 발표 예정 7/29 | — | — |
| NVDA | AI 관련 이슈는 [5] 참고. 일반 이슈 신규 보도 미확인 | — | N/A |
| AMZN | 신규 변동 없음 — 실적 발표 예정 7/30 | — | — |
| GOOGL | 2분기 실적 발표 예정(7/22 장 마감 후) — 상세 컨센서스는 [5-A]·[8] 참고 | 2026-07-21 | TipRanks · [P3] |
| META | 신규 변동 없음 — 실적 발표 예정 7/29 | — | — |
| AVGO | AI 관련 이슈는 [5] 참고. 일반 이슈 신규 보도 미확인 | — | N/A |
| BRK(Berkshire) | 신규 변동 없음 — 관련 뉴스 검색 결과 확인되지 않음 | — | N/A |
| TSM | AI 관련 이슈는 [5] 참고(반도체 랠리 동반 상승). 일반 이슈 신규 보도 미확인 | — | N/A |

---

## [7] 기관·대형 자금 수급 (데일리)

| 항목 | 종목 | 사실 내용 | 규모(수치) | 출처+태그 |
|---|---|---|---|---|
| ETF 순유입(일간) | SOXX + SOXL(합산) | 반도체 ETF로 자금 쏠림 지속 | 합산 $21억 이상 유입(2026-07-20, 월요일 기준) | Benzinga · "Quick Spark: Semiconductor ETFs Dominate Inflows as SOXX, SOXL Pull In Over $2.1 Billion in One Day" · [P3] |
| ETF 순유입(참고, 기존 보도) | QQQ | 최근 세션 순유입 지속 | $13.7억 유입(정확 일자 특정 안됨, "최근 세션" 보도) | Yahoo Finance · "Daily ETF Flows: QQQ Notches Inflows of $2.4B" 기사 내 언급 · [P3] |
| 옵션/블록트레이드 | NVDA/AVGO 등 | 7/21 당일 특정 이상거래(unusual options activity) 구체 내역 검색으로 확인하지 못함 | N/A | N/A |

---

## [7-A] Insider Trading SEC Form 4

N/A — 금일(2026-07-21) 기준 NVDA·AVGO·CRDO·CLS·APLD·VRT·SMCI의 신규 Form 4 공시 확인되지 않음.

비고: 검색 중 발견된 관련 공시는 전부 7월 초 이전 시점으로 "신규" 요건에 해당하지 않아 제외함 — Celestica COO 지분처분(2026-07-02, RSU 베스팅 17,792주 중 세금분 8,605주 처분 및 9,187주 매도, 주당 $323.38), Super Micro CEO 배우자 관련 RSU 베스팅(2026-07-01), Applied Digital CEO Wes Cummins의 성과주식단위(PSU) 베스팅에 따른 80만주 취득·31.48만주 세금원천 처분(정확 일자 미상), NVIDIA 이사 Mark A. Stevens 관련 신탁의 88.5만주 매도(2026-06-18) — StockTitan/SecForm4.com 종합 · [P3]

---

## [8] 향후 14일 주요 일정 (2026-07-22 ~ 2026-08-05)

### 경제 일정

| 날짜 | 시각(ET·KST) | 이벤트 | 컨센서스 | 이전치 | 출처 |
|---|---|---|---|---|---|
| 2026-07-23(목) | 08:30 ET·21:30 KST | 신규 실업수당청구건수(주간) | N/A | N/A | 통상 발표 스케줄(BLS) · [P3] |
| 2026-07-24(금) | 10:00 ET·23:00 KST | 신규주택판매(New Residential Sales) | N/A | N/A | Census Bureau 발표 일정 · [P1] |
| 2026-07-27(월) | 08:30 ET·21:30 KST | 내구재수주 선행발표(Advance durable goods, 6월분) | N/A | N/A | Census Bureau 발표 일정 · [P1] |
| 2026-07-28~29 | 14:00 ET(29일)·익일 03:00 KST | FOMC 회의 및 금리 결정 발표 | 동결(hold) 우세(FedWatch 83.4%, 7/21 기준 보도) | 3.50~3.75% 유지(6월 회의) | Federal Reserve 공식 캘린더 · [P1] |
| 2026-07-30(목) | 08:30 ET·21:30 KST | 2분기 GDP 속보치(Advance Estimate) | N/A | N/A | BEA 공식 발표 일정(2026-07-30 08:30 ET 확인) · [P1] |
| 2026-08-03(월) | 10:00 ET·23:00 KST | ISM 제조업 PMI(8월 첫 영업일) | N/A | N/A | ISM 공식 발표 캘린더 통상 스케줄 · [P3] |
| 2026-08-05(수) | 10:00 ET·23:00 KST | ISM 서비스업 PMI | N/A | N/A | ISM 공식 발표 캘린더 통상 스케줄 · [P3] |

비고: 8/1(토)은 미국 영업일이 아니므로 ISM 제조업 발표는 다음 영업일인 8/3(월)로 표기함. 컨센서스·이전치 다수는 검색으로 확인되지 않아 N/A 처리. 7/30 PCE 물가지수 발표 여부는 금일 검색으로 재확인하지 못해 표에서 제외(직전 수집분에서도 대상월 상충으로 미확정이었음).

### 기업 일정

| 날짜 | 기업 | 이벤트 | 컨센서스 EPS | 컨센서스 매출 | 출처 |
|---|---|---|---|---|---|
| 2026-07-22(수) | Alphabet(GOOGL) | 2분기 실적 발표(장 마감 후) | $2.88(YoY +24.2%) | $1,170억(YoY +21%) | TipRanks/Yahoo Finance · [P3] |
| 2026-07-22(수) | Tesla(TSLA) | 2분기 실적 발표(장 마감 후, 콘퍼런스콜 17:30 ET) | $0.53(YoY +33%, non-GAAP) | 약 $264억 | TradingKey · [P3] |
| 2026-07-23(목) | Intel(INTC) | 2분기 실적 발표 | N/A | N/A | 24/7 Wall St · [P3] |
| 2026-07-24(금) | Verizon(VZ) | 2분기 실적 발표(웹캐스트 08:30 ET, 자료 07:00 ET 공개) | N/A | N/A | Verizon 공식 IR 보도자료(2026-06-26) · [P1] |
| 2026-07-27(월) | Celestica(CLS) | 2분기 실적 발표(장 마감 후), 콘퍼런스콜은 익일(7/28) 08:00 ET | N/A | N/A | Celestica 공식 IR 보도자료 · [P1] |
| 2026-07-28(화) | Coca-Cola(KO) | 2분기 실적 발표(장전, 콘퍼런스콜 08:30 ET) | N/A | N/A | Coca-Cola 공식 IR 보도자료 · [P1] |
| 2026-07-29(수) | Microsoft(MSFT), Meta(META) | 2분기 실적 발표 | N/A | N/A | 검색 요약(어닝 캘린더) · [P3] |
| 2026-07-30(목) | Apple(AAPL), Amazon(AMZN) | 실적 발표(Apple 3Q/6월분기, Amazon 2Q) | N/A | N/A | 검색 요약(어닝 캘린더) · [P3] |

---

## [9] 오늘의 사실 목록 (순위 없음)

- [1] S&P500 7,509.20 마감, +0.89%(3거래일 연속 하락 종료) · Yahoo Finance/CNBC [P2]
- [1] NASDAQ 종합 25,837.21 마감, +1.29% · 상동 [P2]
- [1] Dow Jones 52,224.64 마감, +385.38pt(+0.74%) · 상동 [P2]
- [1] Russell 2000 2,987.40 마감, +1.53% · 검색 결과 종합 [P3]
- [1] SOX 12,356.164 마감, +5.21%(메모리株 급등 주도) · Yahoo Finance/24-7 Wall St [P2]/[P3]
- [1] VIX 17.05 마감, -8.58% · Yahoo Finance [P2]
- [1] DXY 100.92, -0.03% · Trading Economics [P3]
- [1] Brent $91.10, +2.11%; WTI $83대 진입(정확 종가 N/A) · Trading Economics [P3]
- [1] Gold $4,082.73, +1.75%(FOMC 대기 속 $4,000 상회 유지) · Yahoo Finance [P2]
- [2] 10Y 국채금리 4.63%(+3bp), 2Y 4.255%(+4bp) · CNBC [P2]
- [2] CME FedWatch: 7/13 시점 "인상" 확률 46.5% 보도 vs 7/21 시점 "동결" 확률 83.4% 보도(시점 간 상충) · CNBC/Fool.com [P2]/[P3]
- [2] 다음 FOMC 회의 7/28~29, 금리 결정 발표 7/29 14:00 ET · Federal Reserve [P1]
- [3] 금일(7/21) CPI/PPI/GDP/Payrolls/실업률/신규실업수당청구/소매판매/ISM 발표 없음 · N/A
- [4] Danaher -13.7%(실적 서프라이즈에도 가이던스 하향), MSCI -10.7%(실적 미달), Genuine Parts -7.4%(이익전망 하향) · GuruFocus/TheStreet/Barchart [P2]/[P3]
- [4] Nebius +18.78%, 엔비디아 9.3% 지분(약 $50억) 보유 공시가 계기 · CNBC [P2]
- [4] Micron +12%, SanDisk +14%, AI 메모리 수요 랠리(BofA 마이크론 목표가 $1,550 상향) · Yahoo Finance [P2]
- [4] Intel +6%, RBC의 2분기 실적 서프라이즈 전망(실적 발표는 7/23) · 24/7 Wall St [P3]
- [5] 엔비디아, SEC 공시로 Nebius 지분 9.3%(워런트 포함, 평가액 약 $50억) 보유 공개, 워런트 행사는 9/11 이전 금지 · CNBC [P2]
- [5] AMD +4%, Broadcom +3%, 반도체 랠리 동반 상승 · 24/7 Wall St [P3]
- [5] 마이크론 HBM3E·HBM4 2026년 물량 완판 보도, DRAM·NAND 계약가 3분기 상승세(둔화된 속도) 지속 전망 · Tom's Hardware(TrendForce) [P3]
- [5-A] Alphabet 2분기 실적 금일(7/22) 장 마감 후 발표 예정, 컨센서스 EPS $2.88·매출 $1,170억 — 아직 미발표(발표 전 컨센서스치) · TipRanks [P3]
- [6] Apple, DOJ와 아이폰 반독점 소송 초기 화해협상 진행 중(7/17 최초 보도) · Bloomberg [P2]
- [6] Tesla 2분기 인도량 480,126대(YoY +25%, 사상 최대 2분기), 실적 발표는 금일(7/22) · TradingKey [P3]
- [7] SOXX+SOXL 합산 $21억 이상 일간 순유입(7/20 기준) · Benzinga [P3]
- [7-A] 대상 기업(NVDA·AVGO·CRDO·CLS·APLD·VRT·SMCI) 신규 Form 4 공시 확인되지 않음 · N/A
- [8] Alphabet·Tesla 2분기 실적 금일(7/22) 장 마감 후 발표 · TipRanks/TradingKey [P3]
- [8] FOMC 회의 7/28~29, 금리 결정 발표 7/29 14:00 ET · Federal Reserve [P1]
- [8] 2분기 GDP 속보치 7/30 08:30 ET 발표 예정(BEA 공식 확인) · BEA [P1]
- [8] Intel 실적 7/23, Verizon 7/24, Celestica 7/27(콜 7/28), Coca-Cola 7/28, Microsoft·Meta 7/29, Apple·Amazon 7/30 · 각사 IR/검색 종합 [P1]/[P3]
