# 미국 시장 데일리 수집 결과 (Collect)
# 기준일: 2026-09-25 (금요일) · 미국 정규장 종가 기준 · 실행모드: 데일리
# 생성시각(KST): 2026-09-27 07:20

## [1] 미국 주요 지수 〔데일리〕

| 항목 | 종가/수치 | 등락률 | (보도된) 원인 | 출처+태그 |
|------|-----------|--------|----------------|-----------|
| S&P500 | 7,743.41 | +0.51% | 유가 하락(호르무즈 해협 재개 협상 기대)이 국채금리 급등세를 진정시키며 한 주간 변동성 장세를 마무리, 3주 만에 주간 기준 상승 마감 | TheStreet · "Stock Market Today (Sept. 25, 2026): S&P 500 and Nasdaq end the week higher as fresh tech optimism lifts market" · 2026-09-25 (ET) · https://www.thestreet.com/stock-market-today/stock-market-today-dow-jones-sp-500-nasdaq-updates-sept-25-2026 [P3] |
| NASDAQ Composite | 27,068.72 (+129.34pt) | +0.48%~+0.5%(매체별 소폭 상이) | 상동. AI 관련주 재매수세 유입 | CNBC 보도 인용(위 STL.News 재인용) · "U.S. Stocks End Higher After Volatile Week" · 2026-09-26 (ET) · https://www.stl.news/u-s-stocks-end-higher-after-volatile-week-sept-26/ [P3] |
| Dow Jones | 51,828.62 (+478.64pt) | +0.93% | 상동(유가 하락 + 국채금리 진정). 3주 연속 주간 하락 흐름 종료 | 상동 [P3] |
| Russell 2000 | 2,835.57 부근 (-3.09pt) | -0.11% | 개별 보도 원인 명시 없음 | TheStreet · 상동 · 2026-09-25 (ET) [P3] |
| SOX (필라델피아 반도체지수) | N/A | N/A | 확인 필요 — 검색으로 2026-09-25 종가 확정 실패(AMD +9.9%·NVDA +2.3%·Applied Materials +2.3%·Lam Research +2.6% 등 개별 종목 상승은 보도되었으나 지수 종가 수치 미확인) | [N/A] |
| Brent (리스크 참고) | $104.37 | -2.09% | 미국-이란 호르무즈 해협 탱커 봉쇄 해제 관련 단계적 협상 기대로 하락 | Fortune · "Current price of oil as of September 25, 2026" · 2026-09-25 (ET) · https://fortune.com/article/price-of-oil-09-25-2026/ [P3] |

## [1-A] 선물·변동성 구조 〔검색 금지 — 0_data.md에서 그대로 옮김〕

### 선물 (한국 아침 시점)

| 항목 | 심볼 | 현재가/종가 | 전일 대비 | 직전 종가 | 기준시각(ET) |
|------|------|-------------|-----------|-----------|--------------|
| S&P500 선물 (ES) | ES=F | 7,803.75 | +0.47% | 7,767 | 2026-09-25 16:59 |
| 나스닥100 선물 (NQ) | NQ=F | 30,889.25 | +0.40% | 30,766.75 | 2026-09-25 17:00 |
| 다우 선물 (YM) | YM=F | 52,163 | +0.86% | 51,717 | 2026-09-25 16:59 |
| 러셀2000 선물 (RTY) | RTY=F | 2,859.3 | +0.09% | 2,856.8 | 2026-09-25 16:59 |

### 변동성 구조

| 항목 | 심볼 | 현재가/종가 | 전일 대비 | 직전 종가 | 기준시각(ET) |
|------|------|-------------|-----------|-----------|--------------|
| VIX (30일) | ^VIX | 14.87 | -5.11% | 15.67 | 2026-09-25 16:15 |
| VIX9D (9일) | ^VIX9D | 12.76 | -9.57% | 14.11 | 2026-09-25 16:15 |
| VIX3M (3개월) | ^VIX3M | 17.93 | -2.71% | 18.43 | 2026-09-25 16:15 |
| VVIX (VIX의 변동성) | ^VVIX | 87.84 | -3.01% | 90.57 | 2026-09-25 16:15 |
| SKEW (테일리스크) | ^SKEW | 144.91 | -0.77% | 146.04 | 2026-09-25 17:00 |

### 매크로 (참고: DXY·금·WTI)

| 항목 | 심볼 | 현재가/종가 | 전일 대비 | 직전 종가 | 기준시각(ET) |
|------|------|-------------|-----------|-----------|--------------|
| 미 10년 국채선물 | ZN=F | 104.97 | +0.10% | 104.86 | 2026-09-25 16:59 |
| 금 | GC=F | 4,321.2 | +0.54% | 4,298 | 2026-09-25 16:59 |
| WTI | CL=F | 92.41 | -2.33% | 94.61 | 2026-09-25 16:59 |
| 달러지수 (DXY) | DX-Y.NYB | 101.04 | -0.25% | 101.29 | 2026-09-25 16:59 |

### VIX 기간구조 (위 수치에서 산출한 비율)

| 비율 | 값 | 구조 |
|------|----|------|
| VIX3M / VIX | 1.206 | 콘탱고 |
| VIX / VIX9D | 1.165 | 콘탱고 |

### Put/Call 비율 (CBOE 옵션 체인 직접 집계)

| 대상 | P/C (거래량) | P/C (미결제약정) | 콜 거래량 | 풋 거래량 | 집계 계약수 |
|------|--------------|------------------|-----------|-----------|-------------|
| S&P500 지수옵션 (SPX) | 1.344 | 1.391 | 614,553 | 825,768 | 29,206 |
| 나스닥100 ETF 옵션 (QQQ) | 0.984 | 1.405 | 4,386,939 | 4,317,399 | 11,710 |

출처: CBOE / CME (Yahoo chart API 자동수집) [P1]

> 참고: 위 값은 CBOE 지연시세 기준 직전 정규장(2026-09-25 금요일) 집계값이며, 주말(9/26~9/27)에는 정규장이 없어 값이 그대로 유지됨(오류 아님).

## [2] 금리 / 연준 〔데일리〕

| 항목 | 사실 내용(발언·수치) | 출처+태그 |
|------|----------------------|-----------|
| 10년물 국채수익률 | 2026-09-25(금) 종가 기준 5.17% | Seeking Alpha · "Treasury Yields Snapshot: September 25, 2026" · 2026-09-25 (ET) · https://seekingalpha.com/article/4949891-treasury-yields-snapshot-september-25-2026 [P3] |
| 2년물 국채수익률 | 2026-09-25(금) 종가 기준 4.81% | 상동 [P3] |
| 10Y-2Y 스프레드 | 산술값 +0.36%p (5.17% - 4.81%) | 자체 산출 (상동 수치 기반) [P3] |
| CME FedWatch (10/28 FOMC) | 2026-09-25 기준, 10월 28일 차기 FOMC에서 25bp 추가 인상 확률 75.8% | CME Group FedWatch Tool 집계 인용 (growbeansprout.com 재게시) · 2026-09-25 기준 [P3] |
| 9월 FOMC 결정 (배경, 9/16) | 연준은 2026-09-16 FOMC에서 기준금리를 25bp 인상해 3.75~4.00%로 결정(12-0 만장일치) | CNBC · "Fed approves interest rate hike, signals one more to come this year" · 2026-09-16 (ET) [P2] |
| Trump 발언 (유가 관련, 배경) | Trump는 "이란 전쟁은 11월 중간선거 이후 곧 끝날 것"이며 "그때 유가가 크게 떨어질 것"이라고 발언 | CNBC · "Trump sees Iran war ending soon after midterm elections, predicts oil prices will then fall sharply" · 2026-09-12 (ET) · https://www.cnbc.com/2026/09/12/trump-sees-iran-war-ending-very-soon-oil-prices-then-falling.html [P2] |

> 주말(9/26~9/27) 중 Fed 위원의 신규 공개 발언은 검색으로 확인되지 않음 — N/A.

## [3] 주요 경제지표 〔조건부〕

N/A — 2026-09-26(토)·09-27(일) 주말로 신규 경제지표 발표 없음.

참고(배경, 9/25 금요일 발표분, 이미 직전일 리포트에 기재됨):

| 지표 | 발표시각(ET) | 발표치 | 예상치 | 이전치 | 출처 |
|------|--------------|--------|--------|--------|------|
| 내구재수주 (8월) | 2026-09-25 08:30 ET | 0.0%(전월비 변화 없음) | -0.4% | +0.9%(7월, 수정치) | Investing.com Economic Calendar · 2026-09-25 [P3] |
| 미시간대 소비자심리지수 (확정치, 9월) | 2026-09-25 10:00 ET | 48.1 | N/A | 51.7(8월) | TradingEconomics · "US Consumer Sentiment at a Four-Month Low in September" · 2026-09-25 [P3] |

## [4] 특징 종목 〔데일리〕

주말(9/26~9/27)이라 정규장 신규 ±5% 변동 종목 없음(N/A). 단, 9/26(금 ET) 장중 보도된 아래 개별 기업 뉴스는 익영업일 주가에 영향 가능성이 있어 사실만 기재:

| 종목 | 티커 | 등락률 | 거래량 | (보도된) 핵심 사실 | 출처+태그 |
|------|------|--------|--------|----------------------|-----------|
| Apple | AAPL | 확인 필요(장후 뉴스, 당일 주가 영향 미확인) | 확인 필요 | 미국 캘리포니아 샌디에이고 연방배심원단이 Apple이 Taction Technology의 햅틱(진동) 특허 2건(US10,659,885, US10,820,117)을 침해했다고 판단, 배상금 57억 달러 이상 평결. Apple의 "Taptic Engine"이 대상 기술로 지목됨. Apple은 "평결과 배상액에 강하게 동의하지 않는다"며 항소 계획을 밝힘. 배심원은 고의침해는 인정하지 않음 | CNBC · "Apple faces $5.7 billion patent infringement verdict over iPhone and Apple Watch haptics" · 2026-09-26 10:55 (ET) · https://www.cnbc.com/2026/09/26/apple-taction-technology-patent-infringement-verdict.html [P2] |

## [4-A] 섹터별 뉴스 〔0_data.md의 Finnhub 섹터 뉴스에서 선별〕

| 섹터 | 종목 | 사실 내용(무슨 일이) | 발행시각(ET) | 출처+태그 |
|------|------|------------------------|--------------|-----------|
| 반도체·AI | NVDA | Oracle의 데이터센터 프로젝트 force majeure 통지가 "AI 데이터센터 투자논리"에 미치는 영향을 다룬 해설기사 게재 | 2026-09-26 15:20 | Yahoo(Finnhub 수집) · "Here's How Oracle's 'Force Majeure' Changes the AI Data Center Thesis" [P3] |

> 금융·에너지·헬스케어·소비재유통 섹터의 나머지 Finnhub 뉴스(JPM 관련 인력이동·소비트렌드 해설, XOM 관련 정유마진 칼럼, UNH 관련 ETF비중 해설, AMZN 관련 종목추천 칼럼 등)는 당일 주가·거래량 급변과 직접 연결되는 속보성 사실이 확인되지 않아 제외 — N/A 처리. AMZN의 "Anthropic 관련 AWS 데이터센터 이란 드론 공격" 제목 기사는 원문 사실관계(공격 발생 여부·피해규모) 자체가 타 매체로 교차검증되지 않아 이 단계에서는 채택하지 않음(추가 검증 필요, [N/A]).

## [5] AI 인프라 — 공급 측 〔데일리〕

배경 참고(9/24, 직전 리포트 기재분 — 신규 아님):

| 기업 | 뉴스 제목 | 사실 내용(무슨 일이) | 출처일자 | 출처+태그 |
|------|-----------|------------------------|-----------|-----------|
| Oracle | Project Jupiter 데이터센터 force majeure | Oracle이 뉴멕시코 'Project Jupiter' 데이터센터(약 $165B 프로젝트) 개발사(Blue Owl 자회사 Stack Infrastructure)에 전력 공급 확보 지연을 이유로 force majeure 통지 발송. Oracle은 임대계약 해지 불가, 2028년 가동 지연시 지급 지연 여지 확보 목적으로 해석 보도. Blue Owl은 "재무적 약정에는 변화 없다"고 언급 | 2026-09-24 | Yahoo Finance · "Oracle triggers 'force majeure' on data center project over power delays, source says" · 2026-09-24 (ET) [P3] |

> 주말(9/26~9/27) 중 NVDA/AVGO/AMD/TSM/ANET/CRDO/CLS/VRT/SMCI/APLD 관련 신규 공급측 뉴스(수주·데이터센터·가이던스·M&A)는 검색으로 확인되지 않음 — N/A.

## [5-A] AI 인프라 — 수요 측/하이퍼스케일러 CAPEX 〔실적시즌 아니면 1줄 처리〕

신규 변동 없음 — 직전 가이던스 유지(메가캡 3분기 실적은 2026-10-27~10-29 주간 집중 예정, 업계 일정 취합 보도 기준 [P3]).

## [6] 시총 상위 10 — AI 무관 일반 이슈 〔이슈 있을 시〕

| 기업 | 사실 내용 | 출처일자 | 출처+태그 |
|------|-----------|-----------|-----------|
| Apple (AAPL) | 샌디에이고 연방배심원단, Taction Technology의 햅틱 특허 침해 관련 57억 달러 이상 배상 평결(상세는 [4] 참조) | 2026-09-26 (ET) | CNBC · "Apple faces $5.7 billion patent infringement verdict over iPhone and Apple Watch haptics" · 2026-09-26 10:55 (ET) [P2] |

> MSFT·NVDA·AMZN·GOOGL·META·AVGO·BRK·TSLA·TSM 관련 주말 중 AI무관 신규 일반이슈는 검색으로 확인되지 않음 — N/A.

## [7] 기관·대형 자금 수급 〔데일리〕

주말(9/26~9/27) 중 신규 블록딜·ETF자금흐름 공시·옵션 이상거래는 검색으로 확인되지 않음 — N/A.

## [7-A] Insider Trading (SEC Form 4) 〔신규공시 있을 시〕

N/A — Form 4 신규 공시 없음(주말 SEC EDGAR 신규 제출 확인 안 됨).

## [8] 향후 14일 주요 일정 〔변동 있을 시〕

직전 리포트([logs/2026-09-26/1_collect.md])와 비교해 큰 일정 변동 없음 — 생략. (10/2 비농업고용지표, 10/10 PPI, 10/14 CPI, 10/27~10/28 FOMC 등 기존 일정 유지, 출처: FedRateCalc·Federal Reserve 공식 일정 [P1][P3])

## [9] 오늘의 사실 목록 (순위 없음) 〔데일리〕

- [1] S&P500 7,743.41 (+0.51%) · TheStreet [P3]
- [1] NASDAQ 27,068.72 (+129.34pt, +0.48~0.5%) · CNBC/STL.News [P3]
- [1] Dow 51,828.62 (+478.64pt, +0.93%), 3주 연속 주간 하락 흐름 종료 · CNBC/STL.News [P3]
- [1] Russell 2000 2,835.57 부근 (-0.11%) · TheStreet [P3]
- [1] SOX 종가 확인 불가 · [N/A]
- [1] Brent $104.37 (-2.09%), 호르무즈 해협 협상 기대로 하락 · Fortune [P3]
- [1-A] ES선물 7,803.75(+0.47%), NQ 30,889.25(+0.40%), YM 52,163(+0.86%), RTY 2,859.3(+0.09%) · Yahoo chart API [P1]
- [1-A] VIX 14.87(-5.11%), VIX9D 12.76(-9.57%), VIX3M 17.93(-2.71%), VVIX 87.84(-3.01%), SKEW 144.91(-0.77%) · CBOE/CME [P1]
- [1-A] VIX3M/VIX 1.206(콘탱고), VIX/VIX9D 1.165(콘탱고) · 산출값 [P1]
- [1-A] SPX P/C 거래량 1.344, 미결제 1.391 / QQQ P/C 거래량 0.984, 미결제 1.405 · CBOE [P1]
- [2] 10년물 국채수익률 5.17%, 2년물 4.81%, 스프레드 +0.36%p · Seeking Alpha [P3]
- [2] CME FedWatch, 10/28 FOMC 25bp 추가 인상 확률 75.8%(2026-09-25 기준) · CME Group [P3]
- [2] 연준은 2026-09-16 FOMC에서 25bp 인상해 3.75~4.00%로 결정(12-0 만장일치) · CNBC [P2]
- [3] 금일(주말) 신규 경제지표 발표 없음 · N/A
- [3] (배경) 8월 내구재수주 0.0%(예상 -0.4%), 9월 미시간대 소비자심리 확정치 48.1(8월 51.7) · Investing.com/TradingEconomics [P3]
- [4] Apple(AAPL), Taction Technology 햅틱 특허소송에서 57억달러 이상 배상 평결, 항소 예정 · CNBC [P2]
- [4-A] Oracle 데이터센터 force majeure가 AI 데이터센터 투자논리에 미치는 영향 해설기사 게재 · Yahoo(Finnhub) [P3]
- [5] (배경) Oracle, 뉴멕시코 Project Jupiter 데이터센터에 force majeure 통지(전력 지연 사유, 9/24) · Yahoo Finance [P3]
- [5-A] 메가캡 3분기 실적시즌은 10/27~10/29 집중, 현재 비실적시즌으로 직전 가이던스 유지 · 업계 일정 취합 [P3]
- [6] Apple, 특허소송 57억달러 배상 평결(AI무관 일반이슈) · CNBC [P2]
- [7] 주말 중 신규 기관수급 뉴스 확인 안 됨 · N/A
- [7-A] 주말 중 신규 Form 4 공시 없음 · N/A
- [8] 기존 일정(10/2 고용지표, 10/10 PPI, 10/14 CPI, 10/27~10/28 FOMC) 변동 없음 · FedRateCalc/Federal Reserve [P3][P1]
