# 미국 시장 데일리 수집 결과 (Collect)
# 기준일: 2026-07-27 (월) · 미국 정규장 종가 기준 · 실행모드: 실적시즌(빅테크 Q2 2026 어닝시즌, [5-A]/[6] 활성화)
# 생성시각(KST): 2026-07-28 09:30

---

## [1] 미국 주요 지수 + 리스크 지표

| 항목 | 종가/수치 | 등락률 | (보도된) 원인 | 출처+태그 |
|---|---|---|---|---|
| S&P500 | 7,413.18 | +0.02% (+1.20pt) | 미국-이란 공습 중단으로 유가 급락, 위험자산 안도랠리 vs 반도체 약세가 상쇄 | Bloomberg · "Oil Tumbles as US and Iran Pause Military Strikes: Markets Wrap" · 2026-07-27 · https://www.bloomberg.com/news/articles/2026-07-26/oil-tumbles-as-us-and-iran-pause-military-strikes-markets-wrap [P2] |
| NASDAQ종합 | 24,932.08 | -0.18% | 엔비디아(NVDA) 약 5% 급락이 지수 하방 압력, 반도체 전반 약세 | The Motley Fool · "Stock Market Today, July 27: Dow Rises on Oil Retreat, and Sandisk Plunges 11% on Memory Weakness" · 2026-07-27 · https://www.fool.com/coverage/stock-market-today/2026/07/27/stock-market-today-july-27-dow-rises-on-oil-retreat-and-sandisk-plunges-11-on-memory-weakness/ [P2] |
| Dow | 52,210.08 | +0.51% (+262.83pt) | 유가 급락으로 항공/운송/소비재 강세, 애플 +3.5%가 지수 견인 | AP(KTVB) · "How major US stock indexes fared Monday 7/27/2026" · 2026-07-27 · https://www.ktvb.com/article/syndication/associatedpress/how-major-us-stock-indexes-fared-monday-7272026/616-25fbc4e4-9b71-4394-ba41-69d568d1a50a [P2] |
| Russell2000 | 2,948.03 | +0.60% (+18.04pt) | 소형주 상대적 강세, 유가 하락에 따른 비용 부담 완화 보도 | AP(KTVB) · "How major US stock indexes fared Monday 7/27/2026" · 2026-07-27 · 상동 URL [P2] |
| SOX(필라델피아반도체) | N/A (등락률만 확인) | -2.23% | 엔비디아·AMD 등 반도체 대형주 동반 급락 | TradingKey · "NVIDIA Corp Stock (NVDA) Moved Down by 3.46% on Jul 27: Key Drivers Unveiled" 관련 보도 종합 · 2026-07-27 · https://www.tradingkey.com/news/market-movers/262056606-market-movers-nvda-20260727 [P3] — 정확 종가 포인트 확인 필요 |
| 선물 ES(S&P500 선물) | N/A | N/A | 한국 아침(2026-07-28) 시점 실시간 선물 수치 검색 검증 실패 | N/A — 확인 필요 [N/A] |
| 선물 NQ(나스닥100 선물) | N/A | N/A | 한국 아침(2026-07-28) 시점 실시간 선물 수치 검색 검증 실패 | N/A — 확인 필요 [N/A] |
| VIX | 18.58 | +0.64% | 유가 급락에 따른 안도랠리 속에서도 반도체 변동성 반영, 소폭 상승 | The Globe and Mail(AP 신디케이션) · "Stock Market News for July 27, 2026" · 2026-07-27 · https://www.theglobeandmail.com/investing/markets/stocks/META/pressreleases/3481300/stock-market-news-for-july-27-2026/ [P3] |
| DXY(달러인덱스) | 101.1844 | -0.28% | 확인된 개별 보도 없음(수치만 확인) | TradingEconomics · "United States Dollar" · 2026-07-27 · https://tradingeconomics.com/united-states/currency [P3] |
| WTI | $82.62/bbl | -8.68% | 미국-이란 공습 상호 중단 합의로 지정학적 리스크 프리미엄 급격히 해소 | Bloomberg · "Oil Tumbles as US and Iran Pause Military Strikes: Markets Wrap" · 2026-07-27 · https://www.bloomberg.com/news/articles/2026-07-26/oil-tumbles-as-us-and-iran-pause-military-strikes-markets-wrap [P2] |
| Brent | $90.28/bbl | -8.23% | 상동(미국-이란 공습 중단, 2주 가까운 대이란 공습 이후 일시 중단) | Bloomberg · 상동 · 2026-07-27 · 상동 URL [P2] |
| Gold | $4,077.21/toz | +0.62% | 이란 관련 충돌 완화 속 안전자산 수요 지속 보도 | Yahoo Finance · "Gold prices today, Monday, July 27, 2026: Gold prices see positive traction as fighting with Iran has paused" · 2026-07-27 · https://finance.yahoo.com/personal-finance/investing/article/gold-prices-today-monday-july-27-2026-gold-prices-see-positive-traction-as-fighting-with-iran-has-paused-123327127.html [P3] |

비고: ES·NQ 한국 아침 시점 선물 수치는 신뢰 가능한 출처로 검증되지 않아 N/A 처리함. SOX 정확한 종가 포인트는 지수 제공사(Nasdaq OMX/Cboe) 1차 확인 필요.

---

## [2] 금리/연준

| 항목 | 사실 내용(발언·수치) | 출처+태그 |
| --- | --- | --- |
| FOMC 일정 | FOMC는 2026-07-28~29 이틀간 회의 진행, 정책성명 발표는 2026-07-29(수) 14:00 ET(2026-07-30 03:00 KST). 이번 회의는 경제전망(SEP)·점도표 미포함 | Kiplinger · "July Fed Meeting: Live Updates and Commentary" · 2026-07 · https://www.kiplinger.com/investing/live/fed-meeting-updates-and-commentary-july-2026 [P3] |
| 현재 기준금리 목표범위 | 3.50%~3.75% (2026-06 FOMC에서 동결 유지, 인플레이션이 2% 목표 대비 여전히 높다고 언급) | employamerica.org · "July 2026 FOMC Preview (Public)" · 2026-07 · https://www.employamerica.org/fomc-meetings/july-2026-fomc-preview-public/ [P3] |
| 10년물 국채금리 | 4.64% (전 거래일 대비 -0.04%p) | TradingEconomics · "US 10 Year Treasury Note Yield" · 2026-07-27 · https://tradingeconomics.com/united-states/government-bond-yield [P3] |
| 2년물 국채금리 | N/A — 검색 검증 실패(2026-07-27 종가 수치 미확인) | N/A [N/A] |
| 10Y-2Y 스프레드 | N/A — 2년물 미확인으로 산출 불가 | N/A [N/A] |
| CME FedWatch (2026-07-29 FOMC 결과 확률, 2026-07-28 기준 최신치) | 동결 확률 97.4%, 25bp 인하 확률 2.6% (2026-07-23~24 시점에는 동결 65.3% / 인상 34.7%로 보도되어 주중 확률 변동 있었음) | growbeansprout.com "US Fed Funds Interest Rate: Latest Updates and Trends" 종합 · 2026-07-28 기준 · https://growbeansprout.com/tools/fedwatch [P3] — CME 공식 페이지 직접 확인 필요 |

---

## [3] 주요 경제지표

`N/A — 금일(2026-07-27~28) CPI·Core CPI·PPI·GDP·Payroll·실업률·실업수당·소매판매·ISM 제조/서비스 발표 없음.`

비고: Conference Board 소비자신뢰지수(Consumer Confidence)가 2026-07-28 10:00 ET(23:00 KST)에 발표 예정이나, 스펙상 조건부 수집 대상 지표 목록(CPI/PPI/GDP/Payroll/실업률/실업수당/소매판매/ISM)에 포함되지 않아 본 섹션에서는 제외하고 [8]에 별도 명기함.

---

## [4] 특징 종목

| 종목 | 티커 | 등락률 | 거래량 | (보도된) 핵심 사실 | 출처+태그 |
|---|---|---|---|---|---|
| SanDisk | SNDK | -11.85% | 급증(구체적 수치 미확인) | 중국 메모리 경쟁사 창신(ChangXin Technology) 상하이 IPO(86억 달러 규모, 상장 첫날 +466%)로 메모리 공급 경쟁 우려 부각, 메모리 가격 상승 속도 둔화 우려 및 8/5 실적 발표 앞둔 차익실현 매물 보도 | The Motley Fool · "Why Sandisk Stock Crashed on Monday" · 2026-07-27 · https://www.fool.com/investing/2026/07/27/why-sandisk-stock-crashed-on-monday/ [P2] |
| Seagate | STX | -7% | N/A | SanDisk와 동반 약세, 메모리 공급과잉 우려 보도 | Yahoo Finance · "SanDisk Sinks 11%, Seagate Falls 7%, Micron Slides 4% on Memory Supply-Glut Fears" · 2026-07-27 · https://finance.yahoo.com/markets/stocks/articles/sandisk-sinks-11-seagate-falls-160250009.html [P2] |
| Apple | AAPL | +3.5%(CNBC) / 다른 보도는 +0.96~1% 상이 보도 | N/A | 엔비디아 시가총액 하락 속 애플이 세계 시가총액 1위 기업 지위 탈환(시총 약 $4.94~4.95조) | CNBC · "Apple ends day as world's most valuable company, passing Nvidia" · 2026-07-27 · https://www.cnbc.com/2026/07/27/apple-most-valuable-company-nvidia.html [P2] — 등락률 수치는 매체별 상이(+0.96%~+3.5%), 대표출처(CNBC) 기준과 병기 |

비고: NVDA·AMD는 AI인프라 공급 측 전담 종목으로 [5]에서 다룸(중복 배제).

---

## [5] AI 인프라 — 공급 측

| 기업 | 뉴스 제목 | 사실 내용 | 출처일자 | 출처+태그 |
|---|---|---|---|---|
| NVDA | Nvidia drops nearly 5%, leading chip stocks lower amid renewed worries of circular financing | 엔비디아가 OpenAI의 미국 데이터센터 프로젝트 컴퓨팅 파워 리스 관련 최대 2,500억 달러 자금 보증(backstop)을 논의 중이라는 보도로 "순환금융(circular financing)" 우려 재점화, 주가 5% 하락(종가 $196.51 부근, 타 보도는 $201.38도 병기) | 2026-07-27 | Yahoo Finance · "Nvidia drops nearly 5%, leading chip stocks lower amid renewed worries of circular financing" · 2026-07-27 · https://finance.yahoo.com/markets/article/nvidia-drops-nearly-5-leading-chip-stocks-lower-amid-renewed-worries-of-circular-financing-193309793.html [P2] |
| NVDA | SK Group and NVIDIA Expand Strategic Partnership Across AI Factories and Next-Generation Memory | SK그룹과 5,000억 달러 이상 규모 협력 의향서(LOI) 체결 — SK텔레콤의 2GW급 AI데이터센터(Vera Rubin 플랫폼 기반, 1단계 2027년 가동 목표), SK하이닉스와 차세대 HBM4 공동개발 확대 | 2026-07-25 | NVIDIA Newsroom · "SK Group and NVIDIA Expand Strategic Partnership Across AI Factories and Next-Generation Memory" · 2026-07-25 · https://nvidianews.nvidia.com/news/sk-group-and-nvidia-expand-strategic-partnership-across-ai-factories-and-next-generation-memory [P1] |
| AMD | AMD Stock Heads to $450 after Breaking $500 as Pre-Earnings Chip Sector Weakness Intensifies | AMD 주가 5%대 하락(보도별 -3.39%~-5.17% 상이), 실적 발표를 앞두고 반도체 섹터 전반 약세 속 동반 하락 | 2026-07-27 | FX Leaders · "AMD Stock Heads to $450 after Breaking $500 as Pre-Earnings Chip Sector Weakness Intensifies" · 2026-07-27 · https://www.fxleaders.com/news/2026/07/27/amd-stock-heads-to-450-after-breaking-500-as-pre-earnings-chip-sector-weakness-intensifies/ [P3] |
| AVGO | Broadcom AI 반도체 백로그·수주 잔고 | 브로드컴 CEO 훅 탄(Hock Tan)이 FY2027까지 AI 반도체 매출 1,000억 달러 이상 목표 제시, 약 730억 달러 AI 백로그 및 구글·메타·OpenAI·Anthropic 대상 다년 커스텀 ASIC 계약 언급. Q2 2026 매출 222억 달러(+47.87% YoY), AI 반도체 매출 108억 달러(+143% YoY) | 2026-07 (Q2 실적 발표 기준, 정확 발표일 확인 필요) | 종합 보도(Seeking Alpha/StockTitan 등) [P3] — 브로드컴 IR 1차 공시(어닝콜 트랜스크립트) 확인 필요 |
| AVGO | OpenAI·Broadcom 커스텀 칩 "Jalapeño" | OpenAI 자체 설계 첫 추론용 커스텀 가속기 "Jalapeño"를 브로드컴과 공동개발, 설계~테이프아웃 9개월 소요 | 확인 필요(2026-07 이전 보도 다수, 정확 일자 미확인) | N/A — 정확 발표일 확인 필요 [N/A] |
| TSM | TSMC Q2 2026 실적 및 가이던스 | TSMC Q2(4-6월) 매출 가이던스 390억~402억 달러(전년比 약 32% 성장), Q1 매출 359억 달러(+41% YoY), 총마진 66.2%. 2026년 연간 매출 성장률 30% 이상(달러 기준) 유지, 2나노 양산 진전·첨단 패키징 확장 언급 | 2026-07-16(실적 발표일) | The Motley Fool · "Taiwan Semiconductor Reports Earnings July 16. Here's What to Watch." · 2026-07-13(사전) 및 실적 발표 종합 [P3] — TSMC IR 공식 발표자료 1차 확인 필요 |
| — (메모리 공급망 전반) | AI 서버향 DRAM·NAND·HBM4 공급 부족 | 마이크론 CEO가 DRAM(HBM 포함) 수요-공급 격차가 사상 최대라고 언급, 2026년 전체 HBM 생산량에 대한 가격·물량 계약 완료. Q1 2026 DRAM 계약가 전분기 대비 90~95%, NAND 55~60% 상승. 삼성·SK하이닉스·마이크론 HBM4 검증 완료, 엔비디아 Rubin 플랫폼向 배치 예정 | 2026-07 (구체 발표일 확인 필요) | Astute Group / TrendForce 등 종합 보도 [P3] — 개별 기업 IR 1차 확인 필요 |

비고: CRDO(Credo)·ANET(Arista)·CLS(Celestica)·VRT(Vertiv)·SMCI·APLD는 검색상 애널리스트 코멘트·투자의견 성격 보도가 대부분으로, "보도된 사실"(수주·가이던스·M&A 등 확정 사실) 기준을 충족하는 항목이 제한적이었음. Celestica는 2026-07-28 장 마감 후 Q2 실적 발표 예정(사실은 [8] 일정표에 기재, 결과 자체는 발표 전이라 N/A).

---

## [5-A] AI 인프라 — 수요 측/하이퍼스케일러 CAPEX (실적시즌 활성화)

| 항목 | 사실 내용(발표 수치·문구) | 전분기 대비(산술) | 출처일자 | 출처+태그 |
|---|---|---|---|---|
| Alphabet(GOOGL) 2026년 연간 Capex 가이던스 | 195억~205억 달러 상향(기존 가이던스 180억~190억 달러에서 상향) *단위 원문 확인: 회사는 "$195-205 billion"으로 발표 | 가이던스 상단 기준 +약 150억 달러 (기존 190억→신규 205억, 단위: 십억 달러) | 2026-07-22(Q2 실적 발표일) | CNBC · "Alphabet earnings takeaways: Q2 revenue beats, GOOGL stock sinks on 2026 capex hike" · 2026-07-22 · https://www.cnbc.com/2026/07/22/google-earnings-q2-goog-live-updates.html [P2] |
| Alphabet Q2 2026 실제 Capex 집행액 | 449억 달러 기술 인프라 투자, 이 중 약 60%는 서버, 40%는 데이터센터·네트워킹 장비 | N/A(전분기 수치 미확인) | 2026-07-22 | Investing.com · "Alphabet Q2 2026 slides: 24% revenue growth, cloud surges despite capex" · 2026-07-22 · https://www.investing.com/news/company-news/alphabet-q2-2026-slides-24-revenue-growth-cloud-surges-despite-capex-93CH-4807148 [P2] |
| Microsoft(MSFT) | 신규 실적 미발표 — 2026-07-29(수) 장마감 후 FY2026 Q4 실적 발표 예정. 신규 변동 없음 — 직전 가이던스 유지 | — | 직전 공시 기준(정확 일자 확인 필요) | N/A — 차기 실적 발표(2026-07-29) 전까지 직전 가이던스 유지 [N/A] |
| Amazon(AMZN) | 신규 실적 미발표 — 2026-07-30(목) 장마감 후 Q2 실적 발표 예정. 신규 변동 없음 — 직전 가이던스 유지 | — | 직전 공시 기준(정확 일자 확인 필요) | N/A — 차기 실적 발표(2026-07-30) 전까지 직전 가이던스 유지 [N/A] |
| Meta(META) | 신규 실적 미발표 — 2026-07-29(수) 장마감 후 Q2 실적 발표 예정. 신규 변동 없음 — 직전 가이던스 유지 | — | 직전 공시 기준(정확 일자 확인 필요) | N/A — 차기 실적 발표(2026-07-29) 전까지 직전 가이던스 유지 [N/A] |

---

## [6] 시총 상위 10 — AI 무관 일반 이슈 (실적시즌 활성화)

| 기업 | 사실 내용 | 출처일자 | 출처+태그 |
|---|---|---|---|
| Apple(AAPL) | 엔비디아 시가총액 하락 속 세계 시가총액 1위 기업 지위 탈환(시총 약 $4.94~4.95조, 2025년 4월 이후 처음) | 2026-07-27 | CNBC · "Apple ends day as world's most valuable company, passing Nvidia" · 2026-07-27 · https://www.cnbc.com/2026/07/27/apple-most-valuable-company-nvidia.html [P2] |
| Alphabet(GOOGL) | EU 사법재판소, 안드로이드 반독점 소송에서 41억 유로(약 47억 달러) 과징금 관련 구글 항소 기각(2026-07-02) — 8년간 이어진 법적 분쟁 사실상 종료. 별도로 스웨덴 법원이 구글에 클라란(Klarna) 관련 반독점 손해배상 19.7억 달러 지급 명령(2026-07-01) | 2026-07-02 / 2026-07-01 | CNBC · "Google loses fight over record $4.7 billion EU antitrust fine" · 2026-07-02 · https://www.cnbc.com/2026/07/02/alphabet-google-android-eu-antitrust-fine-4-1-billion-euro-appeal.html [P2] |
| Broadcom(AVGO) | 삼성전자와 첨단 칩·패키징 관련 2,000억 달러 규모 MOU(2030년까지) 체결 보도 | 2026-07(정확 일자 확인 필요) | 종합 보도 [P3] — 1차 공시 확인 필요 |
| Tesla(TSLA) | 버크셔 해서웨이 자회사 파일럿 트래블센터(Pilot Travel Centers)와 테슬라 세미(Semi) 전용 충전소 설치 파트너십 발표, 2026년 여름 개소 예정 | 2026-07-07 보도 | The Motley Fool · "Massive News for Tesla Stock Investors!" · 2026-07-07 · https://www.fool.com/investing/2026/07/07/massive-news-for-tesla-stock-investors/ [P3] |

비고: MSFT, AMZN, META, NVDA, TSM, BRK 관련 "AI 무관 일반 이슈"로 분류 가능한 검증된 신규 사실은 검색 범위 내 확인되지 않아 표에서 제외함.

---

## [7] 기관·대형 자금 수급

| 항목 | 종목 | 사실 내용 | 규모(수치) | 출처+태그 |
|---|---|---|---|---|
| ETF 자금흐름 | SOXX(iShares 반도체 ETF) | 최근 세션 중 하루 순유입 기록(2026-07-08 기준 단일 최대 유입 $54억), 7월 말 세션에서도 추가 순유입 보도 | 최근 세션 약 $13.8억 순유입(보도 시점 상이) | ETF.com · "Semiconductor ETFs Roar Back: SOXX Pulls In $5.4 Billion in a Single Day" · 2026-07 · https://www.etf.com/sections/daily-etf-flows/semiconductor-etfs-roar-back-soxx-pulls-54-billion-single-day [P3] — 2026-07-27 당일 수치로 특정되지 않음, 확인 필요 |
| ETF 자금흐름 | SMH(VanEck 반도체 ETF) | 순유입 지속 보도(7/8 $5.52억, 이후 세션 $17.8억 등) | $5.52억~$17.8억(세션별 상이) | ETF Action 등 종합 [P3] — 2026-07-27 당일 특정 수치 확인 필요 |
| ETF 자금흐름 | QQQ(Invesco QQQ Trust) | 순유입 지속(한 세션 $13.7억, 다른 세션 $106.2억 보도) | 세션별 상이(자료상 특정일 미확정) | Benzinga/ETF Action 종합 [P3] — 2026-07-27 당일 특정 수치 확인 필요 |
| 옵션 이상거래 | NVDA(엔비디아) | 콜옵션 순매수 중심의 기관 대량 옵션 프리미엄 유입 보도(콜 매수 우위) | 총 프리미엄 약 $6,325만(콜 매수 약 $6,314만 + 풋 매도 프리미엄 약 $10.2만) | 종합 옵션플로우 트래커 보도 [P3] — 2026-07-27 특정일 여부 확인 필요, 거래소 1차 데이터 아님 |

비고: 13F는 시차 문제로 미사용. 위 ETF/옵션 수치는 세션별 보도가 혼재되어 있어 정확히 2026-07-27 당일 수치로 특정하기 어려운 항목이 있음을 병기함.

---

## [7-A] Insider Trading Form 4

`N/A — 2026-07-27~28 기준 NVDA, AVGO, CRDO, CLS, APLD, VRT, SMCI의 CEO/CFO/COO/Director급 신규 Form 4 공시 검색상 확인되지 않음.`

참고(기간 외 최근 공시, 신규 아님): Broadcom(AVGO) Mark David Brazeal(Chief Legal and Corporate Affairs Officer)가 2026-07-08~07-10 각 25,000주 매도(1주당 약 $401.33, 회당 약 $947만~1,003만) 공시 있었으나 수집 기준일(07-27~28) 신규 공시 아님. Nvidia(NVDA) Jensen Huang(CEO)의 최근 확인된 매도는 2026-06-17(10b5-1 플랜에 따른 매도, 약 $950만)로 역시 기준일 신규 공시 아님. [출처: SEC Form4.com / TheStreet · 2026-07-08~10, 2026-06-17 [P1/P3 혼합]]

---

## [8] 향후 14일 주요 일정 (2026-07-28 ~ 2026-08-11)

### 경제 일정
| 날짜 | 시각(ET·KST) | 이벤트 | 컨센서스 | 이전치 | 출처 |
|---|---|---|---|---|---|
| 2026-07-28 | 10:00 ET(23:00 KST) | Conference Board 소비자신뢰지수(7월) | N/A — 확인 필요 | N/A — 확인 필요 | Investech "Economic Release Calendar 2026 July" [P3] |
| 2026-07-28~29 | 종일(FOMC 회의) / 발표 07-29 14:00 ET(07-30 03:00 KST) | FOMC 정례회의 및 정책성명 | 동결(3.50~3.75%) 시장 컨센서스 우세 | 동결(3.50~3.75%, 2026-06 FOMC) | employamerica.org "July 2026 FOMC Preview" [P3] |
| 2026-07-30 | 08:30 ET(21:30 KST) | GDP(2026년 2분기 속보치) | N/A — 확인 필요 | N/A — 확인 필요 | BEA 발표 일정 종합 보도 [P3] — BEA 공식 캘린더 1차 확인 권장 |
| 2026-08-07 | 08:30 ET(21:30 KST, 익일) | 고용상황보고서(7월, 비농업고용·실업률) | N/A — 확인 필요 | 6월: 비농업고용 +57,000(수정치), 예상 +115,000 하회 | CNBC "Jobs report June 2026" [P2] |
| 2026-08-01 또는 08-03(영업일 조정) | 10:00 ET | ISM 제조업 PMI(7월) | N/A — 확인 필요 | 6월 53.3% | Textile World "Manufacturing PMI At 53.3%; June 2026 ISM Manufacturing PMI Report" [P3] |
| 2026-08-05 | 10:00 ET | ISM 서비스업 PMI(7월) | N/A — 확인 필요 | N/A — 확인 필요 | ISM 발표 일정 종합 [P3] |

### 기업 일정
| 날짜 | 기업 | 이벤트 | 컨센서스 EPS | 컨센서스 매출 | 출처 |
|---|---|---|---|---|---|
| 2026-07-28 | Celestica(CLS) | Q2 2026 실적 발표 | N/A — 확인 필요 | N/A — 확인 필요 | Seeking Alpha 관련 보도 종합 [P3] |
| 2026-07-29(장마감 후) | Microsoft(MSFT) | FY2026 Q4 실적 발표 | $4.24 | 약 $876.2억~877억(매체별 $874.2억~877억 상이) | Alphastreet "Microsoft (MSFT) Q4 2026 Preview: EPS Est. $4.24, Reports July 29" [P3] |
| 2026-07-29(장마감 후) | Meta(META) | Q2 2026 실적 발표 | $7.13(타 보도 $7.18) | 약 $601.7억~601.8억 | Yahoo Finance "Countdown to Meta Platforms (META) Q2 Earnings" [P3] |
| 2026-07-30(장마감 후) | Amazon(AMZN) | Q2 2026 실적 발표 | $1.81 | 북미 세그먼트 매출 약 $1,138억(전사 매출 컨센서스 별도 확인 필요) | 종합 보도 [P3] |
| 2026-07-30(장마감 후) | Apple(AAPL) | Q3 FY2026 실적 발표 | $1.88 | N/A — 확인 필요 | 종합 보도 [P3] |

비고: Alphabet(GOOGL)은 2026-07-22 이미 실적 발표 완료(수집 기간 이전, [5-A] 참조).

---

## [9] 오늘의 사실 목록 (순위 없음)

- [1] S&P500 7,413.18(+0.02%), Dow 52,210.08(+0.51%), Nasdaq 24,932.08(-0.18%), Russell2000 2,948.03(+0.60%) · AP(KTVB)/Bloomberg [P2]
- [1] SOX -2.23%, 반도체 대형주 동반 급락 · TradingKey 종합 [P3]
- [1] WTI $82.62(-8.68%), Brent $90.28(-8.23%), 미국-이란 공습 상호 중단으로 유가 급락 · Bloomberg [P2]
- [1] VIX 18.58(+0.64%), Gold $4,077.21(+0.62%), DXY 101.1844(-0.28%) · The Globe and Mail(AP)/Yahoo/TradingEconomics [P2/P3]
- [2] FOMC 2026-07-28~29 회의, 정책성명 07-29 14:00 ET 발표 예정, 현재 목표금리 3.50~3.75% · Kiplinger/employamerica.org [P3]
- [2] 10년물 국채금리 4.64%(-0.04%p) · TradingEconomics [P3]
- [2] CME FedWatch(2026-07-28 기준) 동결 확률 97.4%, 인하 확률 2.6% · growbeansprout.com 종합 [P3]
- [3] 2026-07-27~28 CPI·PPI·GDP·Payroll·실업률·실업수당·소매판매·ISM 발표 없음 · N/A
- [4] SanDisk(SNDK) -11.85%, 중국 메모리 경쟁사 창신테크놀로지 상하이 IPO(+466% 첫날) 여파 · The Motley Fool [P2]
- [4] Seagate(STX) -7%, 메모리 공급과잉 우려 동반 하락 · Yahoo Finance [P2]
- [4] Apple(AAPL) 세계 시가총액 1위 탈환(시총 약 $4.94~4.95조) · CNBC [P2]
- [5] Nvidia(NVDA) -5%, OpenAI 데이터센터 프로젝트향 최대 $2,500억 자금보증 논의설로 순환금융 우려 재점화 · Yahoo Finance [P2]
- [5] Nvidia-SK그룹 $500억 이상(원문상 5,000억 달러) 협력 LOI 체결, SK텔레콤 2GW AI데이터센터·SK하이닉스 HBM4 공동개발 · NVIDIA Newsroom [P1]
- [5] AMD -3.39%~-5.17%(보도별 상이), 반도체 섹터 전반 약세 동반 · FX Leaders [P3]
- [5] Broadcom(AVGO) AI반도체 백로그 약 $730억, FY2027까지 AI반도체 매출 $1,000억 이상 목표(CEO 발언) · 종합 보도 [P3]
- [5] TSMC(TSM) Q2 매출 가이던스 $390억~402억(+약 32% YoY), 2나노 양산 진전 · The Motley Fool [P3]
- [5] AI서버향 DRAM·NAND·HBM 공급부족 지속, Q1 DRAM 계약가 +90~95% QoQ · Astute Group/TrendForce 종합 [P3]
- [5-A] Alphabet 2026년 Capex 가이던스 $195억~205억으로 상향(기존 $180억~190억) · CNBC [P2]
- [5-A] Alphabet Q2 2026 실제 Capex $449억 집행(서버 약 60%, 데이터센터·네트워킹 약 40%) · Investing.com [P2]
- [5-A] Microsoft·Amazon·Meta는 각 07-29, 07-30, 07-29 실적 발표 예정으로 신규 변동 없음(직전 가이던스 유지) · 종합 보도 [N/A]
- [6] Apple 세계 시가총액 1위 탈환 · CNBC [P2]
- [6] Alphabet EU 안드로이드 반독점 41억 유로 과징금 항소 기각(07-02), 스웨덴 법원 클라란 관련 $19.7억 배상 명령(07-01) · CNBC [P2]
- [6] Broadcom-삼성전자 $2,000억 규모 첨단칩·패키징 MOU 보도(2030년까지) · 종합 보도 [P3]
- [6] Tesla-버크셔 파일럿트래블센터 세미 충전소 파트너십(2026년 여름 개소 예정) · The Motley Fool [P3]
- [7] SOXX·SMH·QQQ 등 반도체/기술 ETF 순유입 지속 보도(당일 특정치 확인 제한) · ETF.com 등 종합 [P3]
- [7] NVDA 옵션시장 콜매수 우위의 대량 프리미엄 유입 보도(총 약 $6,325만) · 옵션플로우 트래커 종합 [P3]
- [7-A] NVDA/AVGO/CRDO/CLS/APLD/VRT/SMCI 대상 신규 Form 4 공시 확인되지 않음 · N/A
- [8] FOMC 정책성명 2026-07-29 14:00 ET 발표 예정 · Kiplinger [P3]
- [8] Celestica(07-28), Microsoft·Meta(07-29), Amazon·Apple(07-30) 실적 발표 예정 · 종합 보도 [P3]
- [8] GDP 2분기 속보치 2026-07-30 08:30 ET 발표 예정 · BEA 일정 종합 [P3]
- [8] 고용상황보고서(7월) 2026-08-07 발표 예정 · 종합 보도 [P3]

---

## 자가 점검 결과
0. 의견·전망·★·AI영향도·밸류체인·순위·다중추론 미포함 확인 — 통과 (원인란은 매체 보도 문구만 인용)
1. 날짜 확정 — 기준일 2026-07-27(월) 미국 정규장 종가, 수집시각 2026-07-28 KST 오전, 검색으로 교차검증(AP/Bloomberg/CNBC 등 다중 매체 수치 대조)
2. 출처+검증 태그 — 전 항목에 출처 URL 및 [P1]/[P2]/[P3]/[N/A] 태그 부여
3. N/A 처리 — ES/NQ 선물, 2년물 금리, 10Y-2Y 스프레드, SOX 정확 포인트, 각종 컨센서스 수치 등 검증 실패 항목 N/A 명기
4. 원인·영향 — 보도된 사실 문구 그대로 인용(해석/추론 배제)
5. 대표 출처 통합 — Dow/S&P/Nasdaq 등 복수 매체 상이 수치 존재 시 AP(KTVB)·Bloomberg·CNBC 등 대표 매체 채택, 상이 수치는 비고로 병기
6. [5]/[5-A]/[6] 분류 — AI 인프라 공급측(반도체·서버·메모리) / 하이퍼스케일러 CAPEX(수요측) / AI 무관 일반이슈(반독점·M&A·제휴)로 구분 적용
7. CAPEX·가이던스 출처일자 — Alphabet 07-22, TSMC 07-16, Broadcom 발표일 일부 미확정(확인 필요 명기)으로 표기
8. Form 4 거래유형 구분 — 기준일 신규 공시 없어 N/A 처리, 참고용 최근 공시(비신규)에 10b5-1 여부 병기
9. [9] 랭킹 아님 — 섹션순 사실 나열, 형용사/방향성/★ 배제
