# 미국 시장 데일리 수집 결과 (Collect)
# 기준일: 2026-07-13 (월) · 미국 정규장 종가 기준(2026-07-10 금요일 종가) · 실행모드: 데일리 코어([1][2][4][5][7][9]) + 조건부([3] N/A 처리·[8] 일정 갱신·[6] 신규이슈 있음·[7-A] 신규공시 없음 확인)
# 생성시각(KST): 2026-07-13 09:30

> 본 문서는 순수 사실 수집(Collect) 결과입니다. 점수·순위·전망·해석은 포함하지 않았습니다(→Analysis 단계 소관).
> 검증 태그: [P1] 1차(Fed·Treasury·BLS·BEA·SEC·기업IR) · [P2] Reuters·Bloomberg·CNBC·WSJ · [P3] 기타 신뢰매체 · [N/A] 확인불가

---

## [1] 미국 주요 지수 + 리스크 지표 〔데일리〕

### 지수 (2026-07-10 금 정규장 종가)

| 항목 | 종가/수치 | 등락률 | (보도된) 원인 | 출처+태그 |
|------|-----------|--------|----------------|-----------|
| S&P 500 | 7,575.39 | +0.42% | Big Tech 강세(Meta·Nvidia) 및 SK Hynix 나스닥 데뷔가 AI 메모리 트레이드 재점화 | Yahoo Finance · "Stock market today: Dow, S&P 500, Nasdaq rise to cap choppy week as SK Hynix pops in US debut" · https://finance.yahoo.com/news/live/stock-market-today-friday-july-10-dow-sp-nasdaq-113921604.html [P2] |
| NASDAQ Composite | 26,281.61 | +0.29% | 상동 | Yahoo Finance(상동) [P2] |
| Dow Jones | 52,637.01 (+149.60pt) | +0.29% | 상동 | Yahoo Finance(상동) [P2] |
| Russell 2000 | 2,977.80 (-14.74pt) | -0.49% | N/A — 당일 개별 원인 보도 미확인(장중 한때 +1.22% 보도와 종가 수치 불일치, 종가 기준 채택) | Yahoo Finance/Investing.com 데이터 종합 [P3, 원인 N/A] |
| SOX(필라델피아 반도체지수) | 12,967.16 (+7.16pt) | +0.06% | N/A — 개별 원인 기사 미확인(대형 반도체주 상승과 인텔·마이크론 하락이 상쇄된 것으로 추정되나 이는 본인 추론이므로 미기재) | Yahoo Finance ^SOX 데이터 [P3] |

**주간 성과(보도 기준):** S&P500 주간 +1%대, NASDAQ 주간 +1%대, Dow 주간 -0.5% · Yahoo Finance(상동) [P2]

### 선물 (2026-07-13 월 오전 KST, 미국 정규장 개장 전)

| 항목 | 동향 | 출처+태그 |
|------|------|-----------|
| ES(S&P500 선물) | N/A — 2026-07-13 오전 KST 시점 정확한 데이터 확보 실패 | [N/A] |
| NQ(나스닥100 선물) | N/A — 2026-07-13 오전 KST 시점 정확한 데이터 확보 실패(2026-07-10~11 시점 자료만 확인: ESU26 -0.11%, NQU26 -0.41%로 보도됐으나 이는 오늘 새벽 KST 시점과 다른 시점 데이터라 채택하지 않음) | [N/A, 참고자료만 존재] |

### 리스크 지표 (2026-07-10 금 기준)

| 항목 | 종가/수치 | 등락률 | 출처+태그 |
|------|-----------|--------|-----------|
| VIX | 15.03 | -5.11% | dds.finance/Yahoo Finance 데이터 종합 [P3] |
| DXY(달러인덱스) | 100.9669 | +0.06% | TradingEconomics [P3] |
| WTI 원유 | $71.41/bbl | -0.93% | Forbes Advisor · "Crude Oil Price Today: July 10, 2026" [P3] |
| Brent 원유 | $76.01/bbl | -0.38% | Forbes Advisor(상동) [P3] |
| Gold(금) | $4,121.05/oz | -0.06% | TradingEconomics [P3] |

**보도된 배경 사실(Big Tech 랠리 관련):**
- Meta 주가 +6% 부근(주간 +15%, 2024년초 이후 최대 주간 상승), BofA는 매수의견 유지하며 내부 메모 기준 Meta의 AI 비용구조 개선 가능성 언급
- Reuters 단독보도(07-09): Meta가 자체 AI 칩 "Iris"(코드네임) 생산을 9월 개시 예정이며, 내년까지 컴퓨팅 파워를 14GW로 확대 목표라는 내부 메모 내용 보도
- Nvidia 주가 약 +2.3%~+4% 상승, 시가총액 다시 $5조 돌파(07-10 기준 시총 약 $5.11조, 종가 $210.96)
- 출처: CNBC · "Traders fall back in love with Meta. Here's where bulls see it going"(2026-07-10) · https://www.cnbc.com/2026/07/10/traders-fall-back-in-love-with-meta-heres-where-bulls-see-it-going.html [P2]
- 출처: CNBC · "Meta to put AI chip into production in September as it looks to double computing capacity, Reuters reports"(2026-07-09) · https://www.cnbc.com/2026/07/09/meta-to-put-ai-chip-into-production-in-september-report.html [P2]
- 출처: Yahoo Finance · "Nvidia stock clinches record close, pushing market cap over $5 trillion once again" [P2]

---

## [2] 금리 / 연준 〔데일리〕

| 항목 | 사실 내용(발언·수치) | 출처+태그 |
|------|----------------------|-----------|
| 미 국채 2년물(07-10) | 4.21% | Advisor Perspectives · "Treasury Yields Snapshot: July 10, 2026" [P3] |
| 미 국채 10년물(07-10) | 4.56% | Advisor Perspectives(상동) [P3] |
| 10Y-2Y 스프레드(07-10) | +0.35%p(35bp) | 계산값(위 두 수치 기준) [P3] |
| **연준 의장 현황** | 케빈 워시(Kevin Warsh)가 현 연준 의장(2026-05-22 취임). 변동 없음 | 직전 파일 확인 사항, 재확인 완료 [P1] |
| **연준, 의회 반기 통화정책보고서(Monetary Policy Report) 제출** | 2026-07-10 11:00 EDT 발표. "인플레이션이 지난 1년간 이란 전쟁·관세·기술재화 비용 급등 영향으로 상승(stepped up)했다"고 명시하면서도 trimmed-mean 물가지표는 하락했다고 병기. 경기는 "solid(견조)", 생산성은 "strong(견조)"으로 평가, 은행시스템 리스크 징후는 낮다고 기술 | Federal Reserve Board · "Monetary Policy Report" (2026-07-10) · https://www.federalreserve.gov/monetarypolicy/files/20260710_mprfullreport.pdf [P1]; Bloomberg · "Fed Vows to Deliver Price Stability in Monetary Policy Report"(2026-07-10) [P2] |
| Fed 워시 의장, 상하원 반기 증언 일정 확정 | 하원 금융서비스위원회 07-14(화) 10:00 ET, 상원 은행위원회 07-15(수) 예정. 취임 후 첫 반기 통화정책 의회 증언 | Investing.com/Reuters · "Fed Chair Warsh to testify before lawmakers on July 14"(2026-06-22 보도, 일정 재확인) [P2] |
| CME FedWatch — 차기 FOMC(2026-07-29) 확률(2026-07-08 기준) | 동결 70.1% (나머지 확률 구성은 스니펫상 명시 안됨 — 검색 결과 원문 미확인) | growbeansprout.com/CME 관련 집계(07-08 기준) [P3] |
| CME FedWatch — 참고치(직전 파일과 동일 출처, 07-10 이전 시점) | 동결 74.9% / 인상 25.1% / 인하 0% | Motley Fool 집계(시점 명확치 않음, 07-08 수치와 불일치) [P3, 수치 출처간 불일치] |
| 직전 FOMC(2026-06-17) | 3.50~3.75% 만장일치 동결. 변동 없음(재확인) | Federal Reserve [P1] |
| 차기 FOMC 회의 | 2026-07-28~29 (07-29 14:00 ET/07-30 03:00 KST 금리결정 발표 예정) | 연준 캘린더 [P1] |

---

## [3] 주요 경제지표 〔조건부 — 발표일만〕

**N/A — 2026-07-10(금) 당일 CPI/PPI/GDP/Payroll/ISM 등 주요 지표 발표 없음.** (경제캘린더 확인: 07-10 "제한적 발표만" 보도 [P3]). 이날 있었던 주요 이벤트는 연준의 반기 통화정책보고서 제출이며, 이는 [2]에 기재함.

### 참고: 최근 발표분 (다음 단계 맥락 참고용)

| 지표 | 발표시각(ET·KST) | 발표치 | 예상치 | 이전치 | 서프라이즈(산술) | 출처+태그 |
|------|------------------|--------|--------|--------|----------------------------------------|------|
| 비농업고용(6월, 07-02) | 08:30 ET / 21:30 KST | +57,000명 | +115,000명 | +129,000명(5월, 수정) | -58,000 | BLS [P1], CNBC [P2] |
| 실업률(6월, 07-02) | 08:30 ET / 21:30 KST | 4.2% | 4.3% | 4.3%(5월) | -0.1%p | CNBC/TradingEconomics [P2] |
| CPI 헤드라인(5월, 06-10) | 08:30 ET / 21:30 KST | +0.5% MoM / +4.2% YoY | N/A | +3.8% YoY(4월) | N/A | BLS [P1], CNBC [P2] |
| PPI 헤드라인(5월, 06-11) | 08:30 ET / 21:30 KST | +1.1% MoM | +0.7% MoM | N/A | +0.4%p | CNBC [P2] |
| 소매판매(5월, 06-17) | 08:30 ET / 21:30 KST | +0.9% MoM | +0.5% MoM | +0.4%(4월) | +0.4%p | Census [P1] |
| ISM 제조업 PMI(6월, 07-01) | 10:00 ET / 23:00 KST | 53.3 | 53.8 | 54.0(5월) | -0.5 | ISM [P1] |
| ISM 서비스업 PMI(6월, 07-06) | 10:00 ET / 23:00 KST | 54.0 | 약 54.0~54.2 | 54.5(5월) | 약 0~-0.2 | ISM [P1] |
| 신규실업수당청구건수(7/4마감주, 07-09) | 08:30 ET / 21:30 KST | 215,000건 | 218,000건 | 217,000건(수정치) | -3,000 | Bloomberg [P2] |
| 미시간대 소비자심리지수 확정치(6월) | 정확 발표일 확인 필요 | 49.5(확정치, 예비치 48.9에서 상향) | N/A | 44.8(5월, 역대 최저) | N/A(예비치 대비 +0.6) | Univ. of Michigan/FRED [P1] |
| Q2 2026 GDP | - | N/A — 미발표(07-30 발표 예정) | - | - | BEA [P1] |

### 향후 발표 예정(이번 주)
| 지표 | 예정일(ET) | 컨센서스 | 출처 |
|------|-----------|----------|------|
| CPI(6월) | 07-14(화) 08:30 | 헤드라인 YoY 약 3.8%대 전망 보도(5월 4.2%에서 둔화 예상) | Kiplinger [P3] |
| PPI(6월) | 07-15(수) 08:30 | N/A | BLS [P1] |
| 소매판매(6월) | 07-16(목) 08:30 | N/A | Census [P1] |
| 산업생산·설비가동률(6월) | 07-17(금) 09:15 | N/A | 연준 G.17 [P1] |

---

## [4] 특징 종목 〔데일리, 2026-07-10 세션〕

| 종목 | 티커 | 등락률 | 거래량/특이사항 | (보도된) 핵심 사실 | 출처+태그 |
|------|------|--------|--------|---------------------|-----------|
| WD-40 | WDFC | +23.3%(장중) | 실적 서프라이즈 | FY2026 3분기 실적 발표, 예상치 상회 | Investing.com(07-10) [P2] |
| Vodafone | VOD | +12.8% | 지분 변동 | 프랑스 통신재벌 Xavier Niel이 16% 지분(약 $59억) 인수하며 최대주주로 부상 | Investing.com(07-10) [P2] |
| Circle Internet Group | CRCL | +12.6%(세션) | OCC 인가·파트너십 | OCC(통화감독청)로부터 내셔널 신탁은행 설립 최종 승인 획득, Nomura와 제휴해 2027년까지 일본에서 USDC 활용 즉시 외환결제 서비스 출시 계획 발표 | Timothy Sykes(07-10) [P3] |
| CCC Intelligent Solutions | CCCS | +9.29%(종가 $5.88) | M&A 검토설 | Reuters 보도: 매각 등 전략적 대안 검토 중이라고 보도 | Investing.com/Reuters(07-10) [P2] |
| Acuity | AYI | -8.6% | 지수 편출 | Russell 1000 Dynamic Index에서 편출됨 | Investing.com(07-10) [P2] |
| Fermi Inc. | FRMI | -17.42% | 전환사채 발행 | 희석 방지용 캡드콜(capped call) 거래를 포함한 3.75억달러 규모 증액 전환사채 발행가 확정 발표 후 하락 | Benzinga(07-09/10) [P2] |
| Ionis Pharmaceuticals | IONS | -7.6%(07-10 추가 하락, 07-09 -21% 급락 이후) | 임상 실패 지속 여파 | AstraZeneca와 공동개발 심장약 Wainua의 Phase 3(CARDIO-TTRansform) 1차 평가변수 미충족 여파 지속 | Investing.com(07-10) [P2] |
| SK Hynix (미 ADR) | SKHYV(07-15부터 SKHY로 티커 변경 예정) | 데뷔일 +13%(종가 $168.01, 시가 $170, 공모가 $149) | 나스닥 데뷔 첫날 | $265억 규모 ADR 상장(외국기업 美 상장 사상 최대, 종전 알리바바 $250억 상회). SK하이닉스 회장 CNBC 인터뷰서 "수요가 막대하다(demand is enormous)"고 언급 | CNBC · "SK Hynix rises 13% in Nasdaq debut. Chairman tells CNBC 'demand is enormous'"(2026-07-10) [P2] |
| Micron | MU | -1.24%(종가 $979.30) | 고점 대비 조정 지속 | 06-25 사상최고가($1,213.37) 대비 약 22% 하락한 상태에서 추가 조정. SK Hynix 상장에 따른 경쟁구도 불확실성이 배경으로 거론됨 | TradingKey(07-10) [P3] |
| Intel | INTC | -2.4%~-3.64%(종가 $109.84) | 반도체 대형주 매도 동반 | 대형 기술주·반도체 전반 위험회피(risk-off) 흐름 속 하락. 파운드리 매출은 461% 급증했다는 보도도 병존 | GuruFocus/TradingKey/ts2.tech(07-10) [P2/P3] |

---

## [5] AI 인프라 — 공급 측 〔데일리〕

| 기업 | 뉴스 제목 | 사실 내용(무슨 일이) | 출처일자 | 출처+태그 |
|------|-----------|----------------------|----------|-----------|
| NVDA | 시가총액 $5조 재돌파 | 07-10 종가 $210.96, 시가총액 약 $5.11조로 재차 $5조 상회 | 2026-07-10 | Yahoo Finance [P2] |
| AVGO | Apple-Broadcom 커스텀 칩 계약 (재확인) | $300억+ 규모 다년 계약, 2031년까지, Fort Collins(콜로라도) 시설에 $15억 투자해 15억개+ 美제조 칩 생산 확대 — 계약 자체는 07-06~08 보도(직전 파일 반영), 07-11~12 시점 애널리스트 컨센서스는 매수(Buy) 유지, 목표주가 평균 $501.58 | 2026-07-06(원 계약 보도), 2026-07-12(애널리스트 집계) | Bloomberg [P2], 애널리스트 컨센서스 집계 [P3] |
| AMD | Stifel 목표주가 $450→$635 상향 | Stifel, AMD 목표주가를 $635로 상향(매수 유지). AI 인프라 기업들은 수요보다 공급 제약이 문제라는 논리, Meta의 최대 6GW AMD Instinct GPU 도입 계획 및 OpenAI의 6GW 공급 약정이 다년 매출 가시성 근거로 제시됨 | 2026-07-10 | 24/7 Wall St., TipRanks(07-10) [P3] |
| AMD | Zen 6 EPYC(코드네임 Venice) 서버 CPU 출시 발표 | TSMC 2nm 공정 기반 신형 서버 CPU를 07-22~23 공개 예정이라고 발표(Advancing AI 2026 컨퍼런스와 동일 일정) | 2026-07-11 | interactivecrypto.com 등 종합 보도(원출처 확인 필요) [P3] |
| TSM | 웨이퍼 가격 인상 확인 | 3nm/5nm 등 첨단 공정 웨이퍼 가격을 5~10% 인상하는 방침이 이미 시행 시작됐다고 보도(직전 파일에서 "확인 필요"였던 항목이 복수 매체 통해 재확인됨) | 2026-07-10 | 24/7 Wall St. · "Taiwan Semiconductor Is a No-Brainer Buy Before July 16 Earnings" [P3] |
| TSM | 6월 매출(월간) 발표 지연 | 태풍(Bavi)으로 인한 대만 임시 휴무로 당초 07-10 발표 예정이던 6월 매출보고가 07-13(현지시간 13:30, 한국시간 약 14:30) 오후로 연기됨. 시장에서는 월 매출이 사상 최고치(NT$4,000억~4,400억 수준) 경신 가능성이 거론되나, 본 문서 작성 시점(07-13 오전 KST) 기준 아직 미발표 | 2026-07-09(연기 발표) | Newsquawk, BigGo Finance [P2/P3] |
| CRDO | CTO 지분 매도 공시 | Cheng Chi Fung(디렉터 겸 CTO), 07-07(Cheng Huang Family Trust 경유, 10b5-1 계획, 27,500주)·07-08(개인 보유분 3,790주, @$258.71) 합산 총 31,290주 매도 — 직전 파일에 개별 보도됐던 두 건이 동일 Form 4로 통합 확인됨(신규 사실 아님, 교차검증) | 2026-07-09(SEC 접수일) | StockTitan/Motley Fool(07-09) [P1/P3] |
| VRT | 말레이시아 신규 공장(재확인) | 조호바루 신공장 개설 소식 — 직전 파일과 동일, 신규 변동 없음 | 2026-07-06(원보도) | 회사 발표 기반 보도 [P2/P3] |
| SMCI | 수출통제 조사(재확인) | 대만 직원 4명 조사 대상 공개 — 직전 파일과 동일, 신규 변동 없음 확인 | 2026-07-01(원보도) | QuiverQuant [P3] |
| APLD | Polaris Forge 1(재확인) | 2동 가동 개시(75MW) — 직전 파일과 동일, 07-11~13 신규 발표 확인 안됨 | 2026-07-01(원보도) | Applied Digital IR [P1] |
| ANET | AI 스위치 목표주가 상향(재확인) | KeyBanc·Morgan Stanley·BofA의 목표주가 상향(최대 $200) — 직전 파일과 동일 사안, 07-11~13 신규 발표 확인 안됨 | 2026-07-06(원보도) | StocksToTrade [P3] |

### 추가 시그널 (HBM/DRAM/NAND, AI서버·광통신)

| 항목 | 사실 내용 | 출처+태그 |
|------|-----------|-----------|
| DRAM 계약가 전망 | 2026 3분기 범용 DRAM 계약가 전분기 대비 +13~18% 상승 전망(2분기 약 +60%대 상승 대비 상승폭 둔화) | TrendForce 관련 보도(Tom's Hardware 인용) [P3] |
| NAND 계약가 전망 | 2026 3분기 NAND Flash 계약가 전분기 대비 +10~15% 상승 전망 | Tom's Hardware [P3] |
| NOR Flash·SLC NAND | 2026 상반기 누적 계약가 인상폭 100% 초과, 하반기도 상승 지속 전망 | TrendForce 보도자료(2026-06-16) [P2] |
| HBM 시장 | HBM 수요 전년대비 약 70% 증가, 2026년 DRAM 웨이퍼 생산능력의 약 25% 차지 추정. Samsung·SK Hynix가 Nvidia 차세대 Rubin 플랫폼용 HBM4 공급사로 거론되며 2026년 생산능력 완판 상태로 보도. 단, HBM은 비공개 계약 거래로 공식 현물시장가는 존재하지 않음(업계 추정치) | Silicon Analysts 등 집계 [P3] |
| 메모리 섹터 시총 변동 | 6/25 이후 메모리 관련주 시총 약 $1.5조 감소, Micron 단독 약 $3,500억 감소로 보도 | Yahoo Finance(시점 특정 어려움) [P3] |

---

## [5-A] AI 인프라 — 수요 측 / 하이퍼스케일러 CAPEX 〔실적시즌 아님 — 직전 가이던스 유지〕

> MSFT/AMZN/GOOGL/META 모두 직전 실적(2026-04-29 전후, Q1 2026)이 최신이며 차기 실적은 07-29(MSFT·META), 07-30(AAPL·AMZN) 예정. CAPEX 수치 가이던스 자체는 신규 변동 없음. 단, META는 실적 발표 전 자체 AI칩 관련 신규 정보가 언론에 노출되어 아래 별도 기재.

- MSFT: 신규 변동 없음 — 직전 가이던스 유지 (FY26 Q3 capex $31.9B, CY2026 총 capex $190B 전망, 출처일자 2026-04-29 · CNBC [P2])
- AMZN: 신규 변동 없음 — 직전 가이던스 유지 (Q1 2026 capex $44.203B/YoY+77%, 2026년 전체 capex 약 $200B 전망, 출처일자 2026-05월경 · SEC 8-K [P1])
- GOOGL: 신규 변동 없음 — 직전 가이던스 유지 (CY2026 capex 가이던스 $180B~$190B, 출처일자 2026-04-29 · CNBC [P2])
- META: **CAPEX 금액 가이던스 자체는 변동 없음**($125B~$145B, 출처일자 2026-04-29). 단, 07-09 Reuters 단독보도(내부 메모 인용)로 신규 사실 노출: ① 자체 설계 AI칩 "Iris"(MTIA 4세대 프로젝트) 생산을 9월 개시 예정, Broadcom과 설계·TSMC와 생산 협력 ② 내년까지 전체 컴퓨팅 파워를 14GW로 확대 목표 ③ Samsung(메모리)·SanDisk(플래시)·Sumitomo Electric(광케이블 장비)과 공급 계약 체결 | 출처: CNBC · "Meta to put AI chip into production in September..."(2026-07-09) [P2]

---

## [6] 시총 상위 10 — AI 무관 일반 이슈 〔신규 이슈 있음 — 2026-07-10 이후 갱신〕

| 기업 | 사실 내용 | 출처일자 | 출처+태그 |
|------|-----------|----------|-----------|
| AAPL | Apple이 캘리포니아 북부지구 연방법원에 OpenAI를 상대로 영업비밀 침해 소송 제기. 전직 Apple 부사장이자 現 OpenAI 하드웨어 총괄 Tang Tan이 Apple 직원들에게 면접 과정에서 기밀정보를 공유하도록 지시했다는 의혹, 前 Apple 엔지니어 Chang Liu가 퇴사 시 Apple 지급 노트북을 반납하지 않고 기밀 기술문서를 다운로드했다는 의혹 포함 | 2026-07-10 | CNBC · "Apple sues OpenAI alleging trade secret theft, says scheme was 'at every level'" · https://www.cnbc.com/2026/07/10/apple-openai-lawsuit-trade-secrets.html [P2]; Bloomberg, Axios, Fortune 동시 보도 [P2] |
| META | EU 집행위원회, Instagram·Facebook의 "중독적 설계(addictive design)"가 디지털서비스법(DSA) 위반이라는 예비 판단(preliminary finding) 발표. 무한스크롤·자동재생·푸시알림·추천알고리즘 4개 메커니즘이 청소년 등 이용자의 신체적·정신적 건강 위험 평가를 소홀히 했다고 지적. 위반 확정 시 글로벌 매출의 최대 6%까지 과징금 가능. Meta는 "예비 판단에 동의하지 않는다"고 반응 | 2026-07-10 | European Commission 보도자료 · https://ec.europa.eu/commission/presscorner/detail/en/ip_26_1579 [P1]; CNBC(동일자) [P2] |
| BRK | Berkshire Hathaway B주가 연초 대비 -1.8%(S&P500 대비 12.4%p 열위)로 보도(2026년 상반기 마감 기준). 6월 한 달 강세로 격차가 6월1일 기준 -17.5%p에서 축소됨 | 2026-07-11 | CNBC · "Berkshire Hathaway gains ground, but still trails the S&P 500 as '26 enters second half" [P2] |
| GOOGL | 美 법무부(DOJ) 온라인광고 반독점 소송 관련 구제조치(remedies) 재판이 "다음 주(발행 시점 기준)" 개시 예정이라고 보도(정확한 개시일 확인 필요) | 확인 필요 | The Conversation [P3] |
| AMZN | FTC 대 아마존 반독점 소송 재판이 2026-10 예정으로 재확인됨(신규 변동 없음) | 재확인, 시점 N/A | 검색 종합 [P3] |
| MSFT | 07-06 발표된 전사 약 4,800명(2.1%) 감원·Xbox 사업 축소 — 신규 변동 없음(재확인만) | 2026-07-06(원보도) | GeekWire [P3] |
| TSLA | Model Y L Launch Series 판매 개시(美), 10-11월 인도 예정, 신차 구매시 FSD 12개월 무료 구독 제공 | 2026-07-11 | Tesla Oracle [P3] |
| TSLA | 07-22 2분기 실적 발표 예정 재확인(신규 변동 없음) | 재확인 | 검색 종합 [P3] |

---

## [7] 기관·대형 자금 수급 〔데일리〕

| 항목 | 종목/ETF | 사실 내용 | 규모(수치) | 출처+태그 |
|------|------|-----------|------------|-----------|
| ETF 자금유입(직전 확인분, 07-08) | SOXX(iShares Semiconductor ETF) | 단일 세션 순유입, AUM 하루만에 11.73% 증가(약 $463억 규모로) — 직전 파일과 동일 사실, 07-09/07-10 신규 수치는 검색으로 확인하지 못함 | $54.3억(1일, 07-08) | ETF.com(07-08) [P3] |
| ETF 자금유입(직전 확인분, 07-08) | SMH(VanEck Semiconductor ETF) | 동일 세션 순유입 — 직전 파일과 동일 사실 | $5.52억(1일, 07-08) | ETF.com(07-08) [P3] |
| ETF 자금유입(직전 확인분, 07-08) | QQQ(Invesco QQQ Trust) | 대규모 순유입 보도(정확한 날짜 특정에 스니펫간 약간의 불일치 있음, 07-08 전후로 추정) | $106.2억 | ETF Action [P3] |
| 07-09/07-10 신규 ETF 자금흐름 | SOXX·SMH·QQQ | N/A — 검색으로 07-09·07-10 단독 순유입/유출 수치를 확인하지 못함 | - | - |
| 기관 블록딜(직전 확인분, 07-01) | MU(Micron)·SNDK(SanDisk) | 옵션시장은 약세 시그널을 보였음에도 기관 블록거래는 순매수 우위로 보도됨(07-01 기준, 신규 수치 아님) | MU +$2.08억, SNDK +$1.46억(순유입, 07-01) | AlphaGBM [P3] |
| 기관 블록딜(직전 확인분, 07-01) | AMAT·TSM·KLAC(반도체 장비주) | 차익실현성 순유출로 보도(07-01 기준, 신규 수치 아님) | AMAT -$1.39억, TSM -$1.38억, KLAC -$0.93억 | AlphaGBM [P3] |
| IPO 수요(재확인) | SK Hynix(SKHYV) | $265억 규모 ADR 공모, 외국기업 美 상장 사상 최대 규모(종전 알리바바 $250억 상회) | $265억 | CNBC(07-10) [P2] |
| 옵션시장 이상거래 | NVDA/AMD/AVGO | N/A — 07-10~13 개별 이례적 옵션거래 관련 구체적 보도 확인 안됨 | - | - |

---

## [7-A] Insider Trading (SEC Form 4) 〔조건부 — 신규공시 확인〕

**N/A — 2026-07-10 이후 NVDA/AVGO/CRDO/CLS/APLD/VRT/SMCI 대상 CEO·CFO·COO·Director 신규 Form 4 매수/매도 공시 확인되지 않음.**

확인 과정: CRDO의 CTO Cheng Chi Fung 매도(07-07·07-08 거래, 07-09 SEC 접수)는 직전 07-10 수집 파일에 이미 개별 반영된 거래로, 신규 공시가 아니라 동일 Form 4 문서의 교차 확인임(위 [5] 표 참고). VRT의 Krishna Mikkilineni 스톡옵션 부여(3,076주, 행사가 $317.58)는 Form 4 제출일이 2026-06-10로 확인되어 신규 공시 대상 기간(07-10 이후) 밖. AVGO Director 대상 검색 결과는 모두 2026-04월 RSU 정기 부여 건으로 신규 매수/매도 아님. SMCI·APLD 대상 검색에서도 07-11~13 신규 매수/매도 공시 확인 안됨.

---

## [8] 향후 14일 주요 일정 〔갱신 — 2026-07-13 ~ 07-27〕

### 경제 일정

| 날짜 | 시각(ET·KST) | 이벤트 | 컨센서스 | 이전치 | 출처+태그 |
|------|--------------|--------|----------|--------|------|
| 07-13(월) | 13:30 대만시간/14:30 KST(추정) | TSMC 6월 매출(월간, 태풍으로 07-10→07-13 연기) | N/A | N/A | Newsquawk [P2] |
| 07-14(화) | 08:30/21:30 | CPI(6월) | 헤드라인 YoY 약 3.8%대(둔화 전망 보도) | 4.2% YoY(5월) | BLS [P1], Kiplinger [P3] |
| 07-14(화) | 10:00 ET/23:00 KST | Fed 워시 의장, 하원 금융서비스위 반기 통화정책 증언(취임 후 최초) | - | - | Investing.com/Reuters [P2] |
| 07-15(수) | 08:30/21:30 | PPI(6월) | N/A | +1.1% MoM(5월) | BLS [P1] |
| 07-15(수) | N/A | Fed 워시 의장, 상원 은행위 반기 통화정책 증언 | - | - | 연준 캘린더 [P1] |
| 07-16(목) | 08:30/21:30 | 소매판매(6월) | N/A | +0.9% MoM(5월) | Census [P1] |
| 07-16(목) | 08:30/21:30 | 신규실업수당청구건수(주간) | N/A | N/A | BLS [P1] |
| 07-17(금) | 08:30/21:30(추정) | 주택착공·건축허가(6월) | N/A | N/A | Census [P1] |
| 07-17(금) | 09:15/22:15 | 산업생산·설비가동률(6월) | N/A | N/A | 연준 G.17 [P1] |
| 07-23(목) | 08:30/21:30 | 신규실업수당청구건수(주간) | N/A | N/A | BLS [P1] |
| 07-28~29 | 07-29 14:00 ET/07-30 03:00 KST | FOMC 금리결정 | - | - | 연준 [P1] |

### 기업 일정

| 날짜 | 기업 | 이벤트 | 컨센서스 EPS | 컨센서스 매출 | 출처+태그 |
|------|------|--------|--------------|---------------|------|
| 07-14(월) | JPMorgan Chase | Q2 2026 실적(장전) | $5.49 | $48.7B | JPM IR [P1] |
| 07-14(월) | BlackRock, Wells Fargo, Citigroup | Q2 2026 실적(장전) | N/A | N/A | Yahoo Finance [P2] |
| 07-15(화) | Bank of America, Morgan Stanley, Goldman Sachs | Q2 2026 실적 | N/A | N/A | TradingView/Yahoo [P2] |
| 07-16(목) | TSMC(TSM) | Q2 2026 실적(대만 14:00/한국 15:00 추정) | 약 $3.83(55% YoY 증가 시사) | $39.0~40.2B(회사 가이던스) | 24/7 Wall St. [P3], SEC 6-K [P1] |
| 07-16(목) | Netflix(NFLX) | Q2 2026 실적 | N/A | N/A | 검색 종합 [P3] |
| 07-22~23 | AMD | Advancing AI 2026 컨퍼런스(신제품 로드맵 공개), Zen 6 EPYC(Venice) 서버 CPU 공개 예정 | - | - | SiliconANGLE, interactivecrypto.com [P3] |
| 07-22(수) | Tesla(TSLA) | Q2 2026 실적(장마감후) | N/A(재확인 필요) | N/A | 검색 종합 [P3] |
| 07-22(수) | Alphabet(GOOGL) | Q2 2026 실적 | N/A(재확인 필요) | N/A | 검색 종합 [P3] |
| 07-23(목) | Intel(INTC) | Q2 2026 실적 | $0.19 | $14.40B | Benzinga [P3] |
| 07-27(월) | Celestica(CLS) | Q2 2026 실적(장마감후, 07-28 콘퍼런스콜) | N/A | N/A | GlobeNewswire [P1] |

> 기간 이후 참고: MSFT·META 07-29(실적), AAPL·AMZN 07-30(실적) — 직전 파일과 동일, 재확인 완료.

---

## [9] 오늘의 사실 목록 (순위 없음) 〔데일리〕

```
[1] S&P500 7,575.39(+0.42%), NASDAQ 26,281.61(+0.29%), Dow 52,637.01(+0.29%) — Meta·Nvidia 강세 및 SK Hynix 나스닥 데뷔 동반(07-10 종가) · Yahoo Finance[P2]
[1] Russell2000 2,977.80(-0.49%), SOX 12,967.16(+0.06%)(07-10 종가) · Yahoo Finance[P3]
[1] VIX 15.03(-5.11%), DXY 100.97(+0.06%), WTI $71.41(-0.93%), Brent $76.01(-0.38%), Gold $4,121.05(-0.06%)(07-10) · TradingEconomics[P3]
[1] Nvidia 시가총액 $5.11조로 재차 $5조 상회(07-10 종가 $210.96) · Yahoo Finance[P2]
[1] Meta 주가 약+6%(주간+15%), Reuters 단독보도로 자체 AI칩 "Iris" 9월 생산 개시 계획 노출 · CNBC[P2]
[2] 연준, 07-10 11:00 EDT 반기 통화정책보고서 제출 — "인플레이션이 관세·이란전쟁·기술재화 비용으로 상승" 명시 · Federal Reserve[P1]
[2] Fed 워시 의장, 07-14 하원·07-15 상원에서 취임 후 첫 반기 통화정책 증언 예정 · Reuters[P2]
[2] 미 국채 10년물 4.56%, 2년물 4.21%, 10Y-2Y +35bp(07-10) · Advisor Perspectives[P3]
[2] CME FedWatch(07-08 기준) 차기 FOMC(07-29) 동결 확률 70.1% · growbeansprout 집계[P3]
[3] 2026-07-10 CPI/PPI/GDP 등 주요 지표 발표 없음 · 경제캘린더 종합[P3]
[4] SK Hynix 美 ADR, 나스닥 데뷔 첫날 +13%(종가 $168.01), $265억 규모 사상 최대 외국기업 美 상장 · CNBC[P2]
[4] WD-40 +23.3%(장중), FQ3 실적 예상치 상회 · Investing.com[P2]
[4] Circle Internet Group +12.6%, OCC 신탁은행 인가 획득·Nomura와 일본 USDC 결제 제휴 · Timothy Sykes[P3]
[4] Fermi Inc -17.42%, $3.75억 규모 증액 전환사채 발행가 확정 후 하락 · Benzinga[P2]
[4] Micron -1.24%(종가 $979.30), 06-25 사상최고가 대비 약 22% 조정 지속 · TradingKey[P3]
[5] Meta 자체 AI칩 "Iris" 9월 생산 개시, Broadcom 설계·TSMC 생산 협력, 내년 컴퓨팅 14GW 목표 · CNBC[P2]
[5] Stifel, AMD 목표주가 $450→$635로 상향(매수 유지) · 24/7 Wall St.[P3]
[5] AMD, TSMC 2nm 기반 Zen 6 EPYC(Venice) 서버CPU를 07-22~23 공개 예정 발표(07-11) · 종합보도[P3]
[5] TSMC, 3nm/5nm 등 첨단 웨이퍼 가격 5~10% 인상 이미 시행 중이라고 보도 재확인(07-10) · 24/7 Wall St.[P3]
[5] TSMC 6월 매출 발표, 태풍으로 07-10→07-13으로 연기(본 문서 작성 시점 미발표) · Newsquawk[P2]
[5-A] MSFT/AMZN/GOOGL capex 가이던스 신규 변동 없음(직전 04-29 가이던스 유지) · 각사 IR[P1/P2]
[6] Apple, OpenAI 상대 영업비밀 침해 소송 제기(07-10), 前 Apple 임직원의 기밀유출 의혹 · CNBC[P2]
[6] EU 집행위, Meta의 Instagram·Facebook "중독적 설계"가 DSA 위반이라는 예비판단 발표(07-10), 최대 매출 6% 과징금 가능 · European Commission[P1]
[6] Berkshire Hathaway B주가 연초 대비 -1.8%로 S&P500 대비 12.4%p 열위(07-11 보도) · CNBC[P2]
[7] SOXX ETF, 07-08 하루 $54.3억 순유입(직전 확인분, 07-09~10 신규 수치 미확인) · ETF.com[P3]
[7-A] NVDA/AVGO/CRDO/CLS/APLD/VRT/SMCI 대상 07-10 이후 신규 Form 4 매수/매도 공시 없음(확인 완료) · SEC 관련 검색 종합[P3]
[8] CPI(6월) 07-14 발표 예정, 컨센서스 YoY 약 3.8%대(5월 4.2%에서 둔화 전망) · Kiplinger[P3]
[8] JPMorgan 등 주요 은행 07-14~15 Q2 실적 발표로 실적시즌 개막 · JPM IR[P1]
[8] TSMC Q2 실적 07-16 발표 예정, EPS 컨센서스 약 $3.83 · 24/7 Wall St.[P3]
[8] 차기 FOMC 금리결정 07-29(14:00 ET/07-30 03:00 KST) · 연준[P1]
```

---

## 자가 점검 결과
0. 방화벽 점검: 의견·전망·★·AI영향도·밸류체인·순위·다중추론 없음 — 확인 완료
1. 날짜: 웹 검색으로 2026-07-13(월) 확정 — 완료(Warsh 증언 일정 07-14/15, TSMC 6월 매출 07-13 연기 발표 등 교차검증으로 재확인)
2. 모든 수치·뉴스에 출처+검증 태그 부여 — 완료(일부 N/A 명시)
3. 확인 못한 칸 N/A 처리 — 완료(ES/NQ 선물 07-13 오전 KST, SOX 등락 원인, Russell2000 등락 불일치, ETF 07-09/07-10 신규 유입치, 옵션 이상거래, Form4 신규공시 등)
4. 원인·영향은 보도된 사실만 기재 — 완료
5. 동일 사건 대표 출처 통합 — 완료
6. [5]공급/[5-A]수요/[6]일반 분류 — 확인 완료(Meta Iris 칩은 자사 커스텀 실리콘 개발이라 [5-A]에 배치, 제조 협력사인 AVGO·TSM 관점 언급은 [5]에도 교차 표기)
7. CAPEX·가이던스 출처일자 표기 — 완료
8. Form 4 거래유형 구분(신규 공시 없음 확인) — 완료
9. [9]는 랭킹이 아닌 사실 나열 — 완료

## 리서치 한계 (다음 단계 참고)
- ES·NQ 선물의 2026-07-13 오전 KST 시점 정확한 수치를 확보하지 못함(N/A). 07-10~11 시점 자료(ESU26 -0.11%, NQU26 -0.41%)만 확인되어 채택하지 않음.
- SOX 지수 07-10 등락(+0.06%, 사실상 보합) 원인에 대한 개별 보도를 찾지 못함. 대형 반도체주 상승(Nvidia·AVGO 등)과 인텔·마이크론 하락이 혼재된 결과로 추정되나 이는 확인된 사실이 아니므로 본문에 원인을 기재하지 않았음.
- Russell 2000의 당일 등락률이 출처 간 불일치(장중 "+1.22%" 보도 vs 공식 종가 기준 "-0.49%")했음. 종가 기준 수치를 채택했으나 원 불일치는 해소되지 않음.
- CME FedWatch 차기 FOMC 확률이 출처 간 불일치(07-08 기준 "동결 70.1%" vs Motley Fool 인용 "동결 74.9%/인상 25.1%"). 두 수치 모두 정확한 산출 시점의 원문 스니펫을 확보하지 못해 병기함.
- ETF(SOXX/SMH/QQQ) 07-09·07-10 개별 세션 순유입/유출 수치를 검색으로 확인하지 못함(가장 최근 확인 가능한 수치는 07-08 기준).
- 옵션시장 이상거래(unusual options activity) 관련 07-10~13 개별 종목 구체적 보도를 확인하지 못함.
- WebFetch(URL 원문 열람) 도구 사용이 이번 세션에서 권한상 제한되어, 전 항목을 WebSearch 스니펫에 의존했음. 일부 수치(예: 미시간대 소비자심리지수 확정 발표일)는 원문 대조가 이뤄지지 않아 "확인 필요"로 표시함.
- CRDO Form 4(07-09 접수)는 07-07·07-08 거래 내역이 직전 07-10 수집 파일에 이미 개별 반영되어 있어 신규 공시로 집계하지 않고 교차 확인 처리함.
