# 미국 시장 데일리 수집 결과 (Collect)
# 기준일: 2026-08-04 (화) · 미국 정규장 종가 기준 · 실행모드: 실적시즌 (하이퍼스케일러 4사 및 반도체 AI인프라 다수 기업 최근 1~2주 내 실적 발표)
# 생성시각(KST): 2026-08-05 09:30

> 참고: 웹검색으로 확정한 현재 날짜는 2026-08-05(수, KST) 오전이다. 미국 정규장은 미개장 상태이므로, 아래 시장 데이터는 직전 정규장인 2026-08-04(화, ET) 종가 기준이다.

---

## [1] 미국 주요 지수 + 리스크 지표

| 항목 | 종가/수치 | 등락률 | (보도된) 원인 | 출처+태그 |
|---|---|---|---|---|
| S&P500 | 7,736.52 | +1.79% (사상 최고 종가) | 실적 호조, 중동(호르무즈 해협) 긴장 완화 기대 | CNBC · "Stock market today live updates" · 2026-08-03/04 게재 [P2] |
| NASDAQ 종합 | 26,584.99 | +2.59% | 팔란티어 등 기술주 급등, 반도체 랠리 | CNBC 상동 [P2]; Yahoo Finance 상동 [P2] |
| Dow | 54,085.88 | +907.47pt / +1.71% (사상 최고 종가) | 실적 호조, 중동 평화협상 기대 | CNBC 상동 [P2] |
| Russell2000 | 2,981.908 | +50.569pt / +1.73% | 개별 보도 없음(지수 반영 수치만 확인) | Yahoo Finance Historical Data [P2] |
| SOX(필라델피아 반도체지수) | N/A(지수 자체 종가 미확인) | 참고: SOXX(반도체 ETF) +6% 이상 | 마이크론 +8%, 인텔 +10%, 마벨 +14% 등 개별 종목 강세가 지수 상승 견인 | Yahoo Finance/247wallst.com · "Intel Soars 10%, AMD Jumps 8%, Broadcom Rises 6%..." 2026-08-04 [P2] |
| ES(S&P500 선물) | N/A | N/A | 한국 아침 시점 프리마켓 수치 검증 불가 | [N/A] |
| NQ(나스닥100 선물) | N/A | N/A | 한국 아침 시점 프리마켓 수치 검증 불가 | [N/A] |
| VIX | 약 16.34~16.56(장중 좁은 범위, 전일 대비 +0.01pt) | 거의 보합 | 지수 급등에도 변동성 급등 없음 | historicaloptiondata.com "Market Analysis 08/04/2026" [P3] |
| DXY(달러인덱스) | 99.9704 | +0.01% | 개별 보도 없음 | TradingEconomics 집계 [P3] |
| WTI | $76.14/bbl | -5.23% | 중동 긴장 완화 기대에 따른 유가 급락 | Forbes Advisor · "Crude Oil Price Today: August 4, 2026" [P3] |
| Brent | 약 $81.77/bbl(장중 $83.45 개장 대비) | -2.07%(장중 기준) | 상동(중동 리스크 완화) | TradingEconomics · Brent Crude Oil [P3] |
| Gold | 약 $4,057.04(전일종가 $4,055.25) | 보합권 | 국채금리 상승과 안전자산 수요가 상충 | Investing.com XAU/USD [P3]; FXLeaders "Gold Price Forecast" 2026-08-04 [P3] |

---

## [2] 금리 / 연준

| 항목 | 사실 내용(발언·수치) | 출처+태그 |
|---|---|---|
| 미 10년물 국채금리 | 약 4.63% | 검색 집계(FRED DGS10 계열) [P1] |
| 미 2년물 국채금리 | 약 4.21% | 검색 집계(FRED 계열) [P1] |
| 10Y-2Y 스프레드 | 약 +0.42%p(산술) | 상기 두 수치 기반 산출 |
| 최근 FOMC(7월 회의) | 정책금리 3.50~3.75% 동결. 표결에서 이견 존재(9-3 표결로 동결 유지, 일부 위원은 9월 인상 주장 보도) | CNBC · "Warsh's plan for a more opaque Fed..." 2026-07-29 [P2] |
| 차기 FOMC 일정 | 2026-09-16 | 검색 집계 [P3] |
| CME FedWatch (2026-07-28 기준) | 9월 회의 0.25%p 인하 확률 54.4%로 표시 | 검색 집계(centralbank.watch 등) [P3] — ※ 위 FOMC 이견 보도와 방향성이 상반되어 병기함, 해석 없음 |
| 파월 후임 Fed 의장 케빈 워시 발언 | "We have no magic wand. This isn't something we're going to be able to carry out in days or weeks." | Chase.com · "Kevin Warsh July 2026 Federal Reserve" [P3] |
| 케빈 워시 발언(위원회 운영 관련) | "I asked for a good family fight and I got one." | 상동 [P3] |

---

## [3] 주요 경제지표 〔조건부〕

| 지표 | 발표시각(ET·KST) | 발표치 | 예상치 | 이전치 | 서프라이즈 | 출처 |
|---|---|---|---|---|---|---|
| ISM 서비스업 PMI(7월) | 2026-08-05 10:00 ET / 23:00 KST(금일, 미발표) | N/A(미발표) | 54.5 | 54.0(6월) | N/A | Continuum Economics "Preview: Due August 5" [P3]; ISM 6월 보고서 prnewswire [P1] |

※ 그 외 CPI(8/12), PPI(8/13), 7월 고용보고서(8/7 예정)는 금일 발표 대상 아님 — [8] 참조.
※ 7월 고용보고서 관련하여 검색 중 "비농업고용 +73,000, 예상 104,000" 수치가 검색되었으나, 발표 예정일(8/7)보다 이전 시점(8/1)의 기사이며 연도 정합성이 불명확하여 신뢰도 부족 → 컨센서스는 N/A 처리.

---

## [4] 특징 종목 (±5% 이상 / 거래량 급증, [5]/[5-A]/[6] 대상 제외)

| 종목 | 티커 | 등락률 | 거래량 | (보도된) 핵심 사실 | 출처+태그 |
|---|---|---|---|---|---|
| 팔란티어 테크놀로지스 | PLTR | +29.45% | N/A | 2분기 매출 $19.4억(예상 $18억 상회), 조정 EPS $0.41(예상 $0.35 상회), 연간 매출 가이던스를 $81.6억으로 상향(기존 $76.5억~76.6억). 미국 상업부문 매출 전년비 149% 증가 | CNBC · "Palantir stock skyrockets 29%..." 2026-08-04 [P2] |
| 인텔 | INTC | +10% | N/A | 반도체 업종 전반 랠리 속 상승 | 247wallst.com/Yahoo Finance · 2026-08-04 [P2] |
| 마벨 테크놀로지 | MRVL | +14% | N/A | FMS(Flash Memory Summit) 2026에서 AI 최적화 메모리·스토리지 신제품 발표, BofA 애널리스트 목표가 $1,550 재확인 | 247wallst.com/Yahoo Finance · 2026-08-04 [P2] |
| 마이크론 | MU | +8% | N/A | BofA 목표가 상향(위 마벨 기사와 동일 보도 내 언급) | 상동 [P2] |

---

## [5] AI 인프라 — 공급 측

| 기업 | 뉴스 제목 | 사실 내용(무슨 일이) | 출처일자 | 출처+태그 |
|---|---|---|---|---|
| AMD | 2분기 실적 발표 | EPS $1.66(가이던스 상회), 매출 $115억(사측 가이던스 약 $112억 상회, 컨센서스 매출 약 $113억·EPS 약 $1.61 상회). 3분기 가이던스는 시장 예상보다 양호. CEO 리사 수: "Epyc 수요 가속, Instinct 배치 확대, Helios 램프업 시작"으로 하반기 강한 모멘텀 진입 발언 | 2026-08-04 | Yahoo Finance/Fool.com [P2]; 회사 발언 인용 [P1] |
| AMD | 주가 반응 | 실적 발표 후 시간외 거래에서 주가 8% 이상 하락(정규장 중에는 실적 발표 전 반도체 랠리로 +7% 상승) | 2026-08-04 | Yahoo Finance [P2] |
| 아리스타 네트웍스 | 2분기 실적 발표 | 비GAAP EPS $1.02(컨센서스 $0.89 대비 상회), 매출 $30.4억(컨센서스 대비 +7.2%, 전년비 +37.7%), 분기 매출 $30억 최초 돌파. 3분기 가이던스 매출 약 $33억(컨센서스 약 $29.5억 상회), 비GAAP 영업이익률 48~49%, EPS $1.06~1.08 제시 | 2026-08-04 | Businesswire/StreetInsider(회사 발표) [P1]; Benzinga [P2] |
| 아리스타 네트웍스 | 주가 반응 | 실적 발표 후 시간외 거래에서 주가 13% 상승, 사상 최고가 경신 | 2026-08-04 | Yahoo Finance [P2] |
| TSMC(TSM) | 2026년 매출 전망 상향 | 2026 연간 매출 성장률 전망을 달러 기준 30% 이상으로 상향. 생성형 AI에서 에이전틱 AI로의 전환에 따른 컴퓨팅 수요 강세를 근거로 언급 | 2026년 1분기 실적발표 콜(약 2주 전 보도) | Fool.com · "TSMC Just Announced Incredible News..." [P2] |
| 브로드컴(AVGO) | 2분기(FY26) 실적 | 매출·EPS 모두 컨센서스 상회했으나, AI 관련 일부 프로그램의 향후 성장 속도에 대한 가이던스 우려로 주가 약세 | 최근 실적발표(정확 일자 재검증 필요) | Yahoo Finance/Zacks [P2] — ※ 발표일자 재확인 필요, N/A 표기 유보 |
| 버티브(VRT) | 엔비디아와 협력 확대 | 엔비디아와 AI 데이터센터용 800V DC 전력 아키텍처 공동 개발 협력 확대, 데이터센터 인프라 모델링·최적화용 프로덕션급 디지털 트윈 제품 출시 | 확인된 정확 발표일 N/A | Simply Wall St News [P3] |
| 크레도 테크놀로지(CRDO) | FMS 2026 참가 및 실적 | FY2026 매출이 전년 대비 약 3배(약 $13억) 증가 보도. 산타클라라 FMS(Flash Memory Summit) 2026(8/4~8/6)에서 최신 인터커넥트 제품 전시 | 2026-08-04~06 | ChipStockInvestor/QuiverQuant [P3] |
| Applied Digital(APLD) | FY2026 4분기 실적 발표 | 2026-07-27 실적 발표(구체 수치 검증 불가) | 2026-07-27 | N/A — 세부 수치 미검증 |
| 셀레스티카(CLS) | 신규 뉴스 | 금일 기준 신규 확인된 뉴스 없음 | — | N/A |
| Super Micro Computer(SMCI) | 신규 뉴스 | 금일 기준 신규 확인된 뉴스 없음(2026-07-21 예비 실적 업데이트 이후 특이사항 미확인) | — | N/A |

---

## [5-A] AI 인프라 — 수요 측 / 하이퍼스케일러 CAPEX 〔실적시즌〕

| 항목 | 사실 내용(발표 수치·문구) | 전분기 대비(산술) | 출처일자 | 출처+태그 |
|---|---|---|---|---|
| 알파벳(Alphabet) | 2026 회계연도 CAPEX 가이던스를 $1,950억~$2,050억로 상향(직전 분기 $1,800억~$1,900억). 구글클라우드 매출 전년비 +82% $248억, 백로그 $5,140억 | 상단 기준 +$150억(+8.3%) | 2026-07-22 | Value Add VC 블로그 [P3] — 원자료: 알파벳 2Q26 실적발표 [P1] |
| 마이크로소프트(MSFT) | Azure 부문 4분기 CAPEX $410억. 시장에서는 FY2027 CAPEX 추정치를 $2,550억~$2,600억로 언급(사측 공식 연간 가이던스와 별개의 시장 추정치) | N/A(비교 기준 상이) | 2026-07-29 | Phemex 블로그 [P3] — ※ FY27 수치는 사측 공식 가이던스인지 애널리스트 추정치인지 재검증 필요 |
| 메타(Meta) | 연간 CAPEX 가이던스를 $1,300억~$1,450억로 상향 | 구체적 직전 가이던스 수치 미확인 | 2026-07-29 | Digitalapplied.com [P3] |
| 아마존(Amazon) | 2026 CAPEX 가이던스 약 $2,000억. AWS 2분기 매출 $422억(컨센서스 $405.4억 상회) | 구체적 직전 가이던스 수치 미확인 | 2026-07-30 | CNBC/TradingKey [P2] |
| 4사 합산 | 2026년 CAPEX 합산 $7,000억 이상 전망(보도 기준) | — | 2026-08-03 전후 | IG UK 등 종합 보도 [P3] |
| 실적 후 주가 반응 | MSFT +8~9%, AMZN +8~9%(시간외), META -9~10%(시간외), AAPL -4%(시간외) | — | 2026-07-29~30 | TradingKey · "Big Tech Earnings Scorecard" [P2] |
| 아마존 시가총액 | 2026-08-03 장중 사상 처음 시가총액 $3조 돌파(종가 기준 약 $3.08조), 애플·MS·알파벳·엔비디아에 이어 5번째 $3조 클럽 진입 | — | 2026-08-03 | CNBC · "Amazon (AMZN) stock market cap earnings" [P2] |

---

## [6] 시총 상위 10 — AI 무관 일반 이슈 〔실적시즌〕

| 기업 | 사실 내용 | 출처일자 | 출처+태그 |
|---|---|---|---|
| 애플(AAPL) | 2026 회계연도 3분기 매출 $1,094억(전년비 +16%), EPS $2.02(전년비 +29%)로 분기 실적 자체는 컨센서스 상회. 그러나 9월분기 매출 성장 가이던스를 9~11%로 제시(시장 예상 약 12% 하회), 아이폰·맥·아이패드 공급 제약 확대 경고. 서비스 매출 $307.4억(예상 $312.2억 하회). 중화권 매출 $188억(예상 $196억 하회). 시간외 주가 약 -4%(일부 보도 -6~7%) | 2026-07-30 | Bloomberg · "Apple's sales disappoint in China unit, services" [P2]; TradingKey [P2] |
| 테슬라(TSLA) / 버크셔해서웨이(BRK) | 금일 기준 신규 확인된 이슈 없음 | — | N/A |

---

## [7] 기관·대형 자금 수급

| 항목 | 종목 | 사실 내용 | 규모(수치) | 출처+태그 |
|---|---|---|---|---|
| 반도체 ETF 주간 자금유입 | SMH·SOXX·SOXL | 블룸버그 애널리스트 에릭 발추나스: 3개 ETF가 해당 주간 전체 ETF 중 최대 자금유입 기록(반도체 섹터 최초) | N/A(비율/절대액 미확인) | Stocktwits · Bloomberg 애널리스트 인용, 2026-08-03 [P2] |
| SMH 자금흐름 | SMH | 5일 순유입 $35.2억, 1개월 순유입 $54.8억, 3개월 순유입 $50.4억 | $35.2억(5일)/$54.8억(1개월)/$50.4억(3개월) | ETFdb.com 집계 [P3] — 집계 기준일 명시 안 됨 |
| SOXX·SOXL 일간 자금유입 | SOXX, SOXL | 하루 동안 $21억 이상 유입 보도(7월 하순) | $21억+(1일) | Benzinga · "Semiconductor ETFs Dominate Inflows" [P3] |
| SOXX 단일일 자금유입 | SOXX | 단일 거래일 $54억 유입 보도 | $54억(1일) | ETF.com · "Semiconductor ETFs Roar Back" [P3] — ※ 위 Benzinga 수치와 시점·금액 상이, 별도 보도로 병기 |

---

## [7-A] Insider Trading (SEC Form 4) 〔조건부〕

N/A — 금일(2026-08-05) 기준 대상 기업(NVDA·AVGO·CRDO·CLS·APLD·VRT·SMCI) 신규 Form 4 공시 확인되지 않음.
참고(신규 아님, 구정보): NVDA 이사 Mark A. Stevens 관련 신탁이 2026-06-18 보통주 885,000주를 가중평균 약 $209~210에 시장매도 — StockTitan/SECForm4.com [P1], 거래유형(10b5-1/재량 여부) 미확인.

---

## [8] 향후 14일 주요 일정 (2026-08-05 ~ 2026-08-19)

### 경제 일정
| 날짜 | 시각(ET·KST) | 이벤트 | 컨센서스 | 이전치 | 출처 |
|---|---|---|---|---|---|
| 2026-08-05(수) | 10:00 ET / 23:00 KST | ISM 서비스업 PMI(7월) | 54.5 | 54.0 | Continuum Economics [P3] |
| 2026-08-07(금) | 8:30 ET / 21:30 KST | 7월 고용보고서(비농업고용·실업률) | N/A(신뢰 가능한 컨센서스 미확인) | N/A | FinanceCalendar.com [P3] |
| 2026-08-12(수) | 8:30 ET / 21:30 KST | CPI(7월) | N/A | N/A | MacroOrNoise.com [P3] |
| 2026-08-13(목) | 8:30 ET / 21:30 KST | PPI(7월) | N/A | N/A | Quasa.io [P3] |

### 기업 일정
| 날짜 | 기업 | 이벤트 | 컨센서스 EPS | 컨센서스 매출 | 출처 |
|---|---|---|---|---|---|
| 2026-08-11(화) | Super Micro Computer(SMCI) | 장마감 후 실적 발표(콘퍼런스콜 5pm ET) | N/A | N/A | WallStreetHorizon/TipRanks [P3] |

※ 엔비디아(NVDA) 2분기(FY2027) 실적발표는 2026-08-26 예정으로 확인되었으나, 14일 창(~8/19) 밖이므로 이번 회차에는 미기재.

---

## [9] 오늘의 사실 목록 (순위 없음, 섹션순 나열)

- [1] S&P500 7,736.52 마감, 전일比 +1.79%, 사상 최고 종가 · CNBC [P2]
- [1] Dow 54,085.88 마감, +907.47pt(+1.71%), 사상 최고 종가 · CNBC [P2]
- [1] NASDAQ 종합 26,584.99 마감, +2.59% · CNBC [P2]
- [1] Russell2000 2,981.908 마감, +1.73% · Yahoo Finance [P2]
- [1] VIX 16.3~16.6대에서 보합, 전일比 +0.01pt · historicaloptiondata.com [P3]
- [1] WTI 76.14달러, -5.23% · Forbes Advisor [P3]
- [1] DXY 99.9704, +0.01% · TradingEconomics [P3]
- [2] 미 10년물 국채금리 약 4.63%, 2년물 약 4.21% · 검색 집계 [P1]
- [2] 7월 FOMC, 정책금리 3.50~3.75% 동결, 9-3 표결로 이견 존재 · CNBC [P2]
- [2] 차기 FOMC 2026-09-16 예정 · 검색 집계 [P3]
- [3] ISM 서비스업 PMI(7월) 금일 23:00 KST 발표 예정, 컨센서스 54.5(미발표) · Continuum Economics [P3]
- [4] 팔란티어(PLTR) +29.45%, 2분기 매출 $19.4억·EPS $0.41로 컨센서스 상회, 연간 가이던스 상향 · CNBC [P2]
- [4] 인텔(INTC) +10%, 마벨(MRVL) +14%, 마이크론(MU) +8%, 반도체 업종 전반 랠리 · 247wallst.com [P2]
- [5] AMD 2분기 EPS $1.66·매출 $115억으로 가이던스 상회, 시간외 주가 8%대 하락 · Yahoo Finance/Fool.com [P2]
- [5] 아리스타 네트웍스 2분기 매출 첫 $30억 돌파($30.4억), 시간외 +13% · Businesswire/Yahoo Finance [P1][P2]
- [5] TSMC 2026 매출 성장률 전망 30%대로 상향 · Fool.com [P2]
- [5] 버티브, 엔비디아와 800V DC 전력 아키텍처 공동개발 협력 확대 · Simply Wall St [P3]
- [5-A] 알파벳 2026 CAPEX 가이던스 $1,950억~2,050억로 상향 · Value Add VC [P3]
- [5-A] 메타 연간 CAPEX 가이던스 $1,300억~1,450억로 상향 · Digitalapplied.com [P3]
- [5-A] 아마존 2026 CAPEX 가이던스 약 $2,000억, AWS 2분기 매출 $422억 · CNBC [P2]
- [5-A] 아마존 시가총액 8/3 장중 처음 $3조 돌파 · CNBC [P2]
- [6] 애플 9월분기 매출 성장 가이던스 9~11%(시장예상 12% 하회), 시간외 주가 약 -4% · Bloomberg [P2]
- [7] SMH·SOXX·SOXL, 해당 주간 전체 ETF 중 최대 자금유입(반도체 섹터 최초) · Bloomberg 애널리스트 인용 [P2]
- [7-A] 대상 기업 신규 Form 4 공시 없음 · N/A
- [8] 7월 고용보고서 8/7, CPI(7월) 8/12, PPI(7월) 8/13 발표 예정 · 각 출처 [P3]
- [8] Super Micro Computer(SMCI) 실적 8/11 장마감 후 예정 · WallStreetHorizon [P3]
